### ISSUE TITLE
alphametics: Tests are taking a long time to complete

### ISSUE THREAD

**Issue by N-Parsons** [exercism/python#1066]
I was having a look at the `travis-ci` build checks, and it looks like `alphametics` is taking up a large chunk of time when running the test-suite. I feel like this is an issue.

## Run times for an [example](https://travis-ci.org/exercism/python/builds/293841177?utm_source=github_status&utm_medium=notification):
* Python 2.7: **1 min 19 s** / 1 min 59 s
* Python 3.3: **1 min 45 s** / 2 min 39 s
* Python 3.4: **1 min 15 s** / 2 min 2 s
* Python 3.5: **34 s** / 1 min 11s
* Python 3.6: **2 min 46 s** / 3 min 47 s

There's obviously quite a bit of variation in the run-time of the `alphametics` test and in the overall run-time of the checks, but it's fairly consistently taking about half of the total check time. _(Variation is presumably due to varying loads on the service)._

## Possible solutions:
1. Leave it as is - accept the additional run time for tests.
2. Add `@unittest.skip` to last test and note it in the README.
3. Refactor the example for `alphametics` to improve performance (if possible).

For me, the ideal solution would be to refactor the example code to improve the performance, but I'm not sure how feasible that actually is.

Alternatively, we could skip the test for now. On my system, skipping the last test cuts the run time down from ~35 seconds to ~5 seconds, which would seem to be worth doing. This skip could be temporary and we could leave an open issue for refactoring the example in case anyone does find a way.

What do you think?

**Comment by m-a-ge** [comment]
Good catch 🦅 
I think we can comment the test for now and revisit it later (I'm a bit busy right now with other things).
This issue will be a reminder for us

**Comment by cmccandless** [comment]
@N-Parsons @m-a-ge See #524

**Comment by nikamirrr** [comment]
Hi, I know I promised to refactor it last weekend, but I was in the time crunch with work and a google foobar challenge.
So, I am not taking any more challenges this weekend and look forward to a more relaxed coding :) fixing this example.
Tomorrow is Friday! Peace to everyone :)
