### ISSUE TITLE
Create maintainer-specific docs

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#1095]
As mentioned in #1086 I think we should create some sort of maintainer-specific docs and document thing related to the best practices we use. It will help us stay on the same page etc

What do you think?

TODO:
- [ ] Add docs on how to choose Exceptions correctly per https://github.com/exercism/python/issues/1095#issuecomment-345554041

**Comment by cmccandless** [comment]
Some of the information I would imagine the proposed docs would contain (Conventions, Code Style) is already in the [README](https://github.com/exercism/python/blob/4f083db4d3e55feffccbbf743c5eaa20cfb6fb4e/README.md). I don't see why we couldn't put label documentation there as well?

**Comment by m-a-ge** [comment]
I thought that README is targeting contributors more than maintainers. For that reason I've created this issue

**Comment by N-Parsons** [comment]
@m-a-ge, I'm not sure what documentation we'd need that is specific to maintainers?

However, I think it might be worth putting together a `CONTRIBUTING.md` (or equivalent) that would give more detail than the README currently does about how to contribute, what conventions we follow, etc. This would be useful both for new people to find and read, and for us to be able to point to when something isn't quite right with a PR. We could probably achieve a lot of the kinds of things you are thinking about with such a document?

**Comment by m-a-ge** [comment]
@N-Parsons yes, that's a good idea

**Comment by N-Parsons** [comment]
Coming from #1080, part of this documentation could be a list of exception types and when to use them (something like the [Choosing Exceptions to Raise](https://github.com/pandas-dev/pandas/wiki/Choosing-Exceptions-to-Raise) Pandas has).

**Comment by cmccandless** [comment]
For now, [the README](https://github.com/exercism/python/blob/master/README.md) for this track is adequate as a contributing guide. If someone submits a PR for a more comprehensive CONTRIBUTING.md, it would be welcome, but this is not an urgent need at this time.
