### ISSUE TITLE
Nextercism: Short track description required

### ISSUE THREAD

**Issue by N-Parsons** [exercism/python#1102]
Nextercism requires us to write a short description of the Python track to appear on the [main track page](https://v2.exercism.io/tracks/python). I'm not sure how we go about submitting it once we've written it, but the beta site seems to suggest that it's up to us to do.

### Go
> Go is a compiled, open source programming language with a small, consistent syntax, a powerful standard library, and fantastic tooling. It's a great fit for web backends and command-line tools.

### Rust
> Rust is a compiled programming language designed for speed, concurrency, and memory safety. Rust programs can run almost anywhere, from low-power embedded devices to web servers.

### Java
> Java is a very widely used Object Oriented programming language. It's safe, simple to use and portable so that you can "write once, run anywhere".

### R
> R is an interpreted, open source programming language with powerful data manipulation and graphical capabilities. It has a thriving package ecosystem and is one of the most popular languages for data science.

**Comment by cmccandless** [comment]
From [the current about page for this track](http://exercism.io/languages/python/about):

> Python is a strong language for beginners. There are many resources available for programmers of all levels, the code is highly readable, and in many cases phrases are comparable to those in the English language.

Any objections to using this?

**Comment by N-Parsons** [comment]
It would end up feeling quite redundant, since both would appear on the same page. I also don't feel like it completely captures what Python is in the same way that the other examples do.

**Comment by cmccandless** [comment]
I didn't realize that both would be on the same page. In that case, we definitely need something different.

**Comment by cmccandless** [comment]
I suggest we summarize [this page](https://wiki.python.org/moin/BeginnersGuide/Overview).

**Comment by N-Parsons** [comment]
Something like this?

> Python is a clear and powerful object-oriented programming language with an elegant and easy-to-read syntax. It is ideal for prototyping and ad-hoc tasks, but also sees wide use in scientific computing, web development, and [something else].

**Comment by cmccandless** [comment]
Looks good to me.

> [something else]

Perhaps "automation"?

**Comment by N-Parsons** [comment]
Sounds good.

From the looks of the [exercism/rust](https://github.com/exercism/rust/blob/master/config.json) repo, this text just goes into the `config.json` as `blurb` - I'll make a PR for it now.

> Python is a clear and powerful object-oriented programming language with an elegant and easy-to-read syntax. It is ideal for prototyping and ad-hoc tasks, but also sees wide use in scientific computing, web development, and automation.
