### ISSUE TITLE
protein-translation: update tests

### ISSUE THREAD

**Issue by sjwarner-bp** [exercism/python#1103]
As identified in #784, some of the exercise test-suites are out-of-date, protein-translation is one of them. It would therefore be really helpful for people to go through and update the test suite to match the canonical data.

Tests should typically be ordered according to their order in the canonical data, since this makes it easier to check and update them in future. If you think that there's a better order, please let us know your reasoning in your PR.

If there are some additional tests that currently exist in this track but which aren't in the canonical data, these can be kept if you think that they are useful. They should be placed at the bottom of the test cases, and it would also be super-helpful if you could add a comment before them saying # Additional tests for this track to make it clear that they aren't part of the canonical data.

The version string should be placed just before the first test class and followed by a blank line. For this exercise, the version string is:

`# Tests adapted from problem-specifications/canonical-data.json @ v1.0.0`

**Test suite:** [/exercism/python/exercises/protein-translation/protein_translation_test.py](https://github.com/exercism/python/blob/master/exercises/protein-translation/protein_translation_test.py)
**Canonical data:** [exercism/problem-specifications//exercises/protein-translation/canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/protein-translation/canonical-data.json)

**Comment by cmccandless** [comment]
Since #784 is still open, I don't think we need a new issue here. It would be better to comment in #784 the list of exercises which have had canonical-data implemented since the original list of out-of-date exercises was made there.

Please close this issue and point all discussion on out-of-date tests to #784.

**Comment by N-Parsons** [comment]
@sjwarner-bp, thanks for raising this as an issue.

@cmccandless, I disagree that this issue should be closed, so I'm going to reopen it. We have issues for all of the different exercises that need to have their tests updated, and this just follows on with that - #784 is a general issue, and this is a specific one.

**Comment by cmccandless** [comment]
You are correct. I misunderstood that this issue was meant to be a new meta issue for all exercises with newly implemented canonical data. Please do reopen.

⁣


Corey McCandless​
