### ISSUE TITLE
beer-song: update tests to canonical-data v2.0.0

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1128]
Currently, the `beer-song` exercise does not reference the [canonical data](https://github.com/exercism/problem-specifications/blob/5c3baae204802cf1c0e73493a671b1de5da10f0f/exercises/beer-song/canonical-data.json). The current tests must be checked and, if necessary, updated to match the canonical data. A comment line referencing the canonical data version must also be added (see #784 for the format of this comment).

**Comment by ajubin** [comment]
Hi, I'd like to contribute to this repo, 
I've read the contributing guide, should I do a pull request directly once I fixed the issue ?

**Comment by cmccandless** [comment]
@ajubin This issue already has a PR (#1165). If you would like to contribute, please see the [list of exercises with the `help wanted` label](https://github.com/exercism/python/labels/help%20wanted).
