### ISSUE TITLE
2 bugs in pig_latin_test.py (Python 3) [Resolved]

### ISSUE THREAD

**Issue by marcuslxxii** [exercism/python#1137]
In pig_latin_test.py 2 assertEqual they should instead be assertNotEqual (I searched the internet if Pig Latin had exceptions, and I did not find anything).

```
def test_word_beginning_with_xr(self):
    self.assertEqual(translate("xray"), "xrayay")  # they should instead be assertNotEqual
    self.assertEqual(translate("xray"), "ayxray")  # is correct

def test_y_is_treated_like_a_consonant_at_the_beginning_of_a_word(self):
    self.assertEqual(translate("yellow"), "ellowyay")  # they should instead be assertNotEqual
    self.assertEqual(translate("yellow"), "yelloway")  # is correct
```

**Comment by cmccandless** [comment]
These tests are based off of the [canonical data] (https://github.com/exercism/problem-specifications/blob/master/exercises/pig-latin/canonical-data.json). If you believe one to be incorrect, please create an issue there. If there is a change resulting in your issue, it will propagate to the Python track (and other tracks) eventually.

**Comment by marcuslxxii** [comment]
Thanks.
The description of the problem, however, says nothing about the exception in words beginning with "xr", and says nothing about the anomaly, in English, of the letter "y", which is a vowel normally, but becomes consonant if it is starting of a word and is followed by a vowel.

**Comment by cmccandless** [comment]
@marcuslxxii Good point on the description. If you are going to open an issue in the problem spec repo, please mention that in the new issue as well. 

As you have marked this resolved, and this is out of scope for this repository, I am going to close this issue here.
