### ISSUE TITLE
ISBN-verifier: implement new exercise

### ISSUE THREAD

**Issue by pheanex** [exercism/python#1142]
Has been started, but not finished yet in #887 and #890
[ISBN-Verifier Problem description](https://github.com/exercism/problem-specifications/blob/master/exercises/isbn-verifier/description.md)
This issue is for coordination.

**Comment by pheanex** [comment]
I would drop the ISBN-13 part, since:

- I don't think its more complex than ISBN-10 and therefore is just a boring coding-task
- problem specifications has no test-cases for it

If somebody insists on adding ISBN-13, I'd suggest:

- using the same verification methods for ISBN-10 and ISBN-13 instead of separate methods
- discussing this (and test-cases) with problem-specifications upstream

**Comment by cmccandless** [comment]
I agree with adhering to the problem spec. I'm although the description does mention ISBN-13, there are no tests currently defined, so I am happy to leave it alone and stick to ISBN-10. If ISBN-13 tests are later added, we can create a new issue/PR to implement them here.

**Comment by pheanex** [comment]
Ok, then. Ready for review :smile:
