### ISSUE TITLE
Bug in dot_dsl_test.py ?

### ISSUE THREAD

**Issue by marcuslxxii** [exercism/python#1151]
In the file dot_dsl_test.py there are 2 errors in the test_graph_with_attributes() function in the following two lines?
```
...
(NODE, "b", {"label", "Beta!"}),  # correct: (NODE, "b", {"label": "Beta!"}),
...
Node("b", {"label", "Beta!"})])  # correct: Node("b", {"label": "Beta!"})])
...
```
I do not think they are correct because the attributes must be in the form of a dictionary, to have the form "property": "value".

**Comment by cmccandless** [comment]
@marcuslxxii I'm not sure what you mean; can you provide a more detailed explanation please?

**Comment by marcuslxxii** [comment]
In general to describe a list of attributes (in the description of this problem the example is given
```
bgcolor="yellow"
color="red"
...
```
) it's a list of attribute names and their values, so a dictionary is perfect. And indeed in the examples are passed dictionaries, except in the two lines that I highlighted. In them instead of ":" there is "," so it is no longer a dictionary but a "set".

**Comment by cmccandless** [comment]
@marcuslxxii I see it now, good catch!
