### ISSUE TITLE
Python 3.3.x EOL

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1157]
[As of Sep. 29, 2017, Python 3.3.x has reached end of life.](https://www.python.org/dev/peps/pep-0398/#x-end-of-life) As 3.3.x occasionally trips up Travis-CI builds for various reasons, I advocate that we discontinue supporting Python 3.3 in this repository. However, I will not take action on this without input from the other maintainers.

@Dog @behrtam @N-Parsons @m-a-ge Thoughts?

Input from other contributors to the repository and other Exercism members is also welcome.

**Comment by Dog** [comment]
Have wee seen these build issues on the repo? If so I think its a good idea. If not then I think keeping support for now may be better.

**Comment by cmccandless** [comment]
@Dog I am not certain that we have observed those issues on this repo. I think that we have at least once, but I do not know of a specific Travis build to use as an example.

**Comment by N-Parsons** [comment]
My personal preference would be to remove support, since the Python developers have already done so, and I don't think that it makes much sense to test our example solutions against an unsupported version.

**Comment by mRcfps** [comment]
I'm in favor of removing support for Python 3.3.x. Besides the possibility of tripping up CI builds, the absence of

**Comment by mRcfps** [comment]
I'm in favor of removing support for Python 3.3.x. Apart from the possibility of tripping up CI builds, at least we can gain an observable building speed-up by dropping this unsupported version, which is especially the case when the maintaining work is heavy.

**Comment by Dog** [comment]
My opinion is mainly because I feel this is early optimization. I don't see any negative to advertising our solutions work with 3.3 - because they do. If someone is learning and already has Python 3.3, I'd prefer to not have them think they then have to try to figure out how to upgrade their version of Python.

There also isn't a reason we can't change our mind if we do run into a problem. We haven't seen these build errors, and the build occurs in the background of our requests. You may have to wait a couple seconds longer for the tests to run under 3.3 in the suite, but I'd personally prefer to be flexible since this is for learning.

**Comment by cmccandless** [comment]
>  I'd personally prefer to be flexible since this is for learning.

Good point. I think sometimes I get so caught up in the optimization and maintenance side of things here that I can forget this. I think the best move is to keep 3.3 for now, and deal with issues as they arise *in this repo*. If nothing else, this issue will serve as a good record for why we still test for an unsupported version of Python.

**Comment by Dog** [comment]
@cmccandless It also gives us a solution for removing support as soon as one of those problems arise =)

**Comment by cmccandless** [comment]
Reopening discussion as latest version of Pyflakes (2.0.0) removes support for Python 3.3.x (#1390).

#### Options
- Remove Python3.3.x support
- Do not upgrade Pyflakes (i.e. close #1390 without merging)
- Do not run linting checks if Python version is 3.3.x (BAD IDEA, but technically an option)

**Comment by Dog** [comment]
I think it makes sense. I was only one that voiced against it, so I went ahead and merged it.
