### ISSUE TITLE
Bob Tests produces different results between 2/3

### ISSUE THREAD

**Issue by AstraLuma** [exercism/python#123]
Under Python 2: `'ÜMLäÜTS!'.isupper() is`True`, but`u'ÜMLäÜTS!'.isupper()`is`False`.

Under Python 3: `'ÜMLäÜTS!'.isupper()` is `False`

The problem is that the string is using precomposed characters and under Python 2, `str` is encoded in the source code encoding of the tests (UTF-8).

**Comment by englishm** [comment]
I ran into this issue while trying to demonstrate Exercism to a student new to programming. It was an unfortunate hurdle to encounter so early in the process. 

There is certainly value in understanding the intricacies of Python unicode handling (and differences between 2 and 3), but I don't think Exercism's `hello-world` exercise is the right place to be confronted with those things.

```
$ python2.7 hello_world_test.py                                                        
.E.
======================================================================
ERROR: test_hello_with_umlaut_name (__main__.BobTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "hello_world_test.py", line 26, in test_hello_with_umlaut_name
    hello_world.hello('Jürgen')
  File "/Users/english/exercism/python/hello-world/hello_world.py", line 8, in hello
    return "Hello, {}!".format(name)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 1: ordinal
 not in range(128)                                                                    

----------------------------------------------------------------------
Ran 3 tests in 0.000s

FAILED (errors=1)
```

```
$ python3 hello_world_test.py 
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK
$ 
```

For `hello_world.py`:

```python
def hello(name=''):
    if name != '':
        return "Hello, {}!".format(name)
    else:
      return 'Hello, World!'
```

(Very nearly the current [example.py](https://github.com/exercism/python/blob/3fd4ee47274dadd6d895cea7502db55f29ff9103/exercises/hello-world/example.py), so the results should be the same)


And `hello_world_test.py`:

```python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals
import unittest

import hello_world


class BobTests(unittest.TestCase):

    def test_hello_without_name(self):
        self.assertEqual(
            'Hello, World!',
            hello_world.hello()
        )

    def test_hello_with_name(self):
        self.assertEqual(
            'Hello, Jane!',
            hello_world.hello('Jane')
        )

    def test_hello_with_umlaut_name(self):
        self.assertEqual(
            'Hello, Jürgen!',
            hello_world.hello('Jürgen')
        )

if __name__ == '__main__':
    unittest.main()
```

Note that 2.7.x is still the default Python installed on many platforms, including macOS:

```
$ /usr/bin/python --version
Python 2.7.10
```

**Comment by kytrinyx** [comment]
@englishm I've opened a new issue in the Python track about this: https://github.com/exercism/python/issues/1353
