### ISSUE TITLE
react: update tests to v1.1.0

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1257]
[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/react/canonical-data.json)

**Comment by mRcfps** [comment]
@cmccandless Currently this exercise is implemented in a way quite different from [Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/react/canonical-data.json). Should we comply with canonical implementation?

**Comment by cmccandless** [comment]
@mRcfps The canonical data for this exercise did not exist when I implemented the exercise in this track, so I based the tests off of the C# track. Now that there is canonical data, I would prefer to follow that.
