### ISSUE TITLE
Typo in exercises/meetup on line 12

### ISSUE THREAD

**Issue by edvoinea** [exercism/python#1349]
- The wednesteenth of January 2017

Maybe change to '- The second Wednesday of January 2017' ?

**Comment by cmccandless** [comment]
Not a typo. This is meant to be interpreted as "the first Wednesday of January 2017 for which the day of the month is a teen (13-19)".

For future reference, issues with problem descriptions should be raised in [exercism/problem-specifications](https://github.com/exercism/problem-specifications).
