### ISSUE TITLE
Track configuration contains improperly locked exercises

### ISSUE THREAD

**Issue by nywilken** [exercism/python#1363]
In the upcoming release of [Configlet v3.8.0](https://github.com/exercism/configlet/issues/121), the lint command will now verify that locked exercises meet the unlocked_by criteria, as defined by the track [configuration spec](https://github.com/exercism/docs/blob/master/language-tracks/configuration/exercises.md):

- Core exercises can not be unlocked by other exercises.
- Non-core exercises can only be unlocked by core exercises.

Before cutting a release of Configlet I am opening issues on all tracks found to contain one or more unlocked_by violations so that maintainers of the track can validate and remedy the violations.

```

-> The exercise 'linked-list' is being unlocked by a non-core exercise. Non-core exercises can only be unlocked by core exercises. 
-> The exercise 'diffie-hellman' is being unlocked by a non-core exercise. Non-core exercises can only be unlocked by core exercises.
```

**Comment by cmccandless** [comment]
#1355 already exists and resolves this.

**Comment by nywilken** [comment]
@cmccandless thanks for the heads up. I created this issue via `github/hub` without checking if there was an already open issue. I’ll go ahead and close this issue and track the PR 🙏
