### ISSUE TITLE
unable to submit - open C:\..\hello-world.py: The system cannot find the file specified

### ISSUE THREAD

**Issue by Sjoshi-TYCS** [exercism/python#1391]
Running from Jupyter Notebook. 

!exercism submit hello-world.py #The path to the file is correct since CWD is same as the file directory.
unable to submit - open C:\exercism\python\hello-world\hello-world.py: The system cannot find the file specified.

!exercism debug # No workspace directory seeb in info as mentioned [here ](http://exercism.io/exercises/python/hello-world/readme)

**** Debug Information ****
Exercism CLI Version: 2.4.1
Exercism CLI Latest Release: 2.4.1
OS/Architecture: windows/amd64
Build OS/Architecture windows/amd64
Home Dir: C:\Users\User
Config File: C:\Users\User\.exercism.json
API Key: bdee*************************807
Exercises Directory: C:\exercism
Testing API endpoints reachability
* GitHub API: https://api.github.com/ [connected] 64.0622ms
* XAPI: http://x.exercism.io [connected] 229.162ms
* API: http://exercism.io [connected] 256.1814ms

**Comment by cmccandless** [comment]
@Sjoshi-TYCS have you found a solution? If not...

> !exercism submit hello-world.py

Is this the *exact* command you typed? If so, the correct file name is actually `hello_world.py` (Note the underscore). If this is not your solution...

> Running from Jupyter Notebook

From the same Jupyter terminal, are you able to run `!python hello_world

While you are working in the Python track, the maintainers at the [exercism CLI repository](https://github.com/exercism/cli) may be able to help you more, as this appears to be either an environment issue or a CLI client issue. You may want to try raising an issue there.

**Comment by Sjoshi-TYCS** [comment]
It was indeed the underscore problem.
