### ISSUE TITLE
Ensure Python track is ready for v2 launch

### ISSUE THREAD

**Issue by kytrinyx** [exercism/python#1401]
There are a number of things we're going to want to check before the v2 site goes live. There are notes below that flesh out all the checklist items.

- [x] The track has a page on the v2 site: https://v2.exercism.io/tracks/python
- [x] The track page has a short description under the name (not starting with `TODO`)
- [x] The "About" section is a friendly, colloquial, compelling introduction
- [ ] The "About" section follows the formatting guidelines
- [x] The code example gives a good taste of the language and fits within the boundaries of the background image
- [x] There are exercises marked as `core`
- [x] Exercises have rough estimates of difficulty
- [x] Exercises have topics associated with them
- [x] The first exercise is `auto_approve: true`

## Track landing page

The v2 site has a landing page for each track, which should make people want to join it. If the track page is missing, ping `@kytrinyx` to get it added.

### Blurb
If the header of the page starts with `TODO`, then submit a pull request to https://github.com/exercism/python/blob/master/config.json with a `blurb` key.  Remember to get [configlet](https://github.com/exercism/configlet/releases/latest) and run `configlet fmt .` from the root of the track before submitting.

### About section
If the "About" section feels a bit dry, then submit a pull request to https://github.com/exercism/python/blob/master/docs/ABOUT.md with suggested tweaks.

#### Formatting guidelines
In order to work well with the design of the new site, we're restricting the formatting of the `ABOUT.md`. It can use:

* Bold
* Italics
* Links
* Bullet lists
* Number lists

Additionally:

* Each sentence should be on its own line
* Paragraphs should be separated by an empty line
* Explicit `<br/>` can be used to split a paragraph into lines without spacing between them, however this is discouraged.

### Code example
If the code example is too short or too wide or too long or too uninteresting, submit a pull request to https://github.com/exercism/python/blob/master/docs/SNIPPET.txt with a suggested replacement.

## Exercise metadata
Where the v1 site has a long, linear list of exercises, the v2 site has organized exercises into a small set of required exercises ("core").

If you update the track config, remember to get [configlet](https://github.com/exercism/configlet/releases/latest) and run `configlet fmt .` from the root of the track before submitting.

### Topic and difficulty
Core exercises unlock optional additional exercises, which can be filtered by topic an difficulty, however that will only work if we add topics and difficulties to the exercises in the track config, which is in https://github.com/exercism/python/blob/master/config.json

### Auto-approval
We've currently made any hello-world exercises auto-approved in the backend of v2. This means that you don't need mentor approval in order to move forward when you've completed that exercise.

Not all tracks have a hello-world, and some tracks might want to auto approve other (or additional) exercises.

## Track mentors
There are no bullet points for this one :)

As we move towards the launch of the new version of Exercism we are going to be ramping up on actively recruiting people to help provide feedback. Our goal is to get to 100%: everyone who submits a solution and wants feedback should get feedback. Good feedback.

If you're interested in helping mentor the track, check out http://mentoring.exercism.io/

#
When all of the boxes are ticked off, please close the issue.

Tracking progress in https://github.com/exercism/meta/issues/104

**Comment by cmccandless** [comment]
@kytrinyx I believe I know the answer, I but I wanted documentation of the correct answer:

>  The first exercise is `auto_approve: true`

> We've currently made any hello-world exercises auto-approved in the backend of v2.

Does this mean that if a track (i.e. this track) uses `hello-world` as its first exercise, there are no changes necessary for this item?

**Comment by jackhughesweb** [comment]
@cmccandless I've submitted a pull request #1405 for auto_approve (https://github.com/exercism/c/issues/303#issuecomment-396647726)

**Comment by kytrinyx** [comment]
> Does this mean that if a track (i.e. this track) uses hello-world as its first exercise, there are no changes necessary for this item?

Sorry that was super confusing. I'd actually like to make the auto-approve explicit in the config and then remove the hack in the website code.
