### ISSUE TITLE
Meetup Exercise broken

### ISSUE THREAD

**Issue by TheAnig** [exercism/python#1407]
Unable to run tests for the Meetup Exercise
`ImportError: cannot import name 'MeetupDayException'`

**Comment by NobbZ** [comment]
You need to add an appropriate definition to your module to make it pass.

**Comment by cmccandless** [comment]
To expand on what @NobbZ said, if you look at the full error message you're getting:

```Bash
meetup_test.py:4: in <module>
    from meetup import meetup_day, MeetupDayException
E   ImportError: cannot import name 'MeetupDayException'
```

Notice which module these symbols are being imported from, `meetup`. By this point in the track, you should know that that is the name of the module you are writing, so everything the tests import from that module you must define.

If you have any more questions on this subject, please feel free to ask and we would be happy to assist. If not, please close this issue.

**Comment by TheAnig** [comment]
Sorry I'm an idiot, it was 3 in the morning and I was sleepy but wanted to solve the challenge before going to sleep.
