### ISSUE TITLE
house: results are now nonsense...

### ISSUE THREAD

**Issue by yawpitch** [exercism/python#1415]
#1354 seems to have fixed an apparent inconsistency in test data with the other "songs", but in doing so has made the actual results make no sense.

This:
    expected = [
            "This is the cat",
            "that killed the rat",
            "that ate the malt",
            "that lay in the house that Jack built."
    ]

Was updated to this:

    expected = [
            "This is the cat"
            "that killed the rat"
            "that ate the malt"
            "that lay in the house that Jack built."
    ]

But that means that what was returned ["This is the cat", "that killed the rat", "that ate the malt", "that lay in the house that Jack built"] is now ["This is the catthat killed the ratthat ate the maltthat lay in the house that Jack built"] ... now you do indeed have a single sentence, but it's full of nonsense words.

The data may have appeared inconsistent by breaking up sentences, but I would argue that what it actually did was break up *stanzas*, which have no bearing on sentences. Poems (and songs) are traditionally delivered by breaking sentences up into stanzas, normally along either boundaries of meter or rhyme repetition.

**Comment by cmccandless** [comment]
# Summary
### What should have been done in this exercise
Replace newlines with spaces.

### What was actually done
Newlines were removed.

**Comment by yawpitch** [comment]
Well, actually, I think I said that newlines were appropriate ... but if you're going to destroy the structure of a poem by removing newlines, at least replace them with spaces.

**Comment by cmccandless** [comment]
Forgive my previous concise reply. I simply meant that when this exercise was updated to match the canonical data, it was done incorrectly. The canonical data replaced newlines with spaces.

**Comment by yawpitch** [comment]
Fair enough. Spaces are sufficient, though the canonical data should really never have been updated. That said, the stanza structure and its willingness to break up sentences is a concept somewhat reserved to the printing of (generally English) poetry.
