### ISSUE TITLE
complex-numbers machine-precision friendly unittest

### ISSUE THREAD

**Issue by SinRas** [exercism/python#1429]
Unittest must be changed in order to take into account machine precision? or there is something wrong with my machine?

- __OS:__ _Ubuntu 16.04 x64_
- __Python:__ _3.5.2_

Two methods fail for me: __exp__ and __truediv__.
Here is my implementation of __Division__ and __Exponentiation__:
```
# Get cartesian representation from polar representation
    @staticmethod
    def cartesian_from_polar( r, theta ):
        """Given z = r * exp( i * theta ), calculates
        z = real + i * imaginary
        """
        # Cartesian Representation
        real = r * math.cos(theta)
        imaginary = r * math.sin(theta)
        # Return
        return( real, imaginary )
# Division
def __truediv__(self, other):
        """Complex Number Division
        z = r * exp( i * theta ), w = r' * exp( i * theta' ) =>
        z / w = ( r/r' ) * exp( i*(theta - theta') )
        """
        # Calculate Components
        r = self.r / other.r
        theta = self.theta - other.theta
        real, imaginary = ComplexNumber.cartesian_from_polar( r, theta )
        # Return new instance
        return( ComplexNumber( real, imaginary ) )
# Exponentiation
def exp(self):
        """Complex Number Exponentiation
        z = a + i * b =>
        exp(z) = exp(a) * exp( i * b )
        """
        # Calculate Components
        r = math.exp(self.real)
        theta = self.imaginary
        real, imaginary = ComplexNumber.cartesian_from_polar( r, theta )
        # Return new instance
        return( ComplexNumber( real, imaginary ) )
```
here is the failed unittest:
```
...........F..F.F..............
======================================================================
FAIL: test_divide_numbers_with_real_and_imaginary_part (__main__.ComplexNumbersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "complex_numbers_test.py", line 114, in test_divide_numbers_with_real_and_imaginary_part
    self.assertEqual(input_number / divider, expected)
AssertionError: 0.44 +i*0.07999999999999999 != 0.44 +i*0.08

======================================================================
FAIL: test_eulers_identity_formula (__main__.ComplexNumbersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "complex_numbers_test.py", line 156, in test_eulers_identity_formula
    self.assertEqual(input_number.exp().imaginary, expected.imaginary)
AssertionError: 1.2246467991473532e-16 != 0

======================================================================
FAIL: test_exponential_of_a_number_with_real_and_imaginary_part (__main__.ComplexNumbersTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "complex_numbers_test.py", line 174, in test_exponential_of_a_number_with_real_and_imaginary_part
    self.assertEqual(input_number.exp().imaginary, expected.imaginary)
AssertionError: 2.4492935982947064e-16 != 0
```

**Comment by SinRas** [comment]
ok just found the example solution. yet i guess the problem is still there (maybe in another form).

1. [complex-numbers/example.py#exp](https://github.com/exercism/python/blob/b214e203fa97d3b55b2bb644f148210d61cf35e9/exercises/complex-numbers/example.py#L42-L45) this definition of `exp` uses `round( ..., 8 )` which either should be mentioned in the instructions (if approximate should be returned) or tests should change
2. [complex-numbers/example.py#truediv](https://github.com/exercism/python/blob/b214e203fa97d3b55b2bb644f148210d61cf35e9/exercises/complex-numbers/example.py#L27-L33) this implementation apparently introduces negligible error in the specific test [test_divide_numbers_with_real_and_imaginary_part](https://github.com/exercism/python/blob/b214e203fa97d3b55b2bb644f148210d61cf35e9/exercises/complex-numbers/complex_numbers_test.py#L110-L114)

**Comment by cmccandless** [comment]
From my own testing, I think the solution here is to use `TestCase.assertAlmostEqual` instead of `TestCase.assertEqual` to avoid requiring the implementation to round values.

**Comment by SinRas** [comment]
@cmccandless thanks! I've have no experience with `unittest`. :smile: 
Since mentors will check solutions after submission, [TestCase.assertAlmotsEqual](https://docs.python.org/3.5/library/unittest.html#unittest.TestCase.assertAlmostEqual)  (which based on their implementation is essentially rounding before testing equality) is fine.
