### ISSUE TITLE
Blocked track progress

### ISSUE THREAD

**Issue by mikewalker** [exercism/python#1453]
I was receiving mentor feedback for a few iterations of a core exercise. The mentor feedback turn around was fairly quick until I got to what I think is the final solution. This is when the mentor went MIA. 

Do other mentors pick up solutions when this happens or once you start a conversation with a mentor does that follow to completion?

The reason I ask is that I would like to get this exercise approved so that I can start working on the next core exercise.

**Comment by mikewalker** [comment]
Thanks, I suspected that was the case here is the exercise  UUID bf3550d0840d4ae0ad1025b98cd55a95. 

Maybe there needs to be some sort of threshold that releases the exercise from the mentor. This would help in cases where mentors go on holidays, or real life takes them away from being able to respond.

**Comment by Smarticles101** [comment]
@mikewalker sorry about that! I went ahead and looked over the last iteration you made and approved it for you so you can continue :) I think your last mentioned idea of having a threshold to release an exercise is a good idea. That if a mentor who has already commented doesn't respond to another iteration say, in three days, that the exercise gets put back into other mentor's dashboards? Maybe @kytrinyx or @iHiD would have more thoughts on that.

**Comment by mikewalker** [comment]
Thanks a lot, moving onward in the track now. :+1:

**Comment by kytrinyx** [comment]
It sounds like this has been resolved. If it isn't, would you please open an issue in http://github.com/exercism/exercism/issues?
