### ISSUE TITLE
Remove obsolete version tracking assertions in exercises

### ISSUE THREAD

**Issue by kytrinyx** [exercism/python#1461]
Some tracks have added assertions to the exercise test suites that ensure that the solution has a hard-coded version in it.
In the old version of the site, this was useful, as it let commenters see what version of the test suite the code had been written against, and they wouldn't accidentally tell people that their code was wrong, when really the world had just moved on since it was submitted.

If this track does not have any assertions that track versions in the exercise tests, please close this issue.

If this track _does_ have this bookkeeping code, then please remove it from all the exercises.

See https://github.com/exercism/exercism/issues/4266 for the full explanation of this change.

**Comment by cmccandless** [comment]
Version assertions are not included in Python track solutions; Closing.
