### ISSUE TITLE
pythagorean-triplet: update tests to v1.0.0

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1510]
The [test suite](https://github.com/exercism/python/blob/master/exercises/pythagorean-triplet/pythagorean_triplet_test.py) for pythagorean-triplet is out of date and needs updated to conform to the [latest canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/pythagorean-triplet/canonical-data.json).

**Comment by omer-g** [comment]
UPDATE: I see now that without using primitive triplets the canonical tests take very long (the last 4 tests took 169s on my machine). An algorithm that uses primitive triplets runs in 2 seconds. In the updated canonical instructions, there is no mention of primitive triplets. I think it would be very difficult for students to figure this out by themselves. Should something be done about this?

**Comment by cmccandless** [comment]
@omer-g 
> Should something be done about this?

A hint about primitive triplets might be useful. It's worth raising an issue or a PR in the problem-specifications repository. If the change is implemented there, it will propagate to this track (as well as the other tracks).

**Comment by omer-g** [comment]
Thanks, I'll try to raise an issue there when I get a chance. However, for now, do you think the `primitive_triplets()` and the long comment about it in the test file should stay in the next PR? The canonical tests do not check for it and it is not mentioned in the current description.

Another small thing, I noticed that the current implementation in `example.py` does not use primitive triplets when looking for triplets in a range, so the new JSON tests will take a very long time with it. I assume `example.py` is used for CI. Could the code there perhaps be replaced with a fast solution (your solution for example runs in 2 seconds :) )

**Comment by cmccandless** [comment]
> do you think the primitive_triplets function and the long comment about it in the test file should stay in the next PR? 

Probably not. Since the tests don't access it, that's an implementation detail not an exercise requirement.

> Could the code there perhaps be replaced with a fast solution?

Absolutely!

> your solution for example runs in 2 seconds

... which actually sounds slow when you put it that way. If you can find a faster one, try to contact the author and request permission to use their code. If that's as fast as it gets, you're welcome to copy mine if you wish.
