### ISSUE TITLE
largest-series-product: update tests to v1.2.0

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1529]
The [test suite](https://github.com/exercism/python/blob/master/exercises/largest-series-product/largest_series_product_test.py) for largest-series-product is out of date and needs updated to conform to the [latest canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/largest-series-product/canonical-data.json).

**Comment by giuseppegagliano** [comment]
Can I do it?
