### ISSUE TITLE
variable-length-quantity: update tests to v1.2.0

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1531]
The [test suite](https://github.com/exercism/python/blob/master/exercises/variable-length-quantity/variable_length_quantity_test.py) for variable-length-quantity is out of date and needs updated to conform to the [latest canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/variable-length-quantity/canonical-data.json).

**Comment by siejqa** [comment]
Do you mind if I work on it?

**Comment by cmccandless** [comment]
@siejqa Go for it!
