### ISSUE TITLE
sgf-parsing: deprecation warning due to an invalid escape sequence

### ISSUE THREAD

**Issue by pranasziaukas** [exercism/python#1550]
I am running Python 3.7.0 and `pytest-3.8.2`.

For me, this line
https://github.com/exercism/python/blob/f9029669c93de49bf9f794d674c18e069229b764/exercises/sgf-parsing/sgf_parsing_test.py#L78
returns a warning `DeprecationWarning: invalid escape sequence \]`.

**Comment by pranasziaukas** [comment]
#1551

**Comment by cmccandless** [comment]
Closed by #1551
