### ISSUE TITLE
sum-of-multiples: Example does not match canonical data

### ISSUE THREAD

**Issue by patiencedaur** [exercism/python#1567]
If we enter 0 as a multiple in the current example of `sum-of-multiples`, a ZeroDivisionError is raised.
[Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/sum-of-multiples/canonical-data.json) require processing the case when zero is in the list of multiples.
The example file does not take that into account, neither does the tests file.
I came across this issue when fixing the inconsistency of `sum-of-multiples-test.py` with canonical data.

**Comment by cmccandless** [comment]
Good catch! Please fix this in #1568 as well.

**Comment by DrJPizzle** [comment]
I think there was a mistake in your fix: if zero in the list, you don't necessary want to return 0. E.g.:
>    {
      "description": "the factor 0 does not affect the sum of multiples of other factors",
      "property": "sum",
      "input": {
        "factors": [3, 0],
        "limit": 4
      },
      "expected": 3
},
I think the ref'd PR fixes this issue neatly.
