### ISSUE TITLE
Kindergarten garden: incomplete description

### ISSUE THREAD

**Issue by swalladge** [exercism/python#1573]
The description states "There are 12 children in the class:", but the test suite has a test that passes a custom students list to the class. Possible the description should be updated to be in line with the test suite?

**Comment by behrtam** [comment]
This is not coming up for the first time: https://github.com/exercism/python/issues/423

I see two ways of thinking about this. Either we want to be 100% consistent with the canonical test data, than we should just remove it or we mark it as to be skipped (like herehttps://github.com/exercism/python/blob/66b9e40115172daefcf3f6eb6d2e4fe0171ae60a/exercises/secret-handshake/secret_handshake_test.py#L50).

What do you think?

**Comment by swalladge** [comment]
Shouldn't the description be updated instead of the tests? Either way, people passing the problem should have passed all the unit tests so the description should simply reflect that now.

**Comment by cmccandless** [comment]
That is another option. Exercise descriptions are generated from the [canonical exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/kindergarten-garden/description.md), which applies to every track, not just this one.

However, there are mechanisms in place to add track specific info to a description ([`error-handling` does this](https://github.com/exercism/python/blob/master/exercises/error-handling/.meta)). I am not sure what all files `configlet` looks for in the `.meta` directory (if it exists), but inspecting the [source for `configlet`](https://github.com/exercism/configlet) or asking someone who is active over there should answer that.
