### ISSUE TITLE
sum-of-multiples: update tests to v1.5.0

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1580]
The [test suite](https://github.com/exercism/python/blob/master/exercises/sum-of-multiples/sum_of_multiples_test.py) for sum-of-multiples is out of date and needs updated to conform to the [latest canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/sum-of-multiples/canonical-data.json).

**Comment by GascaK** [comment]
I would like to work on this issue if no one has taken it on yet.

**Comment by cmccandless** [comment]
@GascaK that would be great!

You can always check the open pull requests to see if the issue you want to work on is already in progress.
