### ISSUE TITLE
dnd-character: implement exercise

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1593]
- [Exercise description](https://github.com/exercism/problem-specifications/blob/master/exercises/dnd-character/description.md)
- [Canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/dnd-character/canonical-data.json)

**Comment by GascaK** [comment]
I would like to take a crack at this if no one minds?

**Comment by GascaK** [comment]
There are two way's I came up with to implement this exercise:

1. Dictionary. Use 'character' dictionary with properties as keys and random 'ability' values
	* Character(): returns a structure with six random abilities and hitpoint score, in accordance with canonical-data.json.
	* Tests for keys and matching value easily
	* Forces the student to use a Dictionary to solve the exercise not in accordance with [Excercises](https://github.com/exercism/docs/tree/master/language-tracks/exercises)

2. Instance Variables. Use self.[ability] to assign values.
	* Allows student flexibility when solving excercise
	* Does not return character object in accordance with canonical-data.json.

Any input on this would be greatly appreciated.  The above commit utilizes the dictionary method as this, seems to me, is the more readable approach.

**Comment by cmccandless** [comment]
> Forces the student to use a Dictionary to solve the exercise not in accordance with Exercises

There are several exercises that require a certain data type as the return value. The idiomatic part is how that data type is populated. That said, I like the idea of properties for the ability tests.

I looked at your current implementation; go ahead and create a PR even if it is not finished so that feedback is easier to link to changes.
