### ISSUE TITLE
sgf-parsing: update tests to v1.1.0

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1620]
The [test suite](https://github.com/exercism/python/blob/master/exercises/sgf-parsing/sgf_parsing_test.py) for sgf-parsing is out of date and needs updated to conform to the [latest canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/sgf-parsing/canonical-data.json).

**Comment by elyashiv** [comment]
Hi. I couldn't find any tests that are outdated aside from the test in exercism/problem-specifications#1414

Can you be more specific?

**Comment by cmccandless** [comment]
It looks like there were no new test cases, but the expected results for one test case were changed: before, a node without properties was expected to not have a children field. This was incorrect, and [has been fixed.](https://github.com/exercism/problem-specifications/blob/cf44302c3a28503a2b5223273b7dd19e2d460bd4/exercises/sgf-parsing/canonical-data.json#L35-L45)

**Comment by elyashiv** [comment]
Will, currently the test does test it - it has a default of empty list.
