### ISSUE TITLE
Add additional linters to Python track.

### ISSUE THREAD

**Issue by AnAccountForReportingBugs** [exercism/python#1659]
I was thinking about the naming convention mix up in #1655 along with the fact that, in many ways, the examples and tests should be exemplars of Python programming.  That in mind, I wonder if the travis-requirements shouldn't include and enable `pep8-naming`, `flake8-bugbear` and run `isort --check-only` as well.  If you wanted to get really crazy, you could also do a `black --check` on the code, but that might be excessive due to the opinionated nature of that tool.

**Comment by AnAccountForReportingBugs** [comment]
Two I missed are `pylint` and `vulture`.  The former is similar to `flake8` and also maintained by PyCQA, but doesn't exactly overlap `flake8` in terms of what it checks.  The latter is used to find "dead" code in your project, which is basically unused or untested code.

**Comment by cmccandless** [comment]
- `pep8-naming`: probably a safe addition
- `flake8-bugbear`: maybe once we abandon Python2.7, but that's still a ways off
- `isort --check-only`: unnecessary for this project
- `black --check`: probably excessive
- `pylint`: enforces some extra-idiomatic styling, reducing a contributor's ability to leave their own fingerprint on their code
- `vulture`: this one was new to me, so I went ahead and ran it against the repo. The problem here is that every single solution stub includes "unused" code, so I don't think that will work here.

**Comment by cmccandless** [comment]
Conclusion: maybe add `pep8-naming`?

**Comment by cmccandless** [comment]
OK, just did some testing with `pep8-naming`. There's a problem there too: `unittest` doesn't follow this. While that in itself doesn't cause any violations, we use a wrapper method `assertRaisesWithMessage` for handling test cases that expect exceptions to be raised. The naming of this method matches the style of `unittest`, but violates `pep8-naming`. For consistency sake, this should be left as is. The following `.flake8` file allows this:

```
[flake8]
ignore-names = setUp,tearDown,setUpClass,tearDownClass,setUpTestData,assertRaisesWithMessage
```

**Comment by cmccandless** [comment]
#1662 functions as a preview of the changes to existing code that adding `pep8-naming` would require.

- If these changes are deemed acceptable, #1662 will be merged and this issue closed.
- If the changes are unacceptable, the Travis-CI check will remain as-is and this issue will be closed.

**Comment by cmccandless** [comment]
[From @naufraghi on Slack](https://exercism-team.slack.com/archives/CASLGCCSZ/p1548244843081700)
> `pep8-naming` may be a bit extreme, I find some names like `test_malformed_EDGE` that is referring to something locally named `EDGE` or `test_valid_with_X_check_digit` that refers to a real capital `X` below, may stay as they are. Ok for all the other. Sadly the stdlib itself is a bit confused, starting from the asserts :stuck_out_tongue:

**Comment by cmccandless** [comment]
I am in agreement with the above. This issue and #1662 will be closed.

**Comment by AnAccountForReportingBugs** [comment]
Sorry for leaving this for quite some time.  But for the sake of completeness I'd like to point out that using the conditional syntax in requirements.txt files allows pip to install different dependencies in different Python versions.

Additionally, I think that the issue with Vulture can be fixed by having a separate linting pass for the exercises in on Travis that uses a file similar to check-exercises.py that copies the exercise files and then lints them.  The reason is that more of the linters use the `ast` module to check the code, in addition to parsing the code directly and using string and `re` matches.
