### ISSUE TITLE
high-scores: update tests to v4.0.0

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1672]
The [test suite](https://github.com/exercism/python/blob/master/exercises/high-scores/high_scores_test.py) for high-scores is out of date and needs updated to conform to the [latest canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/high-scores/canonical-data.json).

**Comment by gabriel376** [comment]
I want to contribute

**Comment by cmccandless** [comment]
@gabriel376 that's great! I see you've commented on a few different issues; please create a separate branch and pull request for each issue you work on.

Once you've got a pull request submitted, I'll do a review on it and we'll go from there!

**Comment by gabriel376** [comment]
I will do that, thanks! =)
