### ISSUE TITLE
resistor-color: implement exercise

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1680]
[Exercise Description](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color/description.md)

[Canonical Data](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color/canonical-data.json)

**Comment by gabriel376** [comment]
I want to contribute

**Comment by gabriel376** [comment]
Hey, I am done implementing this exercise.

However, I need some guidance to add an entry to `config.json`:
```
{
    "slug": "resistor-color",
    "uuid": "?",
    "core": ?,
    "unlocked_by": "?",
    "difficulty": ?,
     "topics": [
         "?"
    ]
}
```

We need to define (or generate):
1. uuid
2. core
3. unlocked_by
4. difficulty
5. topics

**Comment by GascaK** [comment]
Use the [configlet](https://github.com/exercism/configlet) tool to generate uuid's and the README.md for you. 
As for core set to false, unlocked by usually is determined if this is logically harder than a similar test track which I'm not sure of. 
Difficulty I would set to how hard this answer was for you to figure out on a 1 - 10 scale.

**Comment by cmccandless** [comment]
Topics are taken from the [global topics list](https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt). Pick all that seem relevant, and we'll review them in your Pull Request.

For now, we'll leave unlocked_by as `null` (bonus exercise).
