### ISSUE TITLE
Remove references to Python 2.7 from README.md

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1704]
Please target the `drop-python2` branch in your pull request.

**Comment by joaoluizn** [comment]
I'm going to work over this one.

**Comment by joaoluizn** [comment]
I'm going to work on this now.

**Comment by Grociu** [comment]
Would this include dropping Python 2 references from all the individual `README.md` files in each of the exercises? Or is there some sort of script that constructs those? 
For reference, this is an example of an individual exercises readme Python 2.7 reference:

> ## Running the tests

To run the tests, run the appropriate command below ([why they are different](https://github.com/pytest-dev/pytest/issues/1629#issue-161422224)):

- Python 2.7: `py.test accumulate_test.py`
- Python 3.4+: `pytest accumulate_test.py`

Alternatively, you can tell Python to run the pytest module (allowing the same command to be used regardless of Python version):
`python -m pytest accumulate_test.py`

**Comment by cmccandless** [comment]
@Grociu Exercise READMEs are outside the scope of this issue.

[`configlet`](configlet) is used to generate exercise READMEs using the [track readme template] and exercise Description.md from the [problem specifications] repository.

[configlet]: https://github.com/exercism/configlet
[track readme template]: https://github.com/exercism/python/blob/master/config/exercise_readme.go.tmpl
[problem specifications]: https://github.com/exercism/problem-specifications

**Comment by joaoluizn** [comment]
@cmccandless should those be closed?

![image](https://user-images.githubusercontent.com/32312434/59552967-a9378380-8f64-11e9-91f8-c3a7cf0fa78d.png)

**Comment by cmccandless** [comment]
Yeah, I forgot automatic closing only works when merging with master. Thanks for pointing that out.
