### ISSUE TITLE
knapsack: implement exercise

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1736]
From [metadata]:
> Given a knapsack that can only carry a certain weight, determine which items to put in the knapsack in order to maximize their combined value.

[Canonical Data]

Contributor Checklist:
- [ ] Clone [exercism/problem-specifications] to local $`SPEC_DIRECTORY`
- [ ] Make new directory `$PYTHON_TRACK_DIRECTORY/exercises/knapsack`
- [ ] In `$PYTHON_TRACK_DIRECTORY`, run `bin/get-configlet`
- [ ] Add entry for `knapsack` in `$PYTHON_TRACK_DIRECTORY/config.json` (use `bin/configlet uuid` to generate a new UUID for entry)
- [ ] Run `$PYTHON_TRACK_DIRECTORY/bin/configlet generate -p $SPEC_DIRECTORY -O knapsack $PYTHON_TRACK_DIRECTORY` to generate the exercise README.md
- [ ] Implement test suite `$PYTHON_TRACK_DIRECTORY/exercises/knapsack/knapsack_test.py` (use existing exercise ~`coins`~ `change` as an example)
- [ ] Create a solution stub `$PYTHON_TRACK_DIRECTORY/exercises/knapsack/knapsack.py`
- [ ] Implement example solution `$PYTHON_TRACK_DIRECTORY/exercises/knapsack/example.py`. This solution may be tested using `$PYTHON_TRACK_DIRECTORY/test/check-exercises.py knapsack`

[metadata]: https://github.com/exercism/problem-specifications/blob/master/exercises/knapsack/metadata.yml
[Canonical Data]: https://github.com/exercism/problem-specifications/blob/master/exercises/knapsack/canonical-data.json
[exercism/problem-specifications]: https://github.com/exercism/problem-specifications

**Comment by omer-g** [comment]
Hello, I'd be happy to try and work on this.

**Comment by omer-g** [comment]
Hello, in the `config.json` entry, should a new UUID be generated (if so how?) ? Or is there an existing UUID for all knapsack exercises in all tracks? What should the difficulty be? Thanks

**Comment by cmccandless** [comment]
The UUID must be unique for each implementation of the exercise (i.e. this track's `knapsack` `uuid` will not be the same as another track's).

To generate this, use `configlet uuid`

**Comment by omer-g** [comment]
Thanks! Could I manually get it from the `configlet` repository and extract it in `/bin/` (I have no bash on this system at the moment).

**Comment by omer-g** [comment]
What parameters would you suggest for the stub function? I was thinking it may be the clearest to pass a list of `weights` and a list of `values` (albeit it may be arguably more idiomatic to pass a list of tuples).

**Comment by cmccandless** [comment]
I think a list of tuples would be best; it better represents that the weights and values are tied together.

**Comment by AnAccountForReportingBugs** [comment]
When I wrote my implementation, I used a list of dictionaries.  I tend to favor mappings for various reasons.  In addition, they are an allowed json type, so it makes automatic test generation easier.

**Comment by cmccandless** [comment]
> When I wrote my implementation, I used a list of dictionaries. I tend to favor mappings for various reasons.

As in `{"weight": 2, "value": 3}`? That is fine by me.

> In addition, they are an allowed json type, so it makes automatic test generation easier.

Nested lists are allowed in JSON; they just have to be homogeneous. That said, I think the dict approach is clearer.

> Also, another note from the bug text, but I don't think coins is an exercise in this track. Perhaps you meant change?

Yes, my mistake. I updated the issue description.
