### ISSUE TITLE
SGF-Parsing Readme

### ISSUE THREAD

**Issue by GKJCJG** [exercism/python#1748]
The Readme / Problem Description contains the following text:

An SGF file may look like this:

(;FF[4]C[root]SZ[19];B[aa];W[ab])

This is a tree with three nodes:

    The top level node has **two properties**: FF[4] (key = "FF", value = "4") and C[root](key = "C", value = "root"). (FF indicates the version of SGF and C is a comment.)
        The top level node has a single child which has a single property: B[aa]. (Black plays on the point encoded as "aa", which is the 1-1 point (which is a stupid place to play)).
            The B[aa] node has a single child which has a single property: W[ab].

In fact it has three properties: FF, C, and SZ. I will submit a fix once I have an issue number to refer to.

**Comment by cmccandless** [comment]
Great catch! And I see that you've created a PR as well, that's good.

However, for changes to exercise README files, please take a look at [this guide](https://github.com/exercism/docs/blob/master/language-tracks/exercises/anatomy/readmes.md). It explains the generation process for exercise READMEs within a track repository. If your suggested changes affect generated content, the correct action would be to open a PR over at exercism/problem-specifications.

**Comment by GKJCJG** [comment]
Thanks, I'll have a look and try to address it over on that side!

**Comment by GKJCJG** [comment]
It looks like the version in the description repository has already been fixed. I'll leave it to someone with more expertise in readme generation to propagate those changes to this repository.

**Comment by cmccandless** [comment]
@GKJCJG  Done!
