### ISSUE TITLE
anagram: tests should not require specific order for returned list

### ISSUE THREAD

**Issue by roadfoodr** [exercism/python#1826]
The `anagram` problem description does not specify a requirement that the elements of the returned sublist be in any particular order.  However, tests in the suite check against a particular ordered list (instead of checking that all the elements of the list are present).

Motivation: in my solution, I wanted to return a list of unique anagrams (although the problem description does not require this.)  I included a call to `set()` in the process, which changed the order of elements.

If there is interest in relaxing this requirement in the test suite, I will be happy to attempt a pull request.

**Comment by cmccandless** [comment]
@ydrecords Feel free to submit a PR. For testing purposes, please check your changes to the test suite against both your solution and the example solution as-is to verify that no bugs are introduced.

**Comment by roadfoodr** [comment]
Thank you.  I believe the most straightforward implementation would be to use `assertCountEqual()`.  However, this was first introduced in Python 3.2.  Does the test suite need to be compatible with Python 2.7?

**Comment by cmccandless** [comment]
Closed in #1828
