### ISSUE TITLE
track-anatomy: re-order core exercises

### ISSUE THREAD

**Issue by yawpitch** [exercism/python#1858]
Per Track Anatomy Round 2 we need to slightly re-order the Core Level 1 exercises. The significant change is to move `raindrops` into position _after_ `two-fer` and _before_ `high-scores`, however there will need to be some updates to the exercises currently unlocked by each.

**Comment by cmccandless** [comment]
Added `enhancement` label so stalebot will leave this issue alone.

**Comment by yawpitch** [comment]
Closed by #1861.
