### ISSUE TITLE
raindrops: update example to better fit Track Anatomy Level 1 status

### ISSUE THREAD

**Issue by yawpitch** [exercism/python#1859]
As part of Track Anatomy the `raindrops` exercise is being positioned to introduce conditionals (and the bool) _before_ `high-scores` introduces the `list` ... the example.py (and the mentor notes) should foreground that approach rather than the list comprehension syntax currently present.

**Comment by cmccandless** [comment]
If changes to the mentor notes are required, I recommend creating an issue for that in exercism/website-copy.

**Comment by yawpitch** [comment]
> If changes to the mentor notes are required, I recommend creating an issue for that in exercism/website-copy.

Issue created at https://github.com/exercism/website-copy/issues/1186.
