### ISSUE TITLE
raindrops: update "reasonable solutions"

### ISSUE THREAD

**Issue by yawpitch** [exercism/python#1860]
This discussion should limit the changes made to resolve #1859 but also in the website_copy repo.

Currently the example.py and the mentor notes have different solutions; they're not far off, but they take broadly different approaches.

For instance, this is the example.py approach:

```python
DROPS = ((3, 'Pling'), (5, 'Plang'), (7, 'Plong'))

def convert(number):
    return "".join(sound for factor, sound
                   in DROPS if number % factor == 0) or str(number)
```

While this is the "Recommended Solution" in the Mentor Notes:

```python
def raindrops(val: int) -> str:

    sound_map = [
        (3, 'Pling'),
        (5, 'Plang'),
        (7, 'Plong'),
        ]

    lst = [sound for factor, sound in sound_map if not (val % factor)]

    if not lst:
        result = str(val)
    else:
        result = ''.join(lst)

    return result
```

The first uses a _generator comprehension_, the second a _list comprehension_, and both require modelling the various factors and their appropriate sounds into a separate data structure.

I propose for purposes of the Track Anatomy position of this exercise to limit it to the "linear" version mentioned in the Mentor Notes:

```python
def raindrops(number): 
    result = ''
    if number % 3 == 0:
      result += 'Pling'
    if number % 5 == 0:
      result += 'Plang'
    if number % 7 == 0:
      result += 'Plong'
    return result or str(number)
```

It's slightly repetitive, but it introduces conditionals and requires no more complex data type than the **str** and the **int**, which makes it well positioned for a very early position in the Core Level 1 exercises.

Any thoughts or debate?

**Comment by cmccandless** [comment]
I agree that with the exercise's new position in the track, the recommended solution should be simplified. I do think the mentor notes can still include the comprehension form as an "advanced" or "extra-credit" solution, if students are looking for a bigger challenge.

**Comment by yawpitch** [comment]
> I agree that with the exercise's new position in the track, the recommended solution should be simplified. I do think the mentor notes can still include the comprehension form as an "advanced" or "extra-credit" solution, if students are looking for a bigger challenge.

Agreed, I'd really just be changing the ordering in which they're presented, foregrounding the "simpler" version as at least the first "Recommended Solutions".

**Comment by yawpitch** [comment]
Tracking issue for the website_copy repo: https://github.com/exercism/website-copy/issues/1186 , but it'd be helpful to have any discussion of the new "reasonable solution" here.

**Comment by yawpitch** [comment]
Between exercism/website-copy#1206, exercism/problem-specifications#1565, and #1879 this has been closed.
