### ISSUE TITLE
word-count: update tests to v1.4.0

### ISSUE THREAD

**Issue by yawpitch** [exercism/python#1876]
[Canonical data updated](https://github.com/exercism/problem-specifications/commit/055a260854943e612ce4d828a6dc4ec88b4682b5#diff-73c45d8adb070a54a82a7a9f2d4e1398) to add a test for substrings from the beginning of the sentence.

**Comment by guygastineau** [comment]
I'm a maintainer over at the bash track, but I started the python track, and I figured I'd come do some good deeds, so I should have something up later today.
