### ISSUE TITLE
raindrops: update description

### ISSUE THREAD

**Issue by yawpitch** [exercism/python#1878]
With its move to a new position `raindrops` needs an updated README.md file that better explains what's involved in solving the exericse.

**Comment by cmccandless** [comment]
The easiest way to add track-specific content to exercise READMEs within the current architecture is via a .meta/HINTS.md file.

**Comment by yawpitch** [comment]
How does that work if we're going to essentially rewrite the description given in the canonical description.md?

Or should I be proposing the changes in #1861 to the canonical file?

**Comment by cmccandless** [comment]
Some discussion took place offline, but the conclusion was that changes should be proposed to problem-specifications DESCRIPTION.md.
