### ISSUE TITLE
resistor-color-duo: update tests to v2.1.0

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1913]
The [test suite](https://github.com/exercism/python/blob/master/exercises/resistor-color-duo/resistor_color_duo_test.py) for resistor-color-duo is out of date and needs updated to conform to the [latest canonical data](https://github.com/exercism/problem-specifications/blob/master/exercises/resistor-color-duo/canonical-data.json).

**Comment by alirezaghey** [comment]
Addressed in PR #1918
