### ISSUE TITLE
binary-search-tree: add test template

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1931]
## Task
Create a test template file for `binary-search-tree`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `binary-search-tree-add-test-template`
    - Run: `git checkout -b binary-search-tree-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/binary-search-tree/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py binary-search-tree`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by aaditkamat** [comment]
Hi @cmccandless, do we need to add a macro that recursively generates TreeNodes like for this case? :
https://github.com/exercism/python/blob/7a42fb71e2eaf65c69f44d519c79e448aae3816c/exercises/binary-search-tree/binary_search_tree_test.py#L28-L40

**Comment by cmccandless** [comment]
Template macros may be defined within the same template that uses them. Also, if additional Python code is needed for generation, there is a way to define exercise-specific plugins to the generator. I have not yet had time to document this feature. I will look for an exercise that does this for an example.

**Comment by cmccandless** [comment]
See this example of exercise generator plugin: #2106

**Comment by tsamoglou** [comment]
Is this still open? if I want to give a solution first i must make a pull request with [WIP}??
Please help me , I am first time contributing

**Comment by cmccandless** [comment]
@tsamoglou yes, this is still open.

I recommend looking through the [Contributing Guide](https://github.com/exercism/python/blob/master/CONTRIBUTING.md). If you have further questions, please feel free to ask them here.

**Comment by cmccandless** [comment]
Closed in #2157
