### ISSUE TITLE
complex-numbers: add test template

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1937]
## Task
Create a test template file for `complex-numbers`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `complex-numbers-add-test-template`
    - Run: `git checkout -b complex-numbers-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/complex-numbers/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py complex-numbers`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by mbbroberg** [comment]
I'd like to give this one a try 👍

**Comment by mbbroberg** [comment]
Hey @cmccandless, running bin/generate_tests.py complex-numbers results in an error: 

```
$ bin/generate_tests.py -v complex-numbers
INFO:generator:complex-numbers: attempting render
DEBUG:generator:'dict object' has no attribute 'input'
ERROR:generator:complex-numbers: generation failed
```

Any tips?

**Comment by cmccandless** [comment]
@mbbroberg Go ahead and submit a pull request with what you have so far; that's the easiest way for maintainers to submit feedback.

**Comment by dvermd** [comment]
@mbbroberg, I made a PR for this one as yours got closed. However, if you'd like to some help on finishing this issue, I'll be glad to help.
