### ISSUE TITLE
[V2] diffie-hellman: add test template

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1944]
## Task
Create a test template file for `diffie-hellman`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `diffie-hellman-add-test-template`
    - Run: `git checkout -b diffie-hellman-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/diffie-hellman/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py diffie-hellman`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by crsmi** [comment]
I'd like to take this one.

**Comment by denvaar** [comment]
Me too

**Comment by cmccandless** [comment]
@denvaar I'm not sure the issue really lends itself to two simultaneous contributors. If you and @crsmi wish to collaborate, that is between you, but he did claim the issue prior to you. If @crsmi is not open to collaboration on this issue, please feel free to claim another open issue.

**Comment by pyropy** [comment]
@cmccandless Is this stale issue or I could take it?

**Comment by cmccandless** [comment]
@pyropy 
> Is this stale issue
Yes
> or I could take it?
Also yes. Contributors always welcome!

**Comment by BethanyG** [comment]
Missed that this was fixed and merged.  Closing.
