### ISSUE TITLE
dominoes: add test template

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1946]
## Task
Create a test template file for `dominoes`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `dominoes-add-test-template`
    - Run: `git checkout -b dominoes-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/dominoes/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py dominoes`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by mbbroberg** [comment]
I ran this one to give it a try and I'm receiving an error after running `bin/generate_tests.py dominoes`:

```
error: cannot format /var/folders/5l/c1y1gcw97szdywgf9rk1100m0000gn/T/tmpwiaj8rye: Cannot parse: 9:16:         value =
Traceback (most recent call last):
  File "bin/generate_tests.py", line 257, in <module>
    generate(**opts.__dict__)
  File "bin/generate_tests.py", line 217, in generate
    if not generate_exercise(env, spec_path, exercise, check):
  File "bin/generate_tests.py", line 169, in generate_exercise
    format_file(tmp.name)
  File "bin/generate_tests.py", line 132, in format_file
    check_call(['black', '-q', path])
  File "/Users/mbbroberg/.pyenv/versions/3.7.3/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['black', '-q', '/var/folders/5l/c1y1gcw97szdywgf9rk1100m0000gn/T/tmpwiaj8rye']' returned non-zero exit status 123.
```

Note that the temporary file `/var/folders/5l/c1y1gcw97szdywgf9rk1100m0000gn/T/tmpwiaj8rye` contains what looks like the target tests up to main:

```
import unittest

from dominoes import (can_chain,)

# Tests adapted from `problem-specifications//canonical-data.json` @ v2.1.0

class DominoesTest(unittest.TestCase):
    def test_empty_input_empty_output(self):
        value =
        expected = True
        self.assertEqual(canChain(value), expected)

    def test_singleton_input_singleton_output(self):
        value =
        expected = True
        self.assertEqual(canChain(value), expected)

    def test_singleton_that_can_t_be_chained(self):
        value =
        expected = False
        self.assertEqual(canChain(value), expected)

    def test_three_elements(self):
        value =
        expected = True
        self.assertEqual(canChain(value), expected)

    def test_can_reverse_dominoes(self):
        value =
        expected = True
        self.assertEqual(canChain(value), expected)

    def test_can_t_be_chained(self):
        value =
        expected = False
        self.assertEqual(canChain(value), expected)

    def test_disconnected_simple(self):
        value =
        expected = False
        self.assertEqual(canChain(value), expected)

    def test_disconnected_double_loop(self):
        value =
        expected = False
        self.assertEqual(canChain(value), expected)

    def test_disconnected_single_isolated(self):
        value =
        expected = False
        self.assertEqual(canChain(value), expected)

    def test_need_backtrack(self):
        value =
        expected = True
        self.assertEqual(canChain(value), expected)

    def test_separate_loops(self):
        value =
        expected = True
        self.assertEqual(canChain(value), expected)

    def test_nine_elements(self):
        value =
        expected = True
        self.assertEqual(canChain(value), expected)




if __name__ == '__main__':
```

**Comment by cmccandless** [comment]
It's complaining because the lines `value =` are not valid Python. There is an error in your template. Please create a PR with what you have so far, as this is the best way to receive specific feedback.

**Comment by dvermd** [comment]
Sorry about the PR, I did not mean to take "assignment" of this issue instead of @mbbroberg. 
I3wm + too narrow tile => Github doesn't have enough width in the browser, it does not show how many comments there are on an issue. I didn't realize someone was already working on this issue.

@mbbroberg, keep on your work on this one if you feel like to, I'd prefer you manage to complete it and get my PR rejected than you give up on this one because of me.

**Comment by mbbroberg** [comment]
It's okay @dvermd, I was stuck on this and lost track. Tracking your PR will be helpful to dive in. It's all about improving the project 😄
