### ISSUE TITLE
phone-number: add test template

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1966]
## Task
Create a test template file for `phone-number`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `phone-number-add-test-template`
    - Run: `git checkout -b phone-number-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/phone-number/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py phone-number`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by srahnama** [comment]
hi, bin/generate_tests.py phone-number runing without error but there is no change in test file!

**Comment by cmccandless** [comment]
Run `bin/generate_tests.py -v phone-number` please.

**Comment by srahnama** [comment]
output is :
INFO:generator:phone-number: attempting render
DEBUG:generator:[Errno 2] No such file or directory: 'black': 'black'
INFO:generator:phone-number: no canonical data found; skipping

**Comment by srahnama** [comment]
here #2022 same problem!

**Comment by cmccandless** [comment]
Run `python3.7 -m pip install -r requirements-generator.txt`, then try generator again.

**Comment by srahnama** [comment]
It's worked finally, ty.
but  I have new problem 
output is:
```
INFO:generator:phone-number: attempting render
phone-number generated at exercises/phone-number/phone_number_test.py
```

and I `print(rendered)` in `generate_tests.py` and looks good but the `phone_number_test.py` **not changed**

**Comment by cmccandless** [comment]
What operating system are you using?
- If Windows, is the test file open in another application?
- If macOS/Linux, check if you have correct file permissions

**Comment by srahnama** [comment]
I'm using Ubuntu, I used _`sudo`_ but nothing changed.

**Comment by cmccandless** [comment]
Can you try `bin/generate_tests.py -v --check phone-number`?

**Comment by srahnama** [comment]
yes. just:
`INFO:generator:phone-number: attempting render
`

**Comment by cmccandless** [comment]
Can you please run `tree . > python-tree.txt` from the repository root directory, and paste the contents of `python-tree.txt` in a Gist?

**Comment by srahnama** [comment]
https://gist.github.com/srahnama/591f7ebcf64e869504abc024dba8502e

**Comment by cmccandless** [comment]
Ah, shoot. My apologies: please do the same with `tree -a`

**Comment by srahnama** [comment]
gist updated,
now I run 
`sudo  bin/generate_tests.py -v --check  phone-number`

and output is: 

```
INFO:generator:phone-number: attempting render
ERROR:generator:phone-number: check failed; tests must be regenerated with bin/generate_tests.py


```

**Comment by srahnama** [comment]
```
Traceback (most recent call last):
  File "/usr/local/bin/black", line 6, in <module>
    from black import patched_main
  File "/usr/local/lib/python3.7/dist-packages/black.py", line 40, in <module>
    from attr import dataclass, evolve, Factory
ModuleNotFoundError: No module named 'attr'
Traceback (most recent call last):
  File "bin/generate_tests.py", line 242, in <module>
    generate(**opts.__dict__)
  File "bin/generate_tests.py", line 202, in generate
    if not generate_exercise(env, spec_path, exercise, check):
  File "bin/generate_tests.py", line 163, in generate_exercise
    format_file(tmp.name)
  File "bin/generate_tests.py", line 127, in format_file
    check_call(['black', '-q', path])
  File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['black', '-q', '/tmp/tmp73rqibwv']' returned non-zero exit status 1.

```
