### ISSUE TITLE
robot-simulator: add test template

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1980]
## Task
Create a test template file for `robot-simulator`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `robot-simulator-add-test-template`
    - Run: `git checkout -b robot-simulator-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/robot-simulator/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py robot-simulator`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by GKotfis** [comment]
I'd like to take this one. It'll be my first attempt to prepare python template but at least I have some [experience in C# in that area](https://github.com/exercism/csharp/pulls?utf8=%E2%9C%93&q=is%3Apr+author%3Agkotfis+) :)

**Comment by yawpitch** [comment]
Let us know if you have any issues.

**Comment by GKotfis** [comment]
Before I prepare template maybe it's good to rename first 'bearing' to 'direction'? It will be more consistent with canonical data. I've made similar things [here](https://github.com/exercism/csharp/pull/521/files)

**Comment by yawpitch** [comment]
It's perfectly fine to do that rename, however you'll have to update the `example.py` and the `robot_simulator.py` slug file to match.

**Comment by cmccandless** [comment]
Closed in #2056
