### ISSUE TITLE
sublist: add test template

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#1995]
## Task
Create a test template file for `sublist`

### Details
1. If this is your first time contributing to this repository, welcome!
    - Contributing to a repository on GitHub requires a [fork](https://help.github.com/en/articles/fork-a-repo)
1. Create a branch on your local repository called `sublist-add-test-template`
    - Run: `git checkout -b sublist-add-test-template`
1. Clone problem-specifications repository; this is used to populate the template
    - Run: `git clone https://github.com/exercism/problem-specifications ../problem-specifications`
1. Create `exercises/sublist/.meta/template.j2`
    - See [Generator Documentation] for more information
1. Generate test file from new template
    - Run: `bin/generate_tests.py sublist`

At this point, if the generator fails, or you are otherwise stuck,
please feel free to reach out! It is perfectly acceptable to submit
an incomplete PR in order to get feedback or assistance.

### Resources
- [Contributing Guide]
- [Generator Documentation]
- [Closing issues using keywords]

[Contributing Guide]: https://github.com/exercism/python/blob/master/docs/CONTRIBUTING.md
[Generator Documentation]: https://github.com/exercism/python/blob/master/docs/GENERATOR.md
[Closing issues using keywords]: https://help.github.com/en/articles/closing-issues-using-keywords

**Comment by dvermd** [comment]
I'll give a shot at this one

**Comment by dvermd** [comment]
Some feedback on the implementation:
- I use a dict to map expected values to sublist constants
- There are additional tests for this exercise. These go to a `additional_tests.json` file in the `.meta` directory along with some code to `template.j2` based on `word-count`. 
- The test `test_unique_return_values` doesn't call `sublist`. Any hint on how to declare it besides hardcoding it ?

**Comment by cmccandless** [comment]
> I use a dict to map expected values to sublist constants

I have no comment on this until I see it for myself

> There are additional tests for this exercise. These go to a additional_tests.json file in the .meta directory along with some code to template.j2 based on word-count.

You've got it!

> The test test_unique_return_values doesn't call sublist. Any hint on how to declare it besides hardcoding it ?

Might just need to hard-code it.

**Comment by dvermd** [comment]
To generalize even more test creation, would/did you consider moving most of the `template.j2` code (loop, header, additional, footer) to `generator_macros.j2` and only define a macro `test_case` in `template.j2` like the one of `word-count` ? 
A new file could be added for hard-coded test in the `.meta` directory if needed.

**Comment by cmccandless** [comment]
@dvermd I'm open to the suggestion. If someone submitted a PR with such a change so I could test it against several existing template to make sure it is general enough to be used globally.
