### ISSUE TITLE
Generated tests reference a wrong path for canonical-data.json

### ISSUE THREAD

**Issue by dvermd** [exercism/python#2011]
The tests generated with template.j2 contains the comment
`# Tests adapted from problem-specifications//canonical-data.json @ vx.y.z`

The path should contain the exercise name.

I have a fix for that one

**Comment by cmccandless** [comment]
This is intentional to keep the comment consistent and short. Technically, the full path is:
`problem-specifications/exercises/<exercise>/canonical-data.json`

But for the longest exercise name (parallel-letter-frequency), this is incredibly long, so we truncate the path for readability.

**Comment by dvermd** [comment]
Ok, maybe we can add some `...` between the `//`

**Comment by cmccandless** [comment]
I'd prefer to wait until all/most exercises have a template to change this line. There are tools that depend on the format of this line, so every exercise and the dependent tools need to be updated at the same time.
