### ISSUE TITLE
Template generation does not work in Windows

### ISSUE THREAD

**Issue by crsmi** [exercism/python#2026]
When running `bin/generate_tests.py -v [test-name]` in a Windows environment an error is thrown.

```
DEBUG:generator:zebra-puzzle\.meta\template.j2
INFO:generator:zebra-puzzle: no template found; skipping
```

This is because the Jinja environment/loader expects forward slashes instead of backslashes.

I think this can be easily fixed by adding `import posixpath` and using `posixpath.join` instead of `os.path.join` for creating the template string.

**Comment by cmccandless** [comment]
> I think this can be easily fixed by adding import posixpath and using posixpath.join instead of os.path.join for creating the template string.

Sounds like another PR in the works! Try it, test it, push it!

**Comment by crsmi** [comment]
Yeah, I found this out while working on #2004. The `posixpath` fix worked for me.

In the future, should I open an issue if I can easily have a pull request ready (for documentation purposes), or should I just create the pull request?

**Comment by cmccandless** [comment]
You can just create the pull request, but it would be nice if any information that would've been in the issue is also included in the PR (screenshots of errors, etc).

**Comment by crsmi** [comment]
Cool, I'll make sure to do that in the future. Thanks for the feedback!
