### ISSUE TITLE
accumulate: update to more closely emulate Python 3 `map` builtin

### ISSUE THREAD

**Issue by harshraj22** [exercism/python#2068]
[README.md](https://github.com/harshraj22/python/tree/master/exercises/accumulate) in accumulate mentions about a given operation being performed on each element of given collection. But internally, it checks for test cases involving only lists. I was wondering if this implementation is possible for others as well, i.e. our collection can be set,tuple,dict etc. The collection type is to be decided and the performed actions and returned. Is such implementation possible ?

**Comment by harshraj22** [comment]
Maybe the test case can be modified to involve more types. Here is a solution that I could come up with :
```python3
def accumulate(collection, operation):
    ans = None
    if isinstance(collection,list):
        ans = list(operation(i) for i in collection)
    elif(isinstance(collection,set)):
        ans = set(operation(i) for i in collection)
    elif(isinstance(collection,tuple)):
        ans = tuple(operation(i) for i in collection)
    return ans
```

Test : 
```python3
    def test_composition_tuple(self):
        inp = set([10, 17, 23])
        self.assertEqual(
            accumulate(
                accumulate(inp, lambda x: divmod(x, 7)),
                lambda x: 7 * x[0] + x[1]), inp)
```

**Comment by yawpitch** [comment]
IMHO given the scope and complexity of this exercise it’s probably sufficient to have this only work for lists and just add a hints.md to clarify that point; both the term “collection” and the `x => x * x` form are generic, and the hints.md is where we’d put additional Python-specific details.

That said if we did extend this exercise wouldn’t we need to either eliminate the **dict** from the notion of “collection” or decide up front if the operation is meant to apply to the key, the value, or a tuple of the key and value?

If we eliminate the **dict** for ambiguity and we’re only trying to handle iterable builtins with homogenous items, then there is a simpler solution:

```python
def accumulate(collection, operation):
    return type(collection)(operation(i) for i in collection)
```

 But even that won’t work for **str** or **bytes**... which are after both subclasses of **collections.abc.Collection**. Should those work?

Note also that there’s no indication that the collection coming out needs to be the same type as the collection coming in.

**Comment by harshraj22** [comment]
* Agreed with dict part.
* For collections part, I am still novice to python3, don't know much about that :sweat_smile: .

 But I think tuple and set can be extended here, as this would teach about type checking as well rather than just list comprehension/generators creation.

Any way, this is just a suggestion, Do whatever fells right. :smiley:

**Comment by yawpitch** [comment]
> But I think tuple and set can be extended here, as this would teach about type checking as well rather than just list comprehension/generators creation.

It's a reasonable selection, I'm just trying to determine if it "feels" right to have `accumulate` try to return the same type as what went in, as there's some connotations to that.

First, `accumulate` is basically just `map` with the arguments reversed ... `map` in Python 3 yields `operation(item)` for ever item in the collection -- it's a generator -- and so makes no determination on what sort of collection you should pack it back into ... it therefore works fine on _any_ iterable type. It doesn't even care if the **collection** even terminates.

If we were to emulate `map` then we'd treat a `dict` the same way and the **operation** would act on each key ... meaning that neither `map` nor `accumulate` are very _useful_ with `dict` types, but shouldn't reject them.

If we _want_ to encourage the use of type checking here then were probably should introduce **collections.abc**, but that's going to have to be done in the hints.md and will substantially increase the complexity of the solution. Type testing on primitive types (ie `isinstance(thing, set)` is generally _not_ a good habit to get into.

@cmccandless what do you think? My reading of the description has me thinking that having `accumulate(collection, operator)` produce the same result as `map(operator, collection)` in Python 2 (thus the same as `list(map(operator, collection))` in Python 3 is _fine_ but perhaps not _ideal_ ... I agree with @harshraj22 that expanding this might make the resulting solution more interesting, but I'd think we'd want to introduce good habits over bad at the same time.

**Comment by cmccandless** [comment]
It seems a little anti-Pythonic to require that a function returns *exactly* the same type as what went in. This type of behavior is what I'd expect from a staticly-typed language. I'm reminded of two particularly lines from [PEP 20]:

> Simple is better than complex.

Are we reading into the word "collection" too much?

> There should be one-- and preferably only one --obvious way to do it.

If the description seems to describe the `map` builtin, it seems odd to introduce behavior that runs counter to that.


[PEP 20]: https://www.python.org/dev/peps/pep-0020/

**Comment by yawpitch** [comment]
> If the description seems to describe the `map` builtin, it seems odd to introduce behavior that runs counter to that.

I agree, but should we have the student continue to emulate Python 2's `map` and return a **list** or have it mimic Python 3's and return an _iterator_?

I feel like as is `accumulate` doesn't reach much of anything.

**Comment by cmccandless** [comment]
> I agree, but should we have the student continue to emulate Python 2's map and return a list or have it mimic Python 3's and return an iterator?

Ah, I see the confusion now. Well, seeing how we're aiming to drop Python2 in the near future, it does seem wrong to emulate the `list`-return. I would vote towards emulating Python3 `map` then.

> I feel like as is accumulate doesn't reach much of anything.

It's an exercise that makes some sense in languages that don't have `map` or its equivalent, but loses a lot of meaning in many high-level languages.

**Comment by yawpitch** [comment]
Right, I'm going to rename this and set it aside till I've got a moment to think about it more.

**Comment by yawpitch** [comment]
With the rename, though, and post dropping Python 2 support we might want to eliminate this one, or add something more substantial to it.
