### ISSUE TITLE
Request for code review a very old solution

### ISSUE THREAD

**Issue by charles-wangkai** [exercism/python#2109]
My solution (https://exercism.io/my/solutions/dfaaa59d8f804d8aa94def6b24bc7fe7?iteration_idx=2) has been submitted for months and has not got a response.

Could any mentor please take a look? or Any staff could check if it's even not notified to mentors at all? Thanks!

**Comment by yawpitch** [comment]
I'll take a look ... not sure why but it doesn't appear to be in the priority queue at all ... it appears your version 1 was submitted before mentoring was added and your recent comment doesn't seem to have bumped it into the queue.
