### ISSUE TITLE
Error on kindergarden additional tests

### ISSUE THREAD

**Issue by photonn** [exercism/python#2133]
Hi,

There is an error in both last two unit tests.

In "test_students_are_unordered_first_student", you should change:

garden.plants("Patricia") --> garden.plants("Samantha")
and in test "test_students_are_unordered_last_student" you should change:

garden.plants("Xander") --> garden.plants("Roger")
Regards.

**Comment by photonn** [comment]
I could fix it myself as my first contribution to the project...

**Comment by yawpitch** [comment]
Thanks for pointing this out, but the tests are in fact correct. They're testing the fact that the students are supposed to be arranged in alphabetical order _before_ merging with the diagram ... Patricia is the alphabetically first member of the class and Xander the last, so they're getting the proper assignments of plants.

**Comment by photonn** [comment]
Sorry my bad. Maybe a better explanation is needed on the readme file as there is no mention that the students have to be sorted first (as they were already sorted in the original tests and only the name of the new unittests can give you a clue).  I suggest to add a:
├── .meta
│   └── hints.md

file to clarify this, or unorder the original students list so order them first is mandatory.

**Comment by yawpitch** [comment]
There's a section in the existing README.md that explains the constraint:

> Their teacher assigns cups to the children alphabetically by their names.

These tests are meant to confirm that the student read that part of the spec. Is that not clear enough?

**Comment by photonn** [comment]
Ops!, read it like four or five times and didn't pay attention to that. Really sorry for that and thanks for the clarification. I'll close the ticket.

Regards.

**Comment by yawpitch** [comment]
No problem, thanks for scrutinizing the tests.
