### ISSUE TITLE
forth: Duplicate test case definitions

### ISSUE THREAD

**Issue by dreig** [exercism/python#2148]
There are several test cases with the same name (ex: `test_errors_if_there_is_nothing_on_the_stack`) because they are being generated according to a template with data coming from the: [canonical-data.json](https://github.com/exercism/problem-specifications/blob/master/exercises/forth/canonical-data.json), and several cases have the same description.

Do you think it's better to change the template, or change the descriptions of the test cases in canonical-data.json to be more specific (ex: `test_errors_if_addition_and_there_is_nothing_on_the_stack`)?

**Comment by yawpitch** [comment]
Ahh, good catch. Damn, that's one I should never have merged, since it removed the individual class per major case.

We'll need to update the template, the construction of the canonical-data.json is correct.

**Comment by yawpitch** [comment]
Created #2149 to address this.
