### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Ber1337** [exercism/python#2151]
This exercise gives ImportError because test file tries to import PhoneNumber rather than what we are given, Phone.
https://exercism.io/my/solutions/2b93f3b6899547f48598a79efb75febe

the code in test file
```
from phone_number import PhoneNumber
```
the code in original file

```
class Phone:
    def __init__(self, phone_number):
        pass
```

Even though most people would figure it out, some might not.

**Comment by yawpitch** [comment]
@Ber1337 thanks for this, that’s a good catch! #2152 will fix.
