### ISSUE TITLE
New Exercise, Floyd Triangle

### ISSUE THREAD

**Issue by tsamoglou** [exercism/python#2154]
Hello, I want to add a new exercise, the Floyd triangle. 
Please inform me if you are interested in this 
https://en.wikipedia.org/wiki/Floyd%27s_triangle

**Comment by cmccandless** [comment]
Hi @tsamoglou!

We are beginning a reorganization of how we do exercises here at Exercism, so I am unsure of the procedure for adding new exercises (or even if we are currently accepting them at all).

@ErikSchierboom, should @tsamoglou create a PR over at exercism/problem-specifications as before, or are these things on hold for now?

**Comment by ErikSchierboom** [comment]
> @ErikSchierboom, should @tsamoglou create a PR over at exercism/problem-specifications as before, or are these things on hold for now?

The problem-specifications repo does not take any PR's for new exercises. That said, you _can_ create an issue for a new exercise, see e.g. [this issue](https://github.com/exercism/problem-specifications/issues/1608). And you can have track-specific exercise, i.e. ones that are not based on canonical data, if you so desire.

**Comment by tsamoglou** [comment]
Okey , Thanks you a lot for your Correspondence! @ErikSchierboom @cmccandless
