### ISSUE TITLE
Binary tree search problem with canonical data 

### ISSUE THREAD

**Issue by tsamoglou** [exercism/python#2158]
At [`/exercises/binary-search-tree/canonical_data.json`](https://github.com/exercism/problem-specifications/blob/master/exercises/binary-search-tree/canonical-data.json) at the case with the description "insert data at proper node" it has subcases with no reason and it makes difficult to make a template in python track. We should make the subcases unique cases. Please inform me if I can make a Pr for this

**Comment by cmccandless** [comment]
Thanks for the transfer @iHiD.

I'm going to close this as the issue is being addressed in #2157
