### ISSUE TITLE
Not able to download exercises content

### ISSUE THREAD

**Issue by MatteoRenoldi** [exercism/python#2168]
Hello everyone,
I just signed up to the exercism portal and it seems a very good initiative.
I am running Fedora and I have installed exercism from the command line. Then, since I am following the Python track, I wanted to download exercism first exercise, so I run the command that was linked at the page. However, it seems to me that nothing was downloaded. I have attached a screenshot here for further info.

![Screenshot from 2020-01-20 10-19-22](https://user-images.githubusercontent.com/33809495/72714450-03d63500-3b6f-11ea-8790-a4b27ea242d0.png)

I am running `exercism version 3.0.13` and the `hello-world.py` is something that I have created before downloading anything from your website.

Thanks in advance,
Matteo

**Comment by yawpitch** [comment]
Hi Matteo, that's definitely a bit odd. Assuming that you were in the exercism directory that the download was meant to happen to (ie `pwd` gives you back the same `$HOME/exercism` root as the download path), then my only guess is that there's some sort of network error ... can you do me a favour and run the download command with `-v` appended and give us back the verbose output?

**Comment by MatteoRenoldi** [comment]
Dear yawpitch,

Thank you for your message. I just realized that I was doing the download from another directory and not from `$HOME/exercism`. I then found all the files. Thanks for the support. Perhaps you could point out on the website that a specif folder with the related track will be created under the home directory, at least for Linux users

**Comment by cmccandless** [comment]
> Perhaps you could point out on the website that a specif folder with the related track will be created under the home directory

The directory path where the files were downloaded is printed in the output of the download command.

> at least for Linux users

This behavior is not Linux-specific.

**Comment by MatteoRenoldi** [comment]
Ok, thank you for clarifying. I was just confused because, in the initial screenshot that you see above, it seems that the files were downloaded in the folder in which I was in

**Comment by yawpitch** [comment]
@MatteoRenoldi this is part of the reason I've got termite configured to display my `pwd` at the top of the window (and i3 duplicating it on the status bar) -- it helps to avoid such confusion.

Closing this, as there's nothing we can action on.
