### ISSUE TITLE
Fix check-readmes.sh

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#2202]
- [ ] Not all exercises are run through the script
- [ ] Script does not fail on out-of-date README

See https://github.com/exercism/python/pull/2200/files#r421688872 for more info

*Edit: further context https://github.com/exercism/python/pull/2200#discussion_r421688872

**Comment by BethanyG** [comment]
Still open.

**Comment by BethanyG** [comment]
Closing as no longer relevant, given that configlet has been updated to sync these.
