### ISSUE TITLE
react test case that fails the example.

### ISSUE THREAD

**Issue by elyashiv** [exercism/python#2212]
Hi, the following test fails the react example:
```python
def test_callbacks_called_when_one_cell_changes(self):
    input1_ = InputCell(1)
    input2_ = InputCell(2)
    sum_cell = ComputeCell([input1_, input2_], lambda inputs: sum(inputs))

    self.assertEqual(sum_cell.value, 3)
    observer = []
    callback1 = self.callback_factory(observer)
    sum_cell.add_callback(callback1)
    input2_.value = 3
    self.assertEqual(input2_.value, 3)
    self.assertEqual(sum_cell.value, 4)
    self.assertEqual(observer[-1], [4])
```

Am I doing something wrong? Did I misunderstood something in the exercise?

**Comment by cmccandless** [comment]
The tests all pass on my machine. Can you post your `pytest` output?

**Comment by elyashiv** [comment]
Hi, this is a test I wrote myself...

I tested a ComputeCell with two inputs, and it seems like the observer doesn't catch the changes.

**Comment by cmccandless** [comment]
Your last line in the test should be:
```Python
    self.assertEqual(observer[-1], 4)
```

**Comment by elyashiv** [comment]
You are right, this is a problem. The thing is the test fails before that:
```
self = <react_test.ReactTest testMethod=test_callbacks_called_when_one_cell_changes>

    def test_callbacks_called_when_one_cell_changes(self):
        input1_ = InputCell(1)
        input2_ = InputCell(2)
        sum_cell = ComputeCell([input1_, input2_], lambda inputs: sum(inputs))
    
        self.assertEqual(sum_cell.value, 3)
        observer = []
        callback1 = self.callback_factory(observer)
        sum_cell.add_callback(callback1)
        input2_.value = 3
        self.assertEqual(input2_.value, 3)
>       self.assertEqual(sum_cell.value, 4)
E       AssertionError: 3 != 4

react_test.py:184: AssertionError
```

It seems like when one input cell changes, the compute cell doesn't change value. I think this is because the counter is changed just on one of the input cells.

**Comment by cmccandless** [comment]
My apologies, I never got back to this. I believe the issue may have something to do with these lines in `ComputeCell.compute`:

https://github.com/exercism/python/blob/5bd28aa7fc5cf33bee4ef381193b49e021a58b5b/exercises/react/example.py#L42-L44

If you would like to create a pull request to resolve the issue, please feel free. If not, I will try to resolve it when I have the time.
