### ISSUE TITLE
Two Fer

### ISSUE THREAD

**Issue by Yannotron** [exercism/python#2250]
Hi all, 

already running into difficulties in that exercise... Please lookup my code below.

def two_fer(name='default'):
    if name == 'default':
            print ('One for you, one for me')
    else : 
            print ('One for',name,', one for me.')

I get "two_fer_test.py:13: AssertionError" in all cases..

**Comment by cmccandless** [comment]
Hi @Yannotron 

The issue here is that your `two_fer` function does not `return` any value, which implicitly returns `None`. Consider the difference between functions `f` and `g` below:
```Python
def f(x):
  squared = x * x
  print(squared)

def g(x):
  squared = x * x
  return squared

assert g(2) == 4
assert f(2) == 4
```

If you run that whole block, assertion for `g` will pass, but the one for `f` will not.

**Comment by cmccandless** [comment]
For more info, please see https://stackoverflow.com/questions/750136/how-is-returning-the-output-of-a-function-different-from-printing-it

**Comment by Yannotron** [comment]
Thank you very much, that's now crystal clear.
However, I keep getting the same assertion error on each test after modifying my code to the following:

def two_fer(Name):
    if len(Name) == 0:
        return ('One for you, one for me')
    else : 
        return ('One for',Name,', one for me.')

**Comment by Yannotron** [comment]
Thank you for your guidance!

This is what made it:

def two_fer(Name="you"):

    if len(Name) == 0:
        return (f'One for {Name}, one for me')
    else : 
        return (f"One for {Name}, one for me.")

**Comment by Yannotron** [comment]
Thank you for your guidance!

This is what made it:

def two_fer(Name="you"):

    if len(Name) == 0:
        return (f'One for {Name}, one for me')
    else : 
        return (f"One for {Name}, one for me.")

**Comment by Yannotron** [comment]
Thank you for your guidance!

This is what made it:

def two_fer(Name="you"):

    if len(Name) == 0:
        return (f'One for {Name}, one for me')
    else : 
        return (f"One for {Name}, one for me.")
