### ISSUE TITLE
pythagorean-triplet: Remove unneeded empty functions? Add tests? Break this out into separate exercises?

### ISSUE THREAD

**Issue by morganpartee** [exercism/python#2280]
Hi!

Working through pythagorean-triple last night, I noticed the student solution file delivered includes two empty functions that are not used by the tests: `triplets_in_range` and `is_triplet`. The test file doesn't import (or test) these functions, and the [canonical json](https://github.com/exercism/problem-specifications/blob/master/exercises/pythagorean-triplet/canonical-data.json) only outlines tests for `triplets_with_sum`.

I haven't submitted a pull request before so I'm pretty stoked to help revise this exercise - But what is the fix? Do we add those other two functions as track-specific tests? Do we just remove them from the student solution file?

Looking forward to helping improve this track! It helped me a ton as I was getting my feet under me with Python. You all are awesome!

**Comment by morganpartee** [comment]
I browsed previous issues as well, it looks like this is a new issue, and the canonical-data json hasn't changed since the tests were implemented.

**Comment by cmccandless** [comment]
If those functions aren't being tested, then they shouldn't be in the stub.

> Do we add those other two functions as track-specific tests?

How the student implements `triplets_with_sum` is up to them; there's no requirement that they break it out into `triplets_in_range` and/or `is_triplet`. I'd rather not over-constrain them with such a requirement.

> Do we just remove them from the student solution file?

Yes

**Comment by morganpartee** [comment]
Thanks @cmccandless! Opened pr #2282 with the change made.

Thank you all for being my first pr!

**Comment by cmccandless** [comment]
Resolved in #2282
