### ISSUE TITLE
[v3] Configure online editor

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/python#2299]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

In Exercism v3, students can now choose to work on exercises directly from their browser, instead of having to download exercises to their local machine. The track-specific settings for the in-browser editor are defined in the top-level `"online_editor"` field in the track's `config.json` file. This field is defined as an object with two fields:

- `"indent_style"`: the indent style, either "space" or "tab".
- `"indent_size"`: the indent size, which is an integer (e.g. 4).

You can find a full description of these fields in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#metadata).

## Goal

The `"online_editor"` field should be updated to correspond to the track's best practices regarding indentation.

## Example

```json
"online_editor": {
  "indent_style": "space",
  "indent_size": 4
}
```

## Tracking

https://github.com/exercism/v3-launch/issues/2

**Comment by BethanyG** [comment]
The online editor was previously configured for Python, but linking the latest pull request to confirm it is done.

**Comment by ErikSchierboom** [comment]
@BethanyG I don't see the online editor being modified in that PR. It looks like my migration PR [added this field](https://github.com/exercism/python/commit/e5f5e0719534c5052e517a776f1c4478a9121212#diff-587cb980af76fdc7e52369fd0b9d926dff266976b6f8ac631e358fecc49ff8cf) to this repo. If so, it will have used the default settings (which might be correct for Python). My script could of course also have had a bug.

**Comment by BethanyG** [comment]
@ErikSchierboom  -- no -- those settings are correct.  Brain fart on my part.  Let me link the migration PR instead.

**Comment by ErikSchierboom** [comment]
Good! If the settings are correct, feel free to close this issue.
