### ISSUE TITLE
[v3] Build Test Runner

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/python#2304]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

In Exercism v3, one of the biggest changes is that we'll automatically check if a submitted solution passes all the tests.

We'll check this via a new, track-specific tool: the [Test Runner](https://github.com/exercism/v3-docs/tree/main/anatomy/track-tooling/test-runners). Each test runner is track-specific. When a new solution is submitted, we run the track's test runner, which outputs a JSON file that describes the test results.

The test runner must be able to run the tests suites of both [Concept Exercises](https://github.com/exercism/v3-docs/blob/main/product/concept-exercises.md) and [Practice Exercises](https://github.com/exercism/v3-docs/blob/main/product/practice-exercises.md). Depending on the test runner implementation, this could mean having to update the Practice Exercises to the format expected by the test runner.

## Goal

Build a test runner for your track according to [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/test-runners/interface.md).

If you are building a test runner from scratch, we have a [starting guide](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/test-runners/creating-from-scratch.md) and a [generic test runner](https://github.com/exercism/generic-test-runner/) that can be used as the base for the new test runner.

If a test runner has already been built for this track, please check if it works on both Concept Exercises _and_ Practice Exercises.

It can be very useful to check how [other tracks have implemented their test runner](https://github.com/search?q=org%3Aexercism+test-runner&type=repositories).

## Tracking

https://github.com/exercism/v3-launch/issues/4

**Comment by BethanyG** [comment]
Closing this as completed, although version 3 changes to the test runner are pending.  However, the current version 2 of the test runner is complete and running, so it is technically "good for launch".
