### ISSUE TITLE
[v3] Update status of track

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/python#2306]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

There are several new features in Exercism v3 for tracks to build. To selectively enable these features on the Exercism v3 website, each track must keep track of the status of the following features:

- [Concept Exercises](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/concept-exercises.md) have been built
- A [test runner](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/test-runners/README.md) has been implemented
- A [representer](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/representers/README.md) has been implemented
- An [analyzer](https://github.com/exercism/v3-docs/blob/main/anatomy/track-tooling/analyzers/README.md) has been implemented

The status of these features is specified in the top-level `"status"` field in the track's `config.json`, as specified in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#metadata).

## Goal

The `"status"` field in the `config.json` file should be updated to indicate the status of the features for this track. The list of features is defined in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#metadata).

## Example

```json
{
  "status": {
    "concept_exercises": true,
    "test_runner": true,
    "representer": false,
    "analyzer": false
  }
}
```

## Tracking

https://github.com/exercism/v3-launch/issues/12

**Comment by BethanyG** [comment]
Closing this as completed. `config.json` lists the runner, analyzer and representer as `True`.
