### ISSUE TITLE
Update status of Concept Exercises

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/python#2307]
_This issue is part of the migration to v3. You can read full details about the various changes [here](https://github.com/exercism/v3-launch/)._

Concept Exercises can have a status specified in their `"status"` field in their `config.json` entry, as specified in [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#concept-exercises). This status can be one of four values:

- `"wip"`: A work-in-progress exercise not ready for public consumption. Exercises with this tag will not be shown to students on the UI or be used for unlocking logic. They may appear for maintainers.
- `"beta"`: This signifies active exercises that are new and which we would like feedback on. We show a beta label on the site for these exercise, with a Call To Action of "Please give us feedback."
- `"active"`: The normal state of active exercises
- `"deprecated"`: Exercises that are no longer shown to students who have not started them (not usable at this stage).

The `"status"` key can also be omitted, which is the equivalent of setting it to `"active"`.

## Goal

The `"status"` field of Concept Exercises in the `config.json` file should be updated to reflect the status of the Concept Exercises. See [the spec](https://github.com/exercism/v3-docs/blob/main/anatomy/tracks/config-json.md#concept-exercises) for more information.

If your track doesn't have any Concept Exercises, this issue can be closed.

## Example: removed wip status 

```json
{
  "exercises": {
    "concept": [
      {
        "uuid": "93fbc7cf-3a7e-4450-ad22-e30129c36bb9",
        "slug": "cars-assemble",
        "name": "Cars, Assemble!",
        "concepts": ["if-statements", "numbers"],
        "prerequisites": ["basics"]
      },
      ...
    ]
  }
}
```

## Example: replaced wip status with active

```json
{
  "exercises": {
    "concept": [
      {
        "uuid": "93fbc7cf-3a7e-4450-ad22-e30129c36bb9",
        "slug": "cars-assemble",
        "name": "Cars, Assemble!",
        "concepts": ["if-statements", "numbers"],
        "prerequisites": ["basics"],
        "status": "active"
      },
      ...
    ]
  }
}
```

## Tracking

https://github.com/exercism/v3-launch/issues/14

**Comment by BethanyG** [comment]
#2319  Updates statuses to reflect current state as of 2/3/21.  
But we'll keep this issue open for a while as we hope to move more exercises from `WIP` to `beta` before launch.

**Comment by BethanyG** [comment]
Although we've done an initial pass on the status of these exercises we're keeping this issue open because we expect to move more of the exercises from `WIP` to `beta` as we get closer to launch.

**Comment by BethanyG** [comment]
Closing this.  Most of our exercises are now in beta, and we're hoping to move them fully live soonish.
