### ISSUE TITLE
[CI] Update tooling for v3

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#2310]
## Changed components

- Exercises are no longer in just one directory (exercises/). They are in either **`exercises/concept/`** or **`exercises/practice/`**
- Example solutions will now be under a `.meta/` directory:
   - **practice exercise** example files will move from the directory _itself_ (**`two-fer/example.py`**) to a **new** `.meta/` directory.  Optionally, files can be renamed to `proof.py`, `demo.py`, `exemplar.py`, or stay `example.py`.
   - **concept exercise** exemplars are currently located under `concept/<exercise-slug>/.meta/exemplar.py` (**e.g**`concept/currency-exchange/.meta/exemplar.py`), and will remain there.  
- config.json's `exercises` field is no longer an array of exercises. It is an object with two properties: `concept` and `practice`. These each have the same format as the old `exercises` property.
- Exercise READMEs **vary by exercise type.** 
   - **practice exercise** READMES follow the conventions listed [here](https://github.com/exercism/docs/blob/main/anatomy/tracks/practice-exercises.md#files)
   - **concept exercise** READMES follow the conventions listed [here](https://github.com/exercism/docs/blob/main/anatomy/tracks/concept-exercises.md#full-example)

## Scripts dependent on changes components:

- [x] bin/template_status.py
- [x] bin/generate_tests.py
- [x] test/check-exercises.py

## Obsolete scripts

The following scripts are no longer needed:
- [ ] bin/check-readmes.sh
- [x] bin/check-test-version.py (versions no longer used in problem-specifications)

## Ambiguity

@ErikSchierboom, we have these scripts. Neither are needed for CI, but which (if either) should be kept for contributors/maintainers who need to run the new v3 configlet locally

- [ ] bin/fetch-configlet
- [ ] bin/fetch-canonical_data_syncer

**Comment by cmccandless** [comment]
Additionally, it might be easier to maintain our CI workflows if we break out ci-workflow.yml into separate workflow files.

**Comment by BethanyG** [comment]
Holding open for a bit.

**Comment by BethanyG** [comment]
Closing this as no longer relevant given the changes made to configlet and other re-arranging.
