### ISSUE TITLE
[Improve Concept Exercise] : inventory-management (dicts)

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#2342]
This issue is for improvements & changes needed to the [`inventory-management`](https://github.com/exercism/python/tree/main/exercises/concept/inventory-management) concept exercise on the Python track.

## Goals
Improve the [Inventory-management (`dicts`) concept exercise](https://github.com/exercism/python/tree/main/exercises/concept/inventory-management) by adding the `dict.pop()` method & creation via `dict literal` to the tasks the student has to complete.  Make other improvement changes as noted below:  

- [ ] Edit `design.md` doc to add `dict.pop()` to the design
- [ ] Edit `Introduction.md` to add `dict.pop()` usage.
- [ ] Edit `instructions.md` to add new tasks:
        - creation of `dict` literals 
        - using `dict.pop()`
- [ ] Add appropriate hint as needed in `hints.md` for `dict.pop()` usage
- [ ] Edit `exemplar.py` to include new idiomatic solution for newly added tasks
- [ ] Edit `dicts_test.py` file to add new tests for `dict.pop()` task.
- [ ] Edit `dicts.py` stub file to add new tasks.
- [ ] Edit test file to explicitly list imported functions/methods by name instead of using `import *`
- [ ] Check/edit all markdown files to conform to the [Exercism Markdown Specifications](https://exercism.org/docs/building/markdown/markdown) 

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before diving into the implementation, please read up on the following documents:
- [Contributing to Exercism](https://exercism.org/contributing) |  [Help](https://exercism.org/docs/building/product)
- [What are those Weird Task Tags about?](https://exercism.org/docs/building/tasks)
- [Building Language Tracks: An Overview](https://exercism.org/docs/building/tracks) 
- [What are Concepts?](https://exercism.org/docs/building/tracks/concepts)
- [Concept Exercise Specifications](https://exercism.org/docs/building/product/concept-exercises)
- [Exercism Formatting and Style Guide](https://exercism.org/docs/building/markdown/style-guide)
- [Exercism Markdown Specification](https://exercism.org/docs/building/markdown/markdown)

**Comment by mukeshgurpude** [comment]
Is this task still unfinished?

**Comment by BethanyG** [comment]
Hi @mukeshgurpude 👋🏽    This task is indeed unfinished.  I was in the middle of it when we went to launch, so I have a half finished PR.  I'd love some help, if you'd like to join in?  Just let me know, and I can flag it as [claimed' for you.

**Comment by mukeshgurpude** [comment]
I would like to help on this task. I would start working on this task later in the day.
Could you please update the links about Markdown style guides in Issue description, they are giving me 404 now🤔.

**Comment by BethanyG** [comment]
The task is all yours!  And _**thank you**_ for taking it on!  🌟     

I am going to go ahead and PR what I have and flag it as a draft.  You should then be able to make commits to it.  Or not.  Your choice!  You can also start over from the top, if you prefer.  😄 

>Could you please update the links about Markdown style guides in Issue description, they are giving me 404 now🤔.

Yes.  Apologies!  All the links should now be updated to go to the nicely formatted website docs.  LMK if you have additional questions or issues.  I should be available until midnight pacific.

**Comment by BethanyG** [comment]
The draft PR is here: https://github.com/exercism/python/pull/2530

**Comment by mukeshgurpude** [comment]
Hello @BethanyG. Since there is already a pull request from your fork to the upstream, I thought of pushing changes to your fork only..
I've opened a pull request https://github.com/BethanyG/python/pull/15, but maybe you missed it by chance..

**Comment by BethanyG** [comment]
@mukeshgurpude  -- Oh no!  I **did* miss it!  😱   _so sorry_.  I will take a look right now.  Thanks!

**Comment by mukeshgurpude** [comment]
@BethanyG as related PR is merged, we should close this issue now.

**Comment by BethanyG** [comment]
@mukeshgurpude  -- thank you for the reminder!  😂    I have one too many things to do, and forgot this.
