### ISSUE TITLE
Fix Stale bot action AGAIN

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#2400]
The emoji in our labels still aren't referenced correctly in our stale.yml.

**Comment by BethanyG** [comment]
This stale bot action is going to be the death of me.  `Srsly.  🙄 `

**Comment by BethanyG** [comment]
Love it when the bot acts in its own self-interest and marks the stalebot bug stale.  🙄

**Comment by BethanyG** [comment]
@cmccandless  -- since I cause this problem, I will try and fix it soon.  Apologies for it falling through the cracks.  Assigning it to myself.

**Comment by BethanyG** [comment]
Bad stale-bot.  B A D.  😡

**Comment by BethanyG** [comment]
Fixed (_please oh please oh please_) in [2465](https://github.com/exercism/python/pull/2465)
