### ISSUE TITLE
sorry to bother but im dumb

### ISSUE THREAD

**Issue by dipap2112** [exercism/python#2401]
Hi all, I,m new to excersism and python. Nonetheless, i managed to solve Hello world. I see it works when 
i run it on IDLE so happy with that. My issue is the testing and submitting. I tried all i could think of but to no avail. Its either syntax error (even though I copy and paste) or other mess like file not found or directory...
I feel stupid but humble and I hope to get help to pass these first obstacle so that I can move forward and learn more. Any help is appreciated, step by step explanation would be best. I use Windows.

Thanks

**Comment by dipap2112** [comment]
Thanks for the nice words. I have followed every instruction on the site
and pasted commands in powershell and this is what i get
[image: image.png]
I think i managed to install the CLI correctly.
I searched for tutorials on YT by someone with my setup just showing step
by step, but so far when i only got errors back when i use those commands.
I am so stuck. Too old to take up coding maybe??

Have a nice one,
Diego

Il giorno gio 8 apr 2021 alle ore 21:04 BethanyG ***@***.***>
ha scritto:

**Comment by cmccandless** [comment]
@dipap2112 I'm afraid your images pasted into email responses don't render on GitHub, so we can't see your screenshot.

**Comment by BethanyG** [comment]
Hi Diego (@dipap2112),

I don't think you are "too old" to take up coding, but I do think that you need more interactive help.  Unfortunately, the image you pasted did not resolve, so I cannot see the error messages you are getting in your powershell window.   Could you repost it maybe?

Additionally -- is there any chance you could login to gitter -- either https://gitter.im/exercism/support or https://gitter.im/exercism/python, so we could help you closer to real-time?  I promise we don't bite, and with a smaller feedback loop, we may be able to resolve your issue and get you on your way.  Frustration is common in programming - but you don't have to bang your head all alone.  😄

**Comment by dipap2112** [comment]
Ok. I attached the picture.
I will get on Gitter for more help. I think it is my only chance.
Thanks again guys, I truly appreciate.

Diego

fre. 9. apr. 2021, 19:18 skrev BethanyG ***@***.***>:

**Comment by BethanyG** [comment]
@dipap2112  - just checking in to see if your issue was resolved & we can close this.  Please let us know.  Thanks!

**Comment by dipap2112** [comment]
yeah, well. I guess you can close the issue, I am on Gitter and looking for
help. I will manage eventually; in my own time frame I'm afraid.

Best regards
Diego

Il giorno mar 13 apr 2021 alle ore 22:40 BethanyG ***@***.***>
ha scritto:

**Comment by BethanyG** [comment]
Ok @dipap2112 - Let us know (_with another issue or by reopening this one_) if you need more help.
