### ISSUE TITLE
[Improve Concept Exercise] : Black Jack (comparisons) 

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#2428]
RE: https://github.com/exercism/python/pull/2420#pullrequestreview-659249249

Improvements are still needed before the `comparisons` Concept Exercise can graduate from `wip` to `active`. These improvements include (but are not limited to):
- [ ] Spelling/Grammar corrections
- [ ] Reference link checking
- [ ] Exemplar/test code cleanup

**Comment by BethanyG** [comment]
Improving this concept exercise will also address #2482, which has been temporarily fixed via [pull #2481](https://github.com/exercism/python/pull/2481) & removal of the exercise from the beta site.

**Comment by pranasziaukas** [comment]
Where is an exercise set as `wip` or `active`?
My best guess was `config.json` but doesn't look like it.

**Comment by BethanyG** [comment]
It is indeed `config.json` 😄   -- but it's the _track_ [`config.json`](https://github.com/exercism/python/blob/main/config.json).  Here's the entry for BlackJack.  Note that the `status` flag says 'wip`.  WIP exercises are not accessible on the site, but will (_eventually_) be viewable by maintainers. :

<img src="https://user-images.githubusercontent.com/5923094/133434214-23c8e61e-2e60-4522-9ec1-5183da2a83b7.png" width="500">
