### ISSUE TITLE
[Pretty-Leaflet] Rewrite Exercise to Omit the Use of Classes

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#2438]
The `Pretty-Leaflet` concept exercise (`string-formatting` concept) needs to be re-written to not require the creation of/ working with `classes` as part of its solution.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before diving into the implementation, please read up on the following documents:

- [Contributing to Exercism](https://exercism.org/contributing) |  [Help](https://exercism.org/docs/building/product)
- [What are those Weird Task Tags about?](https://exercism.org/docs/building/tasks)
- [Building Language Tracks: An Overview](https://exercism.org/docs/building/tracks) 
- [What are Concepts?](https://exercism.org/docs/building/tracks/concepts)
- [Concept Exercise Specifications](https://exercism.org/docs/building/product/concept-exercises)
- [Exercism Formatting and Style Guide](https://exercism.org/docs/building/markdown/style-guide)
- [Exercism Markdown Specification](https://exercism.org/docs/building/markdown/markdown)

-------

`Pretty-Leaflet`  was intended to appear "early" in the Python concept exercise tree and not require a student to know how to create and work with `classes` or with `higher-order functions`.  It should appear right after students learn the core basics like `strings`, `string-methods`, `loops`, and `lists`.  Requiring `classes` as a prerequisite means that students miss learning about `f-strings`, `str.format()`, and other options for strings that are pretty important early on, and are used (_or can be used_) in the exercises for `dicts`, `sets`, and `tuples`. 

Because a `concept exercise` can only use the techniques introduced in the exercise itself, or in its prerequisites, the reliance on a `class` for `pretty leaflet` needs to go. 

This can be an entire rewrite (_with new tasks or even a new story_), or just a rewrite of the stub, tests and the `examplar.py` code.  Contributors choice -- although, if the story/instructions/hints can be preserved, that would be ideal (and less work!).

[Pretty Leaflet Exercise Directory](https://github.com/exercism/python/tree/main/exercises/concept/pretty-leaflet)
[String-Formatting Concept Directory](https://github.com/exercism/python/tree/main/concepts/string-formatting)

From first glance, the following areas will need to be looked at or changed:

- [ ] exercise instructions
- [ ] exercise hints
- [ ] exercise `exemplar.py`
- [ ] exercise stub and test files

However, there may be additions or changes needed in the other files for the exercise or concept , so reviewing all the related docs might be a good idea.

**Comment by Git389-ma** [comment]
can you explain the issue 
clearly

**Comment by BethanyG** [comment]
👋🏽  @Git389-ma - As stated in the description, this issue is a _placeholder_, and needs additional detail, which I cannot fill in right now.  

But for details on what a concept exercise for V3 exercism is, and what the expected requirements are, please take  a look here:  [exercism concept exercises](https://github.com/exercism/docs/blob/main/building/tracks/concept-exercises.md).  More background and details for building exercism can be found here:  [Building Exercism Directory](https://github.com/exercism/docs/tree/main/building) The current iteration of the `pretty-leaflet` concept exercise can be found here:  [pretty-leaflet](https://github.com/exercism/python/tree/main/exercises/concept/pretty-leaflet).

Since the intended subject of the `pretty-leaflet` concept exercises is `string-formatting`, it feels like "too much" to require a student to also learn how to create `classes` in python in order to complete the exercise.  It should be sufficient to only have an understanding of `strings`, `string-methods`, `functions`, and `loops`.  Because the requirement is that concept exercises only use methods and techniques that are part of prerequisites, at minimum, the stub, exemplar, and test files for this exercise will need to be re-written.

When I have time, I will loop back and really detail what changes I'd expect.  If you are interested in working on this issue, I can prioritize doing that in the next few days.

**Comment by BethanyG** [comment]
For a list of other issues in this repo that have `[help wanted]` (_and a lot of detail on what is needed_), please see this list:  [Python: Help Wanted](https://github.com/exercism/python/issues?q=is%3Aissue+is%3Aopen+label%3A%22help+wanted%22)

**Comment by BethanyG** [comment]
Still active.

**Comment by BethanyG** [comment]
**Update: 9/9/2021**  This issue has been updated with details and is open for a contributor to pick up.  Please contact a maintainer (or ask in this issue) if you have any questions or issues.  Thanks!

**Comment by tigerBoss101** [comment]
Should `lists` be part of the exercise? I'm wondering because I only see `basics` and `strings` in the prerequisites.

**Comment by BethanyG** [comment]
@tigerBoss101  -- The `config.json` shows both `loops` and `lists` as prerequisites for `string-formatting`.  Where are you seeing that only `basics` and `strings` are prerequisites?

**Comment by tigerBoss101** [comment]
@BethanyG
I saw the `basic` and `strings` prerequisites in the design.md file.

**Comment by BethanyG** [comment]
@tigerBoss101   - a ha!  Well, I think whomever does this task should probably change that.  
Depending, of course on their re-write.  But the `config.json` that controls the tree on the site UI does have `loops` and `lists` in the prerequisites.

**Comment by BethanyG** [comment]
In the spirit of optimistic merging, I am going to close this issue, as it has largely been addressed.  Further rewrites are needed before this exercise can go live, but they will be detailed in a follow-on issue.
