### ISSUE TITLE
Tests wrong in book_store_test.py

### ISSUE THREAD

**Issue by marcuslxxii** [exercism/python#2458]
Hello. I'm facing as a student the latest Python track: book_store. But the test file is almost completely wrong (15 tests are incorrect and only two are correct)! If it is correct, then I didn't understand the exercise...

For example total([2, 2]) can not return 1600, but the correct result is 3040 (760*4)...

See my solutions and my test in https://exercism.io/my/solutions/9ca14381cf4a4fa788216516fd0d386e

**Comment by marcuslxxii** [comment]
Excuse me: I had only misinterpret the track! It's all OK.

**Comment by BethanyG** [comment]
Hi @marcuslxxii  👋🏽 !  As discussed in our Slack channel, the tests are correct as per the canonical data for the problem found here:  [Book Store Specifications](https://github.com/exercism/problem-specifications/blob/main/exercises/book-store/canonical-data.json).  But the examples and problem description could be clarified.  Would you mind opening an issue in `problem-specifications`, and describing your confusion and possibly recommending better wording??  That way, we can discuss improvements, and maybe avoid confusing future students?  😄 

_**Thanks so much!**_  I will go ahead and close this issue.
