### ISSUE TITLE
Prt.sckt.00

### ISSUE THREAD

**Issue by T4006** [exercism/python#2467]
.....

**Comment by iHiD** [comment]
Shall I block you from the org, or are you real?

**Comment by ryank01** [comment]
Hey I’m real, I just need to start working on issues and sending out PRs.

**Comment by SleeplessByte** [comment]
@ryank01 we should conduct a turing test.

What's Prt.sckt.00, and what's up with the mostly empty issue?

**Comment by ryank01** [comment]
port.socket.00 ? Also I have no clue about any empty issues. I’ve never
submitted issues before.

**Comment by SleeplessByte** [comment]
Did you respond to @iHiD because you're @T4006 or was it a random response to a question not meant for you?

**Comment by ryank01** [comment]
I’m not @T4006, I responded to the question asking if I should be blocked
because of suspicion of being a bot.

**Comment by iHiD** [comment]
OK. I suggest understanding how GitHub works before doing more things :)

**Comment by ryank01** [comment]
Hey guys I’m sorry about this, I’ve been in meetings all day and super
busy. I’m now looking at the issues on GitHub, I responded to that question
by mistake for some reason I thought the question was directed at me. I
made the assumption that the maintainers were looking at inactive
subscribers and purging them, and even if they were removing users I doubt
they would email each user and ask if they’re real. Sorry again it was a
stupid mistake!

**Comment by iHiD** [comment]
@ryank01 No worries - these things happen 🙂 

FWIW - I thought you and the original poster were the same poster and misread your reply, so sorry for that too!

Anyway, thanks for taking the time to reply - Hopefully see you on a different issue soon! 🙂

**Comment by ryank01** [comment]
Thanks to everyone for understanding, this will not happen again.
