### ISSUE TITLE
Branch in Python Learning Journey Won't Unlock

### ISSUE THREAD

**Issue by OpenWiseFound** [exercism/python#2482]
This is the map of the learning journey presented to students for python: 

![Screen Shot 2021-08-06 at 12 15 01 PM](https://user-images.githubusercontent.com/18388842/128541001-ecc21a33-ebec-454c-8927-4c1414c33410.png)

We've been working our way through learning exercises to check if they are appropriate for our kids and to help bug test them; however, we've hit a roadblock: 

![Screen Shot 2021-08-06 at 12 16 13 PM](https://user-images.githubusercontent.com/18388842/128541253-b70b03d1-4364-4b27-a135-c778247229a0.png)

The Conditional exercises won't unlock unless we complete the Basics exercise, which we have, and the Comparisons exercise, which doesn't exist anywhere on the map.  From the context, it's possible that the Bools exercise was meant here, but we've completed that too, and the Conditional exercise remains locked.

**Comment by BethanyG** [comment]
Please also see #2428, for issues that need to be addressed before this exercise can go back to being live.

**Comment by BethanyG** [comment]
Closing, as this is no longer blocking progress on the site.
