### ISSUE TITLE
Python Learning Exercise Instruction, Test, and Sub Mismatch (Little Sister's Essay) 

### ISSUE THREAD

**Issue by OpenWiseFound** [exercism/python#2483]
So, the instructions, stub (in the online editor, I haven't tried the CLI), and test make solving this impossible for a beginner/learner. 

First, the instructions say this: 

<img width="858" alt="Screen Shot 2021-08-05 at 2 37 16 PM" src="https://user-images.githubusercontent.com/18388842/128404337-fe716a27-e87f-45f0-999d-6aae942b174e.png">

And the stub agrees because the student is presented with this: 

<img width="689" alt="Screen Shot 2021-08-05 at 2 38 58 PM" src="https://user-images.githubusercontent.com/18388842/128404465-48f6fbd1-9445-445c-9018-34f28f24577c.png">

However, if a student tries to run a test even before editing remove_extra_spaces() they receive this error: 

<img width="557" alt="Screen Shot 2021-08-05 at 2 48 43 PM" src="https://user-images.githubusercontent.com/18388842/128404861-f0f734fd-f346-4835-b728-0b53cab45974.png">

So, they need to rename the remove_extra_spaces()  to get any of the test to run: 

<img width="380" alt="Screen Shot 2021-08-05 at 2 49 18 PM" src="https://user-images.githubusercontent.com/18388842/128405109-db27d100-4293-4f74-a506-cc79890d5513.png">

Second, the instructions say this: 

<img width="876" alt="Screen Shot 2021-08-05 at 2 37 25 PM" src="https://user-images.githubusercontent.com/18388842/128405242-2eb14edc-dfa6-4818-b7f7-821506bd5d2f.png">

However, the stub has the parameters for the replace_word_choice() flipped: 
<img width="689" alt="Screen Shot 2021-08-05 at 2 38 58 PM" src="https://user-images.githubusercontent.com/18388842/128405392-b555fa61-9ee8-4238-aa21-cceae7c74d7a.png">

Therefore, the student has to do something like this (flip the parameters) to pass the tests, which agree with the instructions: 

<img width="592" alt="Screen Shot 2021-08-05 at 2 39 10 PM" src="https://user-images.githubusercontent.com/18388842/128405479-6b0416fe-fd69-4a8e-b27e-5eab8a059a27.png">

**Comment by BethanyG** [comment]
@OpenWiseFound  -- this should now be fixed & merged.  Please raise a new issue or comment here if that is not the case.  Thanks!
