### ISSUE TITLE
Check docs are up to date

### ISSUE THREAD

**Issue by ErikSchierboom** [exercism/python#2484]
Please check if your documentation files are still up-to-date.

The key documentation files to check are:

- [x] `docs/ABOUT.md`
- [x] `docs/INSTALLATION.md`
- [x] `docs/LEARNING.md`
- [x] `docs/RESOURCES.md`
- [x]  `docs/TESTS.md`
- [x] `exercises/shared/.docs/help.md`
- [x] `exercises/shared/.docs/tests.md`

There might be more.

## Link check report

To help identify invalid links, we've automatically checked the links of _all_ `*.md` files in this repo.
This is the report of that check:

<pre style="color:#bbb;white-space:pre-wrap;word-wrap:break-word;overflow-wrap:break-word">📝 Summary
---------------------
🔍 Total.........1583
✅ Successful....1574
⏳ Timeouts.........1
🔀 Redirected.......0
👻 Excluded.........0
🚫 Errors...........8

Errors in ./docs/LEARNING.md
<span style="color:#ffff55">⧖ https://www.learnpython.org/</span>

Errors in ./concepts/basics/about.md
<span style="color:#ff5555">✗ https://blog.startifact.com/posts/older/what-is-pythonic.html (error sending request for url (https://blog.startifact.com/posts/older/what-is-pythonic.html): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (certificate has expired))</span>

Errors in ./reference/exercise-concepts/matrix.md
<span style="color:#ff5555">✗ https://exercism.io/tracks/python/exercises/matrix/solutions/b6a3486a35c14372b64fdc35e7c6f98f (HTTP status client error (404 Not Found) for url (https://exercism.io/tracks/python/exercises/matrix/solutions/b6a3486a35c14372b64fdc35e7c6f98f))</span>

Errors in ./exercises/concept/guidos-gorgeous-lasagna/.docs/introduction.md
<span style="color:#ff5555">✗ https://blog.startifact.com/posts/older/what-is-pythonic.html (error sending request for url (https://blog.startifact.com/posts/older/what-is-pythonic.html): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (certificate has expired))</span>

Errors in ./docs/TESTS.md
<span style="color:#ff5555">✗ https://www.youtube.com/watch?v=P0pIW5tJrRM (HTTP status client error (401 Unauthorized) for url (https://www.youtube.com/oembed?url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DP0pIW5tJrRM))</span>

Errors in ./concepts/basics/introduction.md
<span style="color:#ff5555">✗ https://blog.startifact.com/posts/older/what-is-pythonic.html (error sending request for url (https://blog.startifact.com/posts/older/what-is-pythonic.html): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (certificate has expired))</span>

Errors in ./exercises/concept/little-sisters-essay/.docs/introduction.md
<span style="color:#ff5555">✗ https://unicode.org/emoji/'.strip('/stph:') (HTTP status client error (404 Not Found) for url (https://unicode.org/emoji/'.strip('/stph:')))</span>

Errors in ./exercises/concept/making-the-grade/.docs/hints.md
<span style="color:#ff5555">✗ https://docs.python.org/3/tutorial/controlflo.html#break-and-continue-statements-and-else-clauses-on-loops (HTTP status client error (404 Not Found) for url (https://docs.python.org/3/tutorial/controlflo.html#break-and-continue-statements-and-else-clauses-on-loops))</span>

Errors in ./reference/concepts/pythonic.md
<span style="color:#ff5555">✗ https://blog.startifact.com/posts/older/what-is-pythonic.html (error sending request for url (https://blog.startifact.com/posts/older/what-is-pythonic.html): error trying to connect: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:1915: (certificate has expired))</span>

</pre>
## Tracking

https://github.com/exercism/v3-launch/issues/54

**Comment by BethanyG** [comment]
@ErikSchierboom  -- Thanks for filing this, and for checking all the links.  I am re-flagging this as `intermediate` knowledge needed, and as size `medium`.  None of these docs are up-to-date with either the latest version of Python nor the latest version of PyTest, so they're going to take a fair amount of work.  Going to try to bring them up to date this weekend.

**Comment by ErikSchierboom** [comment]
@BethanyG Great. Just found out that I didn't actually check all links 🤦 But I'm hitting rate limits if I do 🤷

**Comment by ErikSchierboom** [comment]
@BethanyG Updated! There _might_ be some false positives, mind.

**Comment by BethanyG** [comment]
@ErikSchierboom  - If you have a moment and can click approve on the linked PRs....  😁   I think I am FINALLY done with these!  🎉   (_of course now there will be issues...._).

**Comment by ErikSchierboom** [comment]
@BethanyG Sure. Just done that. I haven't read any content though :D

**Comment by BethanyG** [comment]
Oh..you really should read the content.  I tell such interesting stories about you!  (_joking, of course!_).  Many thanks for the clickty-clicks!  🌟

**Comment by ErikSchierboom** [comment]
Haha, lol.
