### ISSUE TITLE
test_round_scores() at Making the Grade accepts only the reversed list of rounded data 

### ISSUE THREAD

**Issue by kbuc** [exercism/python#2526]
`test_round_scores()` at "Making the Grade" accepts only the reversed list of rounded data (https://github.com/kbuc/python/edit/main/exercises/concept/making-the-grade/loops_test.py).  The focus of the exercise is to round the data in a given list. If the order of the rounded results is not important, (this should be stated in the exercise text!) it broadens the possible approaches (like using `pop()` in a loop to create rounded array, which would be reversed).

I suggest the test compares sorted arrays and is therefore not sensitive to results order.

Will make a PR.

**Comment by BethanyG** [comment]
@kbuc - Thank you so much for logging this!  Looking forward to the PR.

**Comment by BethanyG** [comment]
Noting here that the exercise instructions should also be updated to say that the score order is unimportant.  This can be done in the same PR, or left to a different one.

**Comment by kbuc** [comment]
There are 2 commits in the PR, one for the code and one for the instructions.

**Comment by BethanyG** [comment]
Closed by #2527
