### ISSUE TITLE
Some problems with "Making the Grade" python task

### ISSUE THREAD

**Issue by CosmoSt4r** [exercism/python#2532]
I got some problems with ["Making the Grade"](https://exercism.org/tracks/python/exercises/making-the-grade) learning pyhon task

1. First is minor. I think they should be in one style
![int typos](https://user-images.githubusercontent.com/69130500/131979347-0a6357cc-c9fd-4071-8beb-2f2ad6e7d278.png)

2. These closing tags probably aren't supposed to be here
![closing tags](https://user-images.githubusercontent.com/69130500/131979663-7508ce94-2b15-47dc-80a1-8e085ddb398d.jpg)

3. In fifth function named **student_ranking** incoming lists with scores and names should be the same length but in the first test for this function they are not:
```py
def test_student_ranking(self):
        scores = [
            [100, 98, 92, 86, 70, 68, 67, 60, 50], <-- 9 elements
            [82],
            [88, 73],
        ]
        names = [
            ['Rui', 'Betty', 'Joci', 'Yoshi', 'Kora', 'Bern', 'Jan', 'Rose'], <-- 8 elements
            ['Betty'],
            ['Paul', 'Ernest'],
        ]
```
If this is intentional it should be added into function's description

4. Description of the sixth function says:
```
If no 100 scores are found in student_info, the string "No perfect scores." should be returned.
```
But in tests we have this:
```py
result_data = [
           "No perfect score.",
           ['Raiana', 100],
           ['Joci', 100],
           "No perfect score.",
           "No perfect score."
       ]
```
("No perfect score." vs. "No perfect score**s**.")

**Comment by BethanyG** [comment]
Thank you for logging this, (and for the PR!!).  Closed by [#2533](https://github.com/exercism/python/pull/2533).
