### ISSUE TITLE
meltdown exercise instructions are printed badly

### ISSUE THREAD

**Issue by elyashiv** [exercism/python#2534]
I think this picture explains it all:
![image](https://user-images.githubusercontent.com/1577529/131999292-4ccb492d-5a82-493f-96db-7e811e8ff532.png)

**Comment by BethanyG** [comment]
Thank you for logging this, @elyashiv!  
I took a look at the markdown and the main page instructions, and things _appear_ OK:

Main instructions at https://exercism.org/tracks/python/exercises/meltdown-mitigation
![image](https://user-images.githubusercontent.com/5923094/132043097-c36d34b0-508d-4490-afe8-6fa7cea0d9c5.png)
__________ 
Markdown in the [exercise file](https://github.com/exercism/python/blob/main/exercises/concept/meltdown-mitigation/.docs/instructions.md)
![image](https://user-images.githubusercontent.com/5923094/132043221-607001c8-723b-498f-9eca-ed12f321e969.png)
__________

So I think that this is actually a website render issue, and needs to be transferred to the `exercsim/exercism` repo.

**Comment by BethanyG** [comment]
@iHiD - not a high priority, but I think this is a markdown render issue in the task pane.  Can you transfer this to `exercism/exercism`?  If not, I am happy to recreate the issue -- just let me know.  😄

**Comment by iHiD** [comment]
I missed this, sorry. Is this fixed now?

**Comment by BethanyG** [comment]
Yup.  Just re-read this (I ended up missing your comment as well, apologies).  Turns out, we had a bad closure on some of the highlights, so it was our issue all along.  With any luck, [PR2595](https://github.com/exercism/python/pull/2595) fixes it.
