### ISSUE TITLE
Python - Triple double-quote docstrings are not detected?

### ISSUE THREAD

**Issue by BigMoonTech** [exercism/python#2538]
[C0114 missing-module-docstring] : ["Missing module docstring"] was reported by Pylint.

PyCharm suggests that docstrings should be triple double-quotes. I go with my editor and change the docstrings to double-quotes but exercism doesn't detect the docstrings unless the are triple single-quotes.

**Comment by BethanyG** [comment]
👋🏽   @BigMoonTech  -- That took longer than I wanted, but if all went well with the gods of deployment, you should be seeing double quote docstrings for concept exercise `exemplar.py` and stub files now.  😄  .  Let us know if you see any issues or have any questions!

**Comment by BigMoonTech** [comment]
🤩 You guys rock. From what I've seen, everything looks good so far. Thank you for pushing this fix so fast, and thanks for hearing me!
