### ISSUE TITLE
[Testing] Add Pytest.ini file in Python Directory for Local Pytest Configuration

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#2539]
Since we're using a custom `pytest.marks.task(taskno)` for our Concept exercise tests, we need to have a way for CLI users to register them.  Otherwise, PyTest complains for every test locally (see issue #2536).  

The most expedient way to do this is to provide a `pytest.ini` file as part of the python exercise directory.
If we'd rather not do it in the main `exercism/python` folder, we could add it into `exercism/python/exercise` or `exercism/python/exercises/concept`.
Additionally, we should update the documentation to show users how to register or ignore the marks themselves.

The ini file should include:
```code
[pytest]
markers =
    task: A concept exercise task.
```

**Comment by BethanyG** [comment]
Further techniques to add to documentation (thank you to @kbuc for these) :

One can also run with `pytest -o markers=task`  or put it in an environmental variable `PYTEST_ADDOPTS` . 
Especially easy for those running in an pipenv virtual environment.

**Comment by siebenschlaefer** [comment]
Why was this issue closed?

The file `HELP.md` still says
> To run the included *tests*, run the test file using the `pytest` module, replacing `{exercise_name}`:
> 
> ```bash
> $ python3 -m pytest {exercise_name}_test.py
> ```

And if I do that I get tons of warnings:
```
========================================= warnings summary ==========================================
classes_test.py:15
  /exercise_test.py:15: PytestUnknownMarkWarning: Unknown pytest.mark.task - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/stable/how-to/mark.html
    @pytest.mark.task(taskno=1)
...
```

Of course, if I start to look around there's a link in `HELP.md`:

> For more information about running tests using `pytest`, checkout our [Python testing guide](https://github.com/exercism/python/blob/main/docs/TESTS.md#pytest).

and at the end of that lengthy document there's a section *Fixing warnings*.

That's not a great user experience. If I as an experienced developer find that bothersome and had to spend some time to find that paragraph how must that feel for a beginner? 

To quote Raymond Hettinger: "There must be a better way", right?

**Comment by BethanyG** [comment]
Hi @siebenschlaefer   -- Thanks for the poke.  😄   YES -- **there is indeed a better way** -- and I need to follow up on it.  See issue #2745 -- which is a similar issue outlining what we will ultimately do (_and why we closed this issue_):  have the said `pytest.ini` file downloaded as part of the CLI, and have instructions on how to place it in the correct position to silence the warnings.

**But more to your point:**  we also need to change the `HELP.md` and **Python testing guide** to have different instructions up front on how to run `pytest` so that the warnings don't happen, along with instructions on how to download/create and place the `pytest.ini` file while we work on having it download automatically.

I'll go ahead and create those issues later today my time.  Meanwhile, since this issue is about creating the `pytest.ini` file in this repo -- not about giving students instructions on how to configure pytest -- I am going to leave it in [closed] state but link it to the other issues, to keep things together.

**Comment by BethanyG** [comment]
@siebenschlaefer - I've made updates to `exercises/shared/.docs/tests.md` and `/docs/TESTING.md`.  Would love any feedback you have to give on either document wrt clarity around pytest markers.  _Many thanks for your help!_.

@ErikSchierboom - any update on whether or not we've got the `pytest.ini` file download via the CLI?  I'll want to change the directions once it starts downloading....
