### ISSUE TITLE
[Currency Exchange]  Docstrings Missing return type and value

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#2545]
The [`currency exchange`](https://github.com/exercism/python/tree/main/exercises/concept/currency-exchange) concept exercise [stub](https://github.com/exercism/python/blob/main/exercises/concept/currency-exchange/exchange.py) and [exemplar.py](https://github.com/exercism/python/blob/main/exercises/concept/currency-exchange/.meta/exemplar.py) files are missing the return type and values from their docstrings.  We should add them in since this is a learning exercise, and needs to be more formal.

**Comment by BethanyG** [comment]
@CosmoSt4r  -- if you'd like to take this one, lmk and I will put [claimed] on it.  Thanks!

**Comment by CosmoSt4r** [comment]
> @CosmoSt4r -- if you'd like to take this one, lmk and I will put [claimed] on it. Thanks!

Yes, I do

**Comment by BethanyG** [comment]
I have no clue as to why the closes syntax didn't work.  But this is closed by #2548.  Nice work!
