### ISSUE TITLE
[Practice Exercises] Add Guidance for Exercises that Require Raising Errors or Error handling

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#2563]
When we transitioned to the current version of exercism, we removed the generic "raising exceptions" notices from all the exercise READMEs.  We felt they were adding confusion and leading students to insert error raising and handling in places where they should not have been inserting it.

For the Python track, we were (and are!) planning `error handling` concept exercises to help students learn how to raise and handle errors properly in their code.  

But those exercises are still in process, and we have **42** [practice exercises](https://exercism.org/docs/building/tracks/practice-exercises) that test for error handling in one way or another.  
**37** of these include `JinJa2` test generation templates.

As a stopgap while we create the `error handling` concept exercises, we need to create practice exercise `.docs/instructions.append.md` files for the `42` exercises that add back a blurb about how to raise an exception.  The original vs proposed language for the `instructions.append.md` is at the bottom, but is open to any edits that make sense and help student understanding.  

 For the 37 `JinJa2` exercises, we will need to modify the test generation templates to test for a meaningful **_exception message_**, and not just the _presence_ of any exception.  We'll then need to regenerate those test files.

For the 5 exercises that remain, we will need to hand-edit the test files as opposed to editing a generation template.

Recommend that a PR for ONE exercise be done as a first pass to make sure the changes do indeed makes sense, then the remainder of them can be done.

*  [Practice Exercise Specs](https://exercism.org/docs/building/tracks/practice-exercises)
*  [Exercism Markdown Specs](https://exercism.org/docs/building/markdown/markdown)
*  [Python Track Test Generator](https://github.com/exercism/python/blob/main/docs/GENERATOR.md)
*  [JinJa2 Tutorial](https://zetcode.com/python/jinja/)

**These are the 42 practice exercises in question:**

[PR 2685](https://github.com/exercism/python/pull/2685)
- [x] [affine-cipher](https://github.com/exercism/python/tree/main/exercises/practice/affine-cipher/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/affine-cipher/affine_cipher_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/affine-cipher/.meta/template.j2)
- [x] [all-your-base](https://github.com/exercism/python/tree/main/exercises/practice/all-your-base/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/all-your-base/all_your_base_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/all-your-base/.meta/template.j2)
- [x] [bank-account](https://github.com/exercism/python/tree/main/exercises/practice/bank-account/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/bank-account/bank_account_test.py)
- [x] [binary-search](https://github.com/exercism/python/tree/main/exercises/practice/binary-search/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/binary-search/binary_search_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/binary-search/.meta/template.j2)
- [x] [binary](https://github.com/exercism/python/tree/main/exercises/practice/binary/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/binary/binary_test.py)

<br>

[PR 2691](https://github.com/exercism/python/pull/2691)
- [x] [bowling](https://github.com/exercism/python/tree/main/exercises/practice/bowling/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/bowling/bowling_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/bowling/.meta/template.j2)
- [x] [change](https://github.com/exercism/python/tree/main/exercises/practice/change/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/change/change_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/change/.meta/template.j2)
- [x] [circular-buffer](https://github.com/exercism/python/tree/main/exercises/practice/circular-buffer/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/circular-buffer/circular_buffer_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/circular-buffer/.meta/template.j2)
- [x] [collatz-conjecture](https://github.com/exercism/python/tree/main/exercises/practice/collatz-conjecture/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/collatz-conjecture/collatz_conjecture_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/collatz-conjecture/.meta/template.j2)
- [x] [dot-dsl](https://github.com/exercism/python/tree/main/exercises/practice/dot-dsl/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/dot-dsl/dot_dsl_test.py)

<br>

[PR 2692](https://github.com/exercism/python/pull/2692)
- [x] ~~[error-handling](https://github.com/exercism/python/tree/main/exercises/practice/error-handling/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/error-handling/error_handling_test.py)~~ Exercise has been depreciated. 
- [x] [forth](https://github.com/exercism/python/tree/main/exercises/practice/forth/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/forth/forth_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/forth/.meta/template.j2)
- [x] [go-counting](https://github.com/exercism/python/tree/main/exercises/practice/go-counting/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/go-counting/go_counting_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/go-counting/.meta/template.j2)
- [x] [grains](https://github.com/exercism/python/tree/main/exercises/practice/grains/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/grains/grains_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/grains/.meta/template.j2)
- [x] [hamming](https://github.com/exercism/python/tree/main/exercises/practice/hamming/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/hamming/hamming_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/hamming/.meta/template.j2)

<br>

[PR 2715](https://github.com/exercism/python/pull/2715)
- [x] [hangman](https://github.com/exercism/python/tree/main/exercises/practice/hangman/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/hangman/hangman_test.py)
- [x] ~~[hexadecimal](https://github.com/exercism/python/tree/main/exercises/practice/hexadecimal/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/hexadecimal/hexadecimal_test.py)~~ Exercise has been depreciated.
- [x] [largest-series-product](https://github.com/exercism/python/tree/main/exercises/practice/largest-series-product/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/largest-series-product/largest_series_product_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/largest-series-product/.meta/template.j2)
- [x] [meetup](https://github.com/exercism/python/tree/main/exercises/practice/meetup/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/meetup/meetup_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/meetup/.meta/template.j2)
- [x] [minesweeper](https://github.com/exercism/python/tree/main/exercises/practice/minesweeper/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/minesweeper/minesweeper_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/minesweeper/.meta/template.j2)

<br>

[PR 2716](https://github.com/exercism/python/pull/2716)
- [x] [nth-prime](https://github.com/exercism/python/tree/main/exercises/practice/nth-prime/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/nth-prime/nth_prime_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/nth-prime/.meta/template.j2)
- [x] ~~[nucleotide-count](https://github.com/exercism/python/tree/main/exercises/practice/nucleotide-count/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/nucleotide-count/nucleotide_count_test.py)~~ Exercise has been depreciated.
- [x] [ocr-numbers](https://github.com/exercism/python/tree/main/exercises/practice/ocr-numbers/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/ocr-numbers/ocr_numbers_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/ocr-numbers/.meta/template.j2)
- [x] ~~[octal](https://github.com/exercism/python/tree/main/exercises/practice/octal/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/octal/octal_test.py)~~ Exercise has been deprciated.
- [x] [palindrome-products](https://github.com/exercism/python/tree/main/exercises/practice/palindrome-products/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/palindrome-products/palindrome_products_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/palindrome-products/.meta/template.j2)

<br>

[PR 2725](https://github.com/exercism/python/pull/2725)
- [x] [perfect-numbers](https://github.com/exercism/python/tree/main/exercises/practice/perfect-numbers/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/perfect-numbers/perfect_numbers_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/perfect-numbers/.meta/template.j2)
- [x] [phone-number](https://github.com/exercism/python/tree/main/exercises/practice/phone-number/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/phone-number/phone_number_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/phone-number/.meta/template.j2)
- [x] [pov](https://github.com/exercism/python/tree/main/exercises/practice/pov/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/pov/pov_test.py)
- [x] [queen-attack](https://github.com/exercism/python/tree/main/exercises/practice/queen-attack/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/queen-attack/queen_attack_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/queen-attack/.meta/template.j2)

<br>

[PR 2727](https://github.com/exercism/python/pull/2727)

- [x] ~~[rational-numbers](https://github.com/exercism/python/tree/main/exercises/practice/rational-numbers/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/rational-numbers/rational_numbers_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/rational-numbers/.meta/template.j2)~~ actually, no error cases here.
- [x] ~~[robot-simulator](https://github.com/exercism/python/tree/main/exercises/practice/robot-simulator/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/robot-simulator/robot_simulator_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/robot-simulator/.meta/template.j2)~~ No error cases currently.  Consider adding some later.
- [x] ~~[roman-numerals](https://github.com/exercism/python/tree/main/exercises/practice/roman-numerals/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/roman-numerals/roman_numerals_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/roman-numerals/.meta/template.j2)~~ Doesn't have error cases either.  Maybe we should consider adding some.
- [x] ~~[run-length-encoding](https://github.com/exercism/python/tree/main/exercises/practice/run-length-encoding/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/run-length-encoding/run_length_encoding_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/run-length-encoding/.meta/template.j2)~~ No error cases.
- [x] [saddle-points](https://github.com/exercism/python/tree/main/exercises/practice/saddle-points/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/saddle-points/saddle_points_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/saddle-points/.meta/template.j2)
- [x] [satellite](https://github.com/exercism/python/tree/main/exercises/practice/satellite/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/satellite/satellite_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/satellite/.meta/template.j2)

<br>

[PR 2734](https://github.com/exercism/python/pull/2734)

- [x] [say](https://github.com/exercism/python/tree/main/exercises/practice/say/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/say/say_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/say/.meta/template.j2)
- [x] [series](https://github.com/exercism/python/tree/main/exercises/practice/series/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/series/series_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/series/.meta/template.j2)
- [x] [sgf-parsing](https://github.com/exercism/python/tree/main/exercises/practice/sgf-parsing/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/sgf-parsing/sgf_parsing_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/sgf-parsing/.meta/template.j2)
- [x] [simple-linked-list](https://github.com/exercism/python/tree/main/exercises/practice/simple-linked-list/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/simple-linked-list/simple_linked_list_test.py)
- [x] [tree-building](https://github.com/exercism/python/tree/main/exercises/practice/tree-building/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/tree-building/tree_building_test.py)
- [x] [variable-length-quantity](https://github.com/exercism/python/tree/main/exercises/practice/variable-length-quantity/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/variable-length-quantity/variable_length_quantity_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/variable-length-quantity/.meta/template.j2)
- [x] [wordy](https://github.com/exercism/python/tree/main/exercises/practice/wordy/) \| [test file](https://github.com/exercism/python/tree/main/exercises/practice/wordy/wordy_test.py) \| [template file](https://github.com/exercism/python/tree/main/exercises/practice/wordy/.meta/template.j2)
______________________________________________________________
The original and proposed new `error handling` messages are below.

`[ORIGINAL]`
## Exception messages
Sometimes it is necessary to raise an exception. When you do this, you should include a meaningful error message to indicate what the source of the error is. This makes your code more readable and helps significantly with debugging. Not every exercise will require you to raise an exception, but for those that do, the tests will only pass if you include a message.

To raise a message with an exception, just write it as an argument to the exception type. For example, instead of raise Exception, you should write:

raise Exception("Meaningful message indicating the source of the error")
_________________________________

`[Suggested Changes]`

## Exception messages
Sometimes it is necessary to [raise an exception](https://docs.python.org/3/tutorial/errors.html#raising-exceptions). When you do this, you should always include a **meaningful error message** to indicate what the source of the error is. This makes your code more readable and helps significantly with debugging.  For situations where you know that the error source will be a certain type, you can choose to rase one of the [built in error types](https://docs.python.org/3/library/exceptions.html#base-classes), but should still include a meaningful message.

This particular exercise requires that you use the [raise statement](https://docs.python.org/3/reference/simple_stmts.html#the-raise-statement) to "throw" an `exception`. The tests will only pass if you both `raise` the `exception` and include a message with it.

To raise an `exception` with a message, write the message as an argument to the `exception` type: 

```python
raise Exception("Meaningful message indicating the source of the error")
```

**Comment by BethanyG** [comment]
I can only **_hope_** to abandon this.  Nice try, gitbot, but I think this needs to stay open.  😞

**Comment by cmccandless** [comment]
Note for anyone else who falls down this rabbit hole after me 😅 :

This policy supersedes https://github.com/exercism/python/issues/1080

**Comment by BethanyG** [comment]
Apologies you fell down a hole.  🙂   We changed this because we were getting a preponderance of students using blank spaces, periods, and dashes as error messages, which is completely not in the spirit of, well _error messages_.  While it is not at all ideal to expect a specific message(_even if it's coming directly from the problem spec_), it was the best we could come up with.  We balance this with having appends that are explicit with examples.

Error messaging concept exercises are still on the docket — and are even more important now that Python 3.13 has error message groups on top of everything else.  We might be able to be more flexible, but we'll have to wait until we get into it.

The up side?  We no longer support anything under Python 3.9 because of changes to Python and tooling constraints, so supporting different 2.7 syntax is no longer an issue.  Once our upgrade to Python 3.13 is complete, our support matrix is going to be 3.9, 3.10, 3.11, 3.12, 3.13.
