### ISSUE TITLE
Are example.py meant to show up in Guidance in the Mentoring Window... because exemplar.py do?

### ISSUE THREAD

**Issue by cjwomack** [exercism/python#2577]
I was wondering whether it is intentional that only exemplar.py (for concept exercises) is shown under the Guidance tab in Mentoring discussion or is this because it is new for concept exercises ? This is no sample solution shown for practice exercises despite there being example.py as a sample solution. Should .meta/config.json be changed or is the functionality is correct?

**Comment by IsaacG** [comment]
The mentoring guide is pulled from [webite-copy](https://github.com/exercism/website-copy/tree/main/tracks/python/exercises) and maintained separately from the exercises themselves.

The exemplar.py is intended as an example of how the exercise can be solved - not necessarily the optimal solution, though.

**Comment by BethanyG** [comment]
@IsaacG  -- the `exemplar.py` files for concept exercises are considered a standard.  The `example.py` files are not - or not as much.

**Comment by cjwomack** [comment]
Thanks for getting back to me with all this information.
