### ISSUE TITLE
Stubs and examples can use linting

### ISSUE THREAD

**Issue by IsaacG** [exercism/python#2582]
This is a superset of https://github.com/exercism/python/issues/2579 (long lines)

`pylint` flags all sorts of issues that ought to be cleaned up.

```
» find exercises -name \*.py ! -name \*_test.py -exec pylint -d C0116,W0613,C0114,C0115,C0103,R0801,W0707,W0107,C0301,R0903,W0511 {} +
```

Logging this is a "on hold, revisit later" type issue for now.

**Comment by BethanyG** [comment]
..and as a superset of #2579, it has a hold for a similar reason.  We need to have the track a bit more stable and a bit more filled out with concepts and concept exercises before we loop back for a discussion about `practice` stub files, line length, or any PyLint whining.  We may also choose to not enforce some PyLint rules.  That is still TBD.

Additionally - `example` files are more or less exempt from formal linting rules.   It isn't that "anything goes" -- but  [the spec](https://github.com/exercism/docs/blob/main/building/tracks/practice-exercises.md#file-example-implementation) says nothing about them being any sort of **exemplar**, and they are at most a "minimum implementation" for use in CI and testing.  It is a very low priority that we look through them all.

**Comment by J08K** [comment]
Whoops, closed the wrong thing 💙

**Comment by J08K** [comment]
Closed by 8 PRs, linted all stubs and exemplars.
