### ISSUE TITLE
Twelve-Days - 3 Tests use student's code to compare against the student's code

### ISSUE THREAD

**Issue by Ou42** [exercism/python#2587]
The following 3 tests compare the results of the student's code against ... itself:
```
    def test_recites_first_three_verses_of_the_song(self):
        expected = [recite(n, n)[0] for n in range(1, 4)]
        self.assertEqual(recite(1, 3), expected)

    def test_recites_three_verses_from_the_middle_of_the_song(self):
        expected = [recite(n, n)[0] for n in range(4, 7)]
        self.assertEqual(recite(4, 6), expected)

    def test_recites_the_whole_song(self):
        expected = [recite(n, n)[0] for n in range(1, 13)]
        self.assertEqual(recite(1, 12), expected)
```
How I found this? I misspelled "fourth" in an early iteration. ( forth )

I've worked on the twelve_days_tests.py and have a non-impressive ( ie IMHO nothing worth the student duplicating ) version that I believe solves this issue ( and AFAICT doesn't create new problems. ) How do I share it?

TY

**Comment by BethanyG** [comment]
Hi @Ou42 👋🏽    Thanks for logging this!  The test cases for `Twelve-Days` on the Python track are auto-generated from a central [`problems specifications`](https://github.com/exercism/problem-specifications) repo, so any changes/issues should first be brought up there, then we can asses if the changes should be in a python-only append, or if the central specification needs to be changed.  Thanks!

**Comment by Ou42** [comment]
Oops. 🤦‍♂️ Should've asked first, eh?
OK. Learning.
I dug and found:
https://github.com/exercism/problem-specifications/blob/main/exercises/twelve-days/canonical-data.json
and it looks like it explicitly states the 3 range based tests.
I'm not sure where to go from here. I'm off until later this evening.

Thanks again.

**Comment by Ou42** [comment]
Found the support chat and talked to @NobbZ and I think I grok it now.
Once the first 12 tests pass -- testing each verse individually -- it's then OK to test a (start, stop) "range" of args against a range of individual verses.
It's a tad confusing, but clever.
Also, when I typo fourth ( 'forth') again, it only fails the 1 test now. Not sure if this is on my end or a fix on the dev side or what.

Anyway, thank you for your time.
