### ISSUE TITLE
[Currency Exchange]:  Improve Variable Naming and Clarify Instructions

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#2594]
The [currency-exchange](https://exercism.org/tracks/python/exercises/currency-exchange) concept exercise for `numbers` needs additional editing for clarity and readability.  
For background, see [Issue 2591](https://github.com/exercism/python/issues/2591)

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before diving into the implementation, please read up on the following documents:

- [Contributing to Exercism](https://exercism.org/contributing) |  [Help](https://exercism.org/docs/building/product)
- [What are those Weird Task Tags about?](https://exercism.org/docs/building/product/tasks)
- [Building Language Tracks: An Overview](https://exercism.org/docs/building/tracks) 
- [What are Concepts?](https://exercism.org/docs/building/tracks/concepts)
- [Concept Exercise Specifications](https://exercism.org/docs/building/product/concept-exercises)
- [Exercism Formatting and Style Guide](https://exercism.org/docs/building/markdown/style-guide)
- [Exercism Markdown Specification](https://exercism.org/docs/building/markdown/markdown)

-------

 **Tasks include:**

- [x] Rephrasing/revision of variable names in instructions and `exemplar.py`.  Current names are causing confusion.
- [x] Editing/clarification of task descriptions & removal of numbered lists.
- [x] Formatting of function names with parameters to be closer to this example:  [Little Sisters Essay](https://github.com/exercism/python/blob/main/exercises/concept/little-sisters-vocab/.docs/instructions.md)
- [x] Spell checking of all associated documents.
- [x] Grammar checking of all associated documents  (AmEn rules)
- [x] Review for readability and topic coverage
- [x] Review of code examples for syntax, [PEP8](https://www.python.org/dev/peps/pep-0008/), and [PEP257](https://www.python.org/dev/peps/pep-0257/)
- [x] Review of `exemplar.py` for syntax, PEP8, and PEP257
- [x] Review of test files and stub files fo syntax and PEP8.  Docstrings not required here.
________

Additionally, if a way can be found to add `complex` numbers to this exercise, that would be excellent.

________

Exercise folder can be found here: [currency-exchange](https://github.com/exercism/python/tree/main/exercises/concept/currency-exchange)
Concept folder can be found here: [numbers](https://github.com/exercism/python/tree/main/concepts/numbers)

**Comment by J08K** [comment]
Currently working on this! :)
