### ISSUE TITLE
[Card-Games]: Phrasing of Task 5 Leads Students to Think Associated Test Cases Are Wrong

### ISSUE THREAD

**Issue by SaschaMann** [exercism/python#2597]
in test 15, approx_average_is_average(hand) for hand = [2,3,4,8,8] expects True, however, unless I am taking crazy pills, the average of hand is 5, and the median is 4. 

5 == 4 is False. No?

---

I think there might be a little problem with Task 6. The second example (which also happens to be test 14) has the following list: [2, 3, 4, 8, 8], that is, median 4, average 5. Since the task asks us to compare these two values, I suppose it should then read False, not True (both in the example and, more importantly, in the test).

---

Python/card-games : error in test

the function ApproxAverageIsAverage(hand: list) -> bool
is supposed to compare the average of list to it's median, and return wether they are equal.

the test TestApproxAverageIsAverage.test_instructions_example_2
( card-games/lists_test.py line 188 )
contains an error: it tests the set [2, 3, 4, 8, 8]. the average of said set is 5, and the median is 4, but the test expects 'True'.

---

In test 14, the test wants you to return True, but the correct answer is False. The median of the list is 4, and its average is 5, so the test is wrong.

---

i have 1 test failure:

hand = [2, 3, 4, 8, 8]
want = True
result = False

the average of the list is 5.
the median of the list is 4.
so it make sense to get False and not True. 

---

Task 6 -> Test 14
How can it be that average of 2,3,4,8,8 is 5 and is equal to the middle number on the list?

---

The result is indeed FALSE

FAILED
Test 14
TestApproxAverageIsAverage.test instructions example 2

CODE RUN
hand = [2, 3, 4, 8, 8]
want = True
got = approx_average_is_average(hand)

self.assertEqual(
    want,
TEST FAILURE
AssertionError: True != False : Expected True but got an incorrect result: False

---

Hello Test 14  is:
TestApproxAverageIsAverage.test instructions example 2
hand = [2, 3, 4, 8, 8]
want = True

But in my opinion thats wrong. There should be want  = False! Because 5 != 4.

**Comment by BethanyG** [comment]
Putting the instructions in here to be really really clear (_emphasis mine_):

>In Black Joe, speed is important.
 Elyse thinks she can "shortcut" the traditional calculation to get an _average-like_ number by taking the average of the first and last card values in the hand - **or** by using the "middle" card value (the median) of the hand.
  She is hoping **one of these calculations** might come close to the average, but be quicker to calculate during game play. She'd like you to create a function to test her theory out.


>Implement a function `approx_average_is_average(<hand>)` that returns a Boolean, indicating if **EITHER** of Elyse's approximation formulas **IS THE SAME** as calculating the "full" average of a hand. For the sake of a simple median, we are going to assume the hand always has an odd number of card values.

So -- not if both the average and the median is the same.  But if the alternate average **OR** the median is the same.


So this is (yet again) about clarifying the instructions.  😄 .  The test case is correct, but the "real" task is very very easy to miss.  Re-titled bug to reflect that.

**Comment by BethanyG** [comment]
Proposed change:

> Implement a function `approx_average_is_average(<hand>)` that returns a Boolean.
 The function should return  `True` if _one (or both)_ of Elyse's approximations yields the same value as calculating the "full" average of a hand.
  The function should return `False` if _neither_ approximation formula yields the same value as the "full" average.
  For the sake of a simple median, we are going to assume the hand always has an odd number of card values.
