### ISSUE TITLE
Inconsistent whitespace in stubs

### ISSUE THREAD

**Issue by ynfle** [exercism/python#2602]
In [meltdown-mitigation](https://github.com/exercism/python/blob/2eaeb28bdc49bb23686175da0445162163454cec/exercises/concept/meltdown-mitigation/conditionals.py#L16) there is a blank line after the docstring before the `pass`, while in [ghost-gobble-arcade-game](https://github.com/exercism/python/blob/2eaeb28bdc49bb23686175da0445162163454cec/exercises/concept/ghost-gobble-arcade-game/arcade_game.py#L8) there is no blank line.

Was this intentional? Should it be standardized?

I'm happy to submit (a) PR(s) to standardize it

**Comment by BethanyG** [comment]
Hi @ynfle 👋🏽  !  Thanks for logging this.  Yes, there should be one blank line after the docstring.  And yes -- perfectly fine to submit a PR for `ghost-gobble-arcade-game`.  But please don't go through _all_ the stubs at this time.  We're still cleaning up things like instructions and code samples, so PR-ing a bunch of blank lines across exercises will add chaos we don't want.  😄

**Comment by ynfle** [comment]
Ok. I can totally wait and not do anything right now. Would one for `ghost-gobble-arcade-game` be useful? If not I can just wait.

**Comment by BethanyG** [comment]
Honestly?  There are other things that are more important right now (content & tests), so if you could wait that would be good.  😄

**Comment by ynfle** [comment]
So if you think this should be closed, then feel free. Good luck with the rest of the track
