### ISSUE TITLE
[Cater-Waiter] PyLint Has Praise Locally and Errors on Website.

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#2614]
Running the `Cater-Waiter` `expemplar.py` through the Python analyzer locally results in the following `analysis.json`:

```JSON
{
    "summary": "Good work! \ud83c\udf1f Here are some general recommendations for improving your Python code.",
    "comments": [
        {
            "comment": "python.pylint.convention",
            "params": {
                "lineno": "1",
                "code": "C0114 missing-module-docstring",
                "message": [
                    "Missing module docstring"
                ]
            },
            "type": "informative"
        }
    ]
}
```

However, the same file results in the following in the web editor:

![image](https://user-images.githubusercontent.com/5923094/135205201-4294bd34-ae47-47cc-9ea6-c757e0639435.png)

Suspect `PyLint` is getting greedy and running analysis on the test data files, or otherwise getting confused.  It is tripping up students, who are worried they are doing something wrong.

**Comment by BethanyG** [comment]
First thought here is to edit the test files to see if that stops the whining.

**Comment by J08K** [comment]
`exemplar.py` does not seem to generate the issue from my account. It is most likely linked to an older, outdated, version.
![image](https://user-images.githubusercontent.com/48634934/135337346-6687ac5a-8d82-4a9f-ab21-e42f2ca8f45f.png)
