### ISSUE TITLE
Lasagna may be too hard - making first exercise more accessible. 

### ISSUE THREAD

**Issue by kwikiel** [exercism/python#2616]
The problem: 
I've mentored over 150 solutions and finished exercism v2 python track so I assume I have some basic python skills, however I was unable to solve simplest exercise in v3 - the lasagna one. 

Previous problem had almost zero mental overhead ( hello world two_fer AFAIK )

With the help of @BethanyG I found the culprit in the error message :

```
ImportError: cannot import name &#39;preparation_time_in_minutes&#39; from &#39;lasagna&#39; (.mnt.exercism-iteration.lasagna.py)
```

It seems like I didn't implemented preparation_time_in_minutes at all. 

I was bamboozled by the `"&#39;"` and forgot that it's the usual way of python not being able to import a function from a file. 

New exercism prevents people from asking about mentorship if tests aren't passing. 

I see multiple ways to improve this exercise: 

- enable mentoring for first exercise even if tests aren't passing so first exercise would be an exercise in setting up the environment 

- better error logging ( _without_ `"&#39"` )  and maybe even something like this: https://github.com/Qix-/better-exceptions
(**my personal view:** two_fer hello world was IHMO better exercise)
 - for some people concept of lasagna is not obvious - i.e **does the baking time depends on number of layers?** what is lasagna? what is function? what's the difference between printing and returning? 
 
- ask the  person to implement just one function, not multiple ones. Introduce concepts one by one - not multiple of them like global variables, functions, relative imports,...

 I still remember when I had to learn the concept of loops in python ( for in style loops opposed to the C++ style loops) - for the beginner or the absolute beginner with 0 programming experience small things like that can prevent them from going forward and they could just drop out learning after failing to solve exercise nr 1. 
 
I expect many people to get stuck on first exercise without asking explicitly for help. 

**edited by BethanyG** _to correct Githubs over-eager auto-issue resolve for `#39;`_

**Comment by SleeplessByte** [comment]
"for the beginner or the absolute beginner with 0 programming experience small things like that can prevent them from going forward and they could just drop out learning after failing to solve exercise nr 1."

Yes, and this is the point. Exercism is _not_ a platform to *learn programming*. It's a platform for programmers to gain fluency in a new language. Most of your comments seem to cater a beginner, which is not the target for Exercism.

That said, I _absolutely_ agree with you that the error message should be fixed and not say `&#39`.

**Comment by iHiD** [comment]
:wave: Thanks for logging! A few thoughts.

1. FYI, Hello World comes before this exercise in the flow, so they've had to get a working setup before then (or used the editor).
2. Re enabling mentoring if someone can't solve the issue. The problem with this is that it means basically anyone can sign up with no programming experience and start using the mentors to help. If we allowed that, we'd get thousands of students per day wanting help with the fundamentals of programming, which would utterly overwhelm the mentors etc. So I think that wouldn't work. But we are considering allowing people to request mentoring for failed tests if some criteria are met (e.g. the user has solved exercises in a different track, or has certain rep, etc).
3. I think the tasks are quite well introduced 1 by 1 here (see screenshot below). By doing these in the order given, I think it's reasonable to get to a solution. Maybe it's harder working locally without the clear GUI to talk you through it? We could split lasagna into multiple exercises, but I think that would be too spoon-feeding for most developers coming to python as a second language.
4. Agree about the error stuff. It would confuse me too and know @BethanyG is fixing that.
5. `"&#39"` is fixed. That was my fault.

<img width="460" alt="Screenshot 2021-10-01 at 14 57 30" src="https://user-images.githubusercontent.com/286476/135632522-8b167324-a1e0-4426-87be-0438801c9f6c.png">

**Comment by BethanyG** [comment]
The `ImportError` UI messages for this exercise have been updated to:

For `constants`:

![image](https://user-images.githubusercontent.com/5923094/135707175-7293687a-e9ca-49ba-b510-296671f983e0.png)


For `functions`:

![image](https://user-images.githubusercontent.com/5923094/135707196-3586d00a-2213-482e-a76d-e2538c4d5c87.png)


For the command line, the error includes the traceback:

<img width="1293" alt="2021-10-02_00-11-09" src="https://user-images.githubusercontent.com/5923094/135707278-b2758062-b0b2-45a8-ba61-55371a99d6a1.png">

**Comment by J08K** [comment]
Great work @BethanyG!
