### ISSUE TITLE
[Card Games] Suggestions improvements for Task 5

### ISSUE THREAD

**Issue by R4ygen** [exercism/python#2625]
https://github.com/exercism/python/blob/1c2b930b952eb32f61973e222ee41e11b2d775f2/exercises/concept/card-games/lists_test.py#L99

Hello, while doing the test 5 in Python track's Card Games I encountered an issue with the Variation #7. I think it should return `False` instead of `True`. Since 8/2 and the median term equals 4, wich differs from the average of 5.
Correct me if I'm wrong.

**Comment by BethanyG** [comment]
Hi @R4ygen 👋🏽 

Thanks for logging this issue!  We've been discussing changing this task. Even with a (recent) wording change, it appears to be confusing users.  For reference, I'm going to past the directions for `Task 5` below:

![image](https://user-images.githubusercontent.com/5923094/135743440-a40a7a7a-e013-4cd9-bd48-2ac6f846a70c.png)


Not that is is an **`OR`** condition, and that the result is `True` if **either** the median **OR** the alt-average technique match the "full average".  The result is `False` if **neither** result matches. 

So the test is correct -- because **one** of the methods (_alt-average_) is the same as the "full" average -- but it feels deceiving because the **either** part of the instruction is easy to miss.

We'd welcome any suggestions you might have on how to improve this test case and task.  We may need to re-work it, or choose different numbers.  😄

**Comment by R4ygen** [comment]
Hello,
Thanks for the help, I see the mistake now, my bad. I was pretty tired when tried to do the exercise and misread the text in fact.

I could do a couple of suggestion to help improve the introduction to the test though, yes:
 

• The instructions for the exercise could be more separated from the "story" part of the text, to help focus more the attention on what is needed for the exercise and help don't miss details. Something like this:

> In Black Joe, speed is important. Elyse thinks she can "shortcut" the traditional calculation to get an average-like number by using just the first and last card values in the hand - or the median card value. She is hoping one of these calculations might come close to the average, but be quicker to calculate during game play. She'd like you to create a function to test her theory out.
> 
> Implement a function approx_average_is_average(<hand>) that returns a Boolean. The function should return True if the average of the first and last card values in the hand - OR the "middle" positioned card value (the median) of the hand, yields the same value as calculating the real average of a hand. The function should instead return False if neither approximation formula yields the same value as the real average. For the sake of a simpler median, we are going to assume the hand always has an odd number of card values.

 
• An additional variation similar to the number #7 could be added to double confirm these type of mistakes. In fact I was also pretty self convinced it was an error of the test since every other variation passed. Something like this:

`([13, 5, 11, 4, 22], True), `

**Comment by BethanyG** [comment]
@R4ygen - Nice!  I like those changes.  @J08K  -- what are your thoughts?  If these look good, maybe you can help Marco with submitting a PR?

**Comment by J08K** [comment]
@BethanyG, @R4ygen, I would love to see a PR on this with your full edit! Don't forget to ping either of us, @R4ygen.

Yes, the instructions definitely need a re-write, make them more readable at least. On the other hand, I think the instructions should still represent the context of the exercise. We do not want to give the student all the info, but we do want to hint them to them. It is important for a student to be able to solve simple text-explained exercises, as this also (somewhat) mimics how it is done in the real world.

So, try to rewrite the instructions: e.g. limiting sentences to 10 - 12 words, maximum of 2 sentences per line, etc. These are some guidelines you could follow, but language is not an _exact subject_ so everything is debatable.

Try looking up some guidelines yourself. As my _cheat sheet_ I use an article from a magazine that was written by professors in the dutch language, where they have a nice explanation of when to use certain language styles.

These are just some tips and tricks, I'd love to see what you come up with! Let me know!

**Comment by BethanyG** [comment]
@J08K -- do you have time this week to address this?  Let me know -- thanks!

**Comment by J08K** [comment]
Yup sure! Will get to this tomorrow!

**Comment by BethanyG** [comment]
@J08K  Just a gentle ping -- do you still want to work on this?  Let me know ... thanks!
