### ISSUE TITLE
[Ghost Gobble Arcade Game] Lacking test for win conditions

### ISSUE THREAD

**Issue by s-torn** [exercism/python#2627]
The Ghost Gobble Arcade Game exercise is solvable by defining a win only as not losing, the condition of having eaten all dots is not tested. 
In the current state the exercise passes the tests if the win function returns _not lose(power_pellet_active,touching_ghost)_.

**Comment by s-torn** [comment]
I'm not able to link my pull request, which I think is about permissions?
#2628

**Comment by J08K** [comment]
Hi there, nice catch! I did test out what you meant and you're right, the tests do allow for a student to pass the exercise even if they don't use `has_eaten_all_dots`. Funny that this was never noticed... I wonder how many students used this loop-hole to pass the exercise.

I will be reviewing your PR #2628 about this!
