### ISSUE TITLE
[Little Sister's Vocab/Essay]:  Update About.md to Include removeprefix and removesuffix

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#2641]
Python `3.9` [introduces](https://docs.python.org/3.9/whatsnew/3.9.html#new-features) two new string methods that make removing prefixes and suffixes easier.  

`Little Sisters Vocab` has the student remove prefixes and suffixes, but uses Python `3.8` methods.  Its follow-on exercise `Little Sisters Essay` has the student work with `startswith()` and `endswith()`.  

We should note in the `string-methods` [`about.md`](https://github.com/exercism/python/blob/main/concepts/string-methods/about.md) (_and possibly in the about.md of `strings`_) that is displayed after the student finishes `Little Sisters Essay` that Python `3.9` introduces some methods of convenience around removing prefixes and suffixes:

- [x] [`removeprefix()`](https://docs.python.org/3.9/library/stdtypes.html#str.removeprefix)
- [x] [`removesuffix()`](https://docs.python.org/3.9/library/stdtypes.html#str.removesuffix)

We should also include code examples of common usage.

**Comment by kana800** [comment]
Hi can I work on this?

**Comment by BethanyG** [comment]
@kana800 - Certainly!  🎉   

Below are some additional links to exercism docs.  Let I or @J08K know if you have any questions or issues!

- [Contributing to Exercism](https://exercism.org/contributing) |  [Help](https://exercism.org/docs/building/product)
- [What are those Weird Task Tags about?](https://exercism.org/docs/building/tasks)
- [Building Language Tracks: An Overview](https://exercism.org/docs/building/tracks) 
- [What are Concepts?](https://exercism.org/docs/building/tracks/concepts)
- [Concept Exercise Specifications](https://exercism.org/docs/building/product/concept-exercises)
- [Exercism Formatting and Style Guide](https://exercism.org/docs/building/markdown/style-guide)
- [Exercism Markdown Specification](https://exercism.org/docs/building/markdown/markdown)

**Comment by BethanyG** [comment]
@kana800, 

No apologies needed!  😄  - and thank you for your excellent questions.



> In `little-sister-vocab` [concept](https://github.com/exercism/python/tree/main/exercises/concept/little-sisters-vocab).
> 
> 1. Do I need to mention about `removeprefix ` and `removesuffix` in [introduction.md](https://github.com/exercism/python/blob/main/exercises/concept/little-sisters-vocab/.docs/introduction.md), [hints.md](https://github.com/exercism/python/blob/main/exercises/concept/little-sisters-vocab/.docs/hints.md) or just in [hints.md ](https://github.com/exercism/python/blob/main/exercises/concept/little-sisters-vocab/.docs/hints.md) ?.
> 2. Also only _**remove a suffix from a word**_ is mentioned in the `little-sister-vocab` concept.  Do I need to include about the `removesuffix()` method?
> 3. Do I need to change the `.meta/exemplar.py` file as well ?

Since these two methods are `Python  3.9`, and we (currently) only support `Python 3.8`, we should leave them out of the documents for the exercises proper for now.  -- so no changes to any of the files you mention above.

 But having this issue, and the changes in the `about.md` files for the  related concept documents will be a reminder to update these exercises when we do move to Python 3.9 in the future.


> In **[concepts/strings-methods/about.md](https://github.com/exercism/python/blob/main/concepts/string-methods/about.md)**, I can do a simple introduction of the new concepts of
> 
> * `removeprefix()`
> * `removesuffix()`
>   I dont see the point of mentioning above methods in [_about.md in strings_](https://github.com/exercism/python/blob/main/concepts/strings/about.md), If you want to let me know!

As I look at the documents once again, I agree - there is no need to mention these in the `strings`  `about.md` document.  


So I think the place to do the work would indeed be **[concepts/strings-methods/about.md](https://github.com/exercism/python/blob/main/concepts/string-methods/about.md)**,  perhaps under a heading or sub-heading that says something like "Introduced in Python 3.9:" or "Newly added in Python 3.9"?   Or some note.  But I will leave that to your discretion.  😄 

Thanks again for working on this.
