### ISSUE TITLE
[Log-levels]: Add Formal Docstrings to exemplar.py and stub files

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#2642]
For `log-levels` (Enums concept), we need to add proper docstrings to both the [stub file](https://github.com/exercism/python/blob/main/exercises/concept/log-levels/enums.py) and the [`exemplar.py`](https://github.com/exercism/python/blob/main/exercises/concept/log-levels/.meta/exemplar.py).

Example docstrings can be found [here](https://github.com/exercism/python/blob/main/exercises/concept/meltdown-mitigation/conditionals.py).  Docstrings should conform to [PEP257](https://www.python.org/dev/peps/pep-0257/), and be denoted with triple `"""`.

**Please do not use type annotations.**

**Comment by BethanyG** [comment]
@tigerBoss101  -- our sincere apologies!  We missed your note, and this was fixed by someone else.  😞    

Closed by #2730.

**Comment by tigerBoss101** [comment]
@BethanyG I see! Don't worry, it's all fine!
