### ISSUE TITLE
[Guido's Gorgeous Lasagna] instructions.md showing different var names

### ISSUE THREAD

**Issue by goatthinking** [exercism/python#2647]
In the instruction page for "Guido's Gorgeous Lasagna" concept exercise a variable has two different names within the document.

When instructing on how to make the function it says to use: `elapsed_bake_time`
* https://github.com/exercism/python/blob/efc213ac959a76e4f204214ffb98e185227960ff/exercises/concept/guidos-gorgeous-lasagna/.docs/instructions.md?plain=1#L38

However in the next section it where it has you add documentation it uses: `actual_bake_time`
* https://github.com/exercism/python/blob/efc213ac959a76e4f204214ffb98e185227960ff/exercises/concept/guidos-gorgeous-lasagna/.docs/instructions.md?plain=1#L51

Suggest renaming one so that they match.

**Comment by BethanyG** [comment]
@goatthinking -- thanks for the catch!  We've fixed this in #2651.
