### ISSUE TITLE
[New Exercises] using the input() function

### ISSUE THREAD

**Issue by szabgab** [exercism/python#2702]
People coming from a GUI-only background will have a lot of fun getting used to the command-line. IMHO it would be a good idea to have them practice. I'd be happy to contribute one or more of my super-simple exercises:

https://code-maven.com/slides/python/exercise-rectangle
https://code-maven.com/slides/python/exercise-calculator
https://code-maven.com/slides/python/exercise-age-limit
https://code-maven.com/slides/python/exercise-what-is-this-language

**Comment by BethanyG** [comment]
Hi @szabgab  -- for `input()` I disagree. There is very little use for `input()` in the vast majority of production Python code.  There are some corner cases where it is useful - but for a majority of cases, it is something that may be helpful to new programmers, but is really not helpful for someone looking to be fluent in core Python.

In addition to that, due to the nature of our track structures and test runners (_tooling runs in isolated docker containers_), an interactive Python session is out of the question.  So tests for something like this would be very contrived, and it's questionable that a student would get much _Python_  benefit -- beyond how to struggle with accepting input from `stdin` -- for which an exercise on [`sys.argv`](https://docs.python.org/3/library/sys.html#sys.argv) or  [`Argparse`](https://docs.python.org/3/library/argparse.html), or  even one on [`click`](https://click.palletsprojects.com/en/8.0.x/) would be a better candidate.

**Comment by BethanyG** [comment]
@J08K  -- your thoughts on this?  Would figuring out an exercise on `input()` be useful you think?  Open to discussion here, if there is a use-case I am forgetting or ignoring.  😄

**Comment by J08K** [comment]
Heya, thank you @BethanyG for tagging me in this! So, about `input()` I have 2 points:
 1. Exercism is (to my knowledge) not interested in `stdin` and `stdout` types of exercises (`input()` falls under `stdin`). We want to teach people programming, automation and just general ways to deal with given data. The kind of problems we teach are problems that _would_ theoretically deal with the user in an _indirect_ way.
 2. Secondly, I do not think it is possible, as of this moment, to get `stdin` from students. I tried getting `stdin` using `input()` and got the following error from pytest: 
![image](https://user-images.githubusercontent.com/48634934/139497135-0e350aad-69fc-478e-8c58-b0bfe1ad5c92.png) ... This by itself is only an error from pytest, and we could possibly fix it, but there would also be need for some changes to the website itself.

Yes, we could possibly emulate the issue that I proposed in point 2, but that would require a lot of research for something that is pretty trivial to understand.

I want to clarify that I do not dislike the idea. If we _would_ end up dealing with issue 2, I do believe it is still against the nature of Exercism.

Lovely issue though, actually something worth thinking about. Thanks

**Comment by szabgab** [comment]
I am trying to understand, where do students normally run their code. Because I run it on my own computer natively, not inside any container. In that setting the user would just run the `python some_code.py` that would ask for the input. I can put together a test for this and let you check it on whatever system you have.

**Comment by szabgab** [comment]
And for the reason, when I teach python (or any other language) I like to to teach students some way they can interact with the program. That, I feel, makes a much more fun experience as they can make useful little things after an hour of learning.

**Comment by J08K** [comment]
So @szabgab, code is tested in two ways on Exercism. You can write your solutions locally on your own machine using the CLI. It is also possible to do it via the website directly, which a lot of our students are currently doing. Either of these two options will require the `test-runner` to run the tests on your code and let the tests pass.

The `test-runner` is inside a `docker container` on an AWS server. To avoid wasting recourses these containers `time-out` after 3 seconds or so: AKA tests have failed, to avoid solutions with long runtime and infinite loops. 

Establishing a connection with that `docker container` will probably be difficult to build and will require us to do a major change to how we run things on Exercism. Also, asking input from a student will require the process to be halted, that means the `test-runner` will have to wait on that input. 

About "some way they can interact with the program", we try to do that with the code itself. Our new _reputation_ system on V3 tries to reward the student when they pass all the tests. We want them to be happy when all the lights go green and that they can finally say they finished it. When they know how to code a problem some students might think to implement a program itself on their own machine.

Exercism is not about using the `command line interface` but it's about solving problems and getting rewarded for solving them. Using `input()` as a concept will require us to also teach them a little bit about the `CLI` itself, which is not _technically_ what we want to teach. It is a useful skill to have, yes, but not one that is specifically tailored for our track, I think.

Hope this clarifies a bit.

**Comment by szabgab** [comment]
So if I understand the problem is not with the automated tests. The problem is letting the user run their program that expects interaction. People who use the command-line tool of Exercism to download and submit the code will have no problem.

Such exercises could explicitly say that they (currently) are only supported for people working on their own computer. For an even better UX, this could be a configuration parameter and the UI could disable the "edit" button, but that would not be necessary.

**Comment by BethanyG** [comment]
As both @J08K and I have stated, the "problem" is that interaction on the command line for something like `input()` is not the intended purpose for exercism exercises.  At best, it teaches a specific _proficiency_, **not** _fluency_ in Python.  It also has limited value to students beyond the beginning programming level.  As such, it is not a great return on effort for this track at this time.

I brought this interactivity/input issue up to a group of fellow maintainers earlier today for discussion -- and I think the general agreement was that if we were to do something "interactive", it would likely be a tutorial or interactive lesson using embedded REPLs -- which frankly, is a much better environment than our CLI would be for interaction and feedback.  Perhaps as a step for after students complete "Hello World", or as a `learn to program` track or pre-course -- or even as part of a debugging exercise (_with `pdb`, in Python's case_) -- but it probably wouldn't be through having students write a program that uses `input()`.

And while we do have a (_very few -- I think 3 at this point_) set of exercises on the Python track for which we cannot run online tests, we are not interested in adding to that count right now.  We'd rather keep the CLI and website experiences as in sync content-wise as we can make them.

So while the issue of interactivity **is** an interesting one, it just doesn't quite work with using `input()`.

**Comment by szabgab** [comment]
OK, I am closing this issue.
