### ISSUE TITLE
Investigate automated test suite generation based on JSON 

### ISSUE THREAD

**Issue by behrtam** [exercism/python#271]
Shouldn't be that complicated to write an automated test suite generator which uses the `*.json` file from the `x-common` repo. This could make the initial work for implementing new exercises easier.

See https://github.com/exercism/todo/issues/8

**Comment by kytrinyx** [comment]
The tricky thing is that the format isn't necessarily consistent yet (and we don't know if it should be). But there might be a small handful of formats, which would definitely help.

**Comment by behrtam** [comment]
The inconsistent format should be a thing of the past: https://github.com/exercism/x-common/pull/602
