### ISSUE TITLE
[My Little Sisters Essay] Parameter order

### ISSUE THREAD

**Issue by mathstrains21** [exercism/python#2712]
On my little sisters essay, the parameter naming order for `replace_word_choice()` is inconsistent.

The template has:
```py
def replace_word_choice(..., old_word, new_word):
    """
    ...
    :param new_word: str replacement word
    :param old_word: str word to replace
    ...
    """
    ...
```
While the exemplar solution is:
```py
def replace_word_choice(..., new_word, old_word):
    """
    :param new_word: str replacement word
    :param old_word: str word to replace
    """
    ...
```
The template is clearly correct in the function definition, while all of the other 3 orders are wrong.

I'd like to fix this if possible!

**Comment by IsaacG** [comment]
> I'd like to fix this if possible!

Would you like to submit a PR for this? Or would you like this to be fixed by anyone, in which case I can submit a PR?

**Comment by mathstrains21** [comment]
> > I'd like to fix this if possible!
> 
> Would you like to submit a PR for this? Or would you like this to be fixed by anyone, in which case I can submit a PR?

I'd like to fix this

**Comment by IsaacG** [comment]
Feel free to submit a PR.

**Comment by mathstrains21** [comment]
👍 will submit one later today!
