### ISSUE TITLE
Sorting of Published Solutions

### ISSUE THREAD

**Issue by shumashv1** [exercism/python#2718]
There should be more than just looking for some unknown user's solution.  I have no clue how the solutions are sorted now, but there should be options to sort on "newest to oldest", "oldest to newest", "date range", "alphabetic by user", etc.

**Comment by J08K** [comment]
Hi there @shumashv1,
I am assuming that you are currently talking about the `community solutions` page on every exercise, correct?

Even though I do agree with you, and that there should be a way of sorting things a little different, that is not up to the `Python track`. This is an _issue_ on all community solutions on all tracks. 

Please have a look in the main [Exercism Repo](https://github.com/exercism/exercism/issues), **but** please check out [this reply](https://github.com/exercism/exercism/issues/5616#issuecomment-916720899) from **iHiD** on the same issue. TLDR: They are thinking of adding this feature in the future. The issue has been reported.

You could leave a comment on [the issue](https://github.com/exercism/exercism/issues/5616), if you want. 

Anyway, have a nice day! I will be closing this.
