### ISSUE TITLE
Tools.md doc is not published to the website

### ISSUE THREAD

**Issue by IsaacG** [exercism/python#2721]
@BethanyG did some major rework of the https://github.com/exercism/python/blob/main/docs/TOOLS.md file in https://github.com/exercism/python/pull/2611/files

However, while the [tests](https://exercism.org/docs/tracks/python/tests) page shows up on the website, the tools page does not. I believe that's due to the tools page lacking an entry in https://github.com/exercism/python/blob/main/docs/config.json

The docs repo has 7 markdown files. The config has 4 entries. At least one, if not three, of those files should probably be added.

**Comment by IsaacG** [comment]
Side note: the MD files link locally using names like `[TOOLS](./TOOLS.md)` which works when renders on Github but generates invalid links when displayed on the website.

**Comment by BethanyG** [comment]
It was actually @J08K who did that massive amount of work.  I did the CONTRIBUTING and READMEs.  😄 
Let's get the links logged in a separate issue and corrected before we PR anything to show on the site.
