### ISSUE TITLE
[Twelve Days]: Odd formatting of data structures in tests leads to confusion

### ISSUE THREAD

**Issue by mohmad-null** [exercism/python#2772]
The 12 days exercise:
https://exercism.org/tracks/python/exercises/twelve-days

Problems:

* No instructions for what start_verse and end_verse are meant to mean / relate to. I can guess, but I shouldn't have to guess.

* The tests look like:
```
        expected = [
            "On the third day of Christmas my true love gave to me: "
            "three French Hens, "
            "two Turtle Doves, "
            "and a Partridge in a Pear Tree."
        ]
```
Chances are reading that if you're not familiar with the tests you think you've got 4 strings in a list. Really it's one string in a list but depicted exactly how most people would depict the former. Most people (especially newer people!) won't notice the missing commas at the end of the lines **outside** the brackets because the human mind is expecting there to be commas there.

If you want multi-line stuff like that, do it in a way that's not convention for multi-item lists, or put a comment in there to spell out to the user that the code isn't doing what they would normally expect it to do.

**Comment by BethanyG** [comment]
Hi @mohmad-null 👋🏽 

Thanks for bringing this up.  I agree:  if you are unfamiliar with [implicit line joining in python](https://docs.python.org/3/reference/lexical_analysis.html#implicit-line-joining) and how the [Black code formatter](https://black.readthedocs.io/en/stable/) formats data structures, it can be confusing to read the test files, and your brain might fill in commas where there aren't any.

Two point on this:

1.  It **is** convention in Python to format multi-line data structures in this way, though it can trip the unwary.  But I would argue it is a good thing to get used to -- I know that Google for one encourages implicit line joining in its [Python style guide](https://google.github.io/styleguide/pyguide.html).
2. These tests are both auto-generated and auto-formatted via Black, so commenting them is a bit difficult, but we'll give it a go and see if we can get that done inside the JinJa2 template.

**Comment by mohmad-null** [comment]
> It is convention in Python to format multi-line data structures in this way, though it can trip the unwary. But I would argue it is a good thing to get used to -- I know that Google for one encourages implicit line joining in its Python style guide.

@BethanyG - Mayhaps, but that doesn't mean it (implicit line joining of strings) is a good idea. :-)
It's certainly not something I've come across often in my 10+ years of Python, and the infrequency it's used will make it all the harder for folks to retain knowledge of it (I'd forgotten). There's also the fact that almost everyone (non-programmers included) will have decades of experience of expecting commas at the end of these sorts of sentences.

So I'd suggest it's definitely something that should **not** be encouraged.

I can easily envision implicit-line-joining of strings being responsible for an entire extra class of otherwise avoidable bugs.

**Comment by BethanyG** [comment]
> Mayhaps, but that doesn't mean it (implicit line joining of strings) is a good idea. :-)

Maybe -- maybe not.  ;-)  As with most things, context, project, and team matter.  

..but the the docs definitely go over it, and present it as normal.  Here's the string bit in the tutorial:

![image](https://user-images.githubusercontent.com/5923094/143502775-71bd9b5e-e6a3-40ff-846d-a35358efe99a.png)


I took a look at the JinJa template for the tests for this exercise.  It uses a macro to break up the string, and formats the result using Black (_all our templated test files use Black as a formatter_). 

When I get some time, I'll run a test to see if the outcome is different if we don't break the string.  I suspect that the string was broken up _because_ Black made things more confusing with the way it formatted.
