### ISSUE TITLE
Prime Factors solution already given (not by me)

### ISSUE THREAD

**Issue by googlymog** [exercism/python#2796]
Hello,

(I looked for a similar issue in exercism/python and exercism/exercism before posting). I tried doing the Prime Factors exercise and I believe a solution was already saved.  I don't remember populating this solution and it doesn't look like the point of the exercise is refactoring.  Additionally, the code passed all the tests without needing to change anything.  The code present when I started the exercise was:

```python
# def factors(value):
#     pass
def factors(value):
    factors = []
    divisor = 2
    while value > 1:
        while value % divisor == 0:
            factors.append(divisor)
            value /= divisor

        divisor += 1

    return factors
```
This is the first time this has happened to me.  It is always possible that I sleep-coded or just forgot I did this previously but I don't think I would choose to solve the problem with a nested while loop and I didn't realize you can do /= like you can do +=.  The only thing giving me pause is the answer is in my account.  If this is not suitable for exercism/python or as an issue in general then I can close it.  Thank you!

**Comment by BethanyG** [comment]
@googlymog  - Thank you very much for filing this issue!  We've been doing some cleanup on our practice exercises, and accidentally left an example solution in the "stub" file for this exercise.  😱 &nbsp; -- not the kind of thing we like to do.

We'll push a fix shortly.  😄
