### ISSUE TITLE
[Currency Exchange] Confusing instructions and tasks

### ISSUE THREAD

**Issue by mohmad-null** [exercism/python#2804]
I must admit when I got to Currency Exchange I was somewhat confused as to what was required on the later tasks.

Now I've just had a friend who I'm mentoring get road-blocked at Task 5. And because of the complicated nature of the requirements, I can't just quickly look at them go "yep this is what's wanted", then tell my friend what they need to do.

My friend's (unsolicited) feedback that prompted this ticket:
> this is frustrating **** :(
> most frustrating because it is thought for people who are learning

For this I'd like to suggest:
* Much much simpler equations. There's no need for anything particularly advanced here.
* Spell out exactly what is required much more clearly
* Break down the equations so it's clear what the components are.
* A problem with a modulo (modulo's are taught but not required in the results).

**Comment by BethanyG** [comment]
Hi @mohmad-null  

Thanks for giving feedback on this exercise & opening an issue.  This echos what is stated in issue #2621, so I am going to link and close this.  I think it's more helpful to have the feedback all in one place, as we determine next steps for this exercise.  Thanks!
