### ISSUE TITLE
[Guido's Gorgeous Lasagna]: Tests or Instructions Might be Wrong

### ISSUE THREAD

**Issue by formidablae** [exercism/python#2811]
The code doesn't reflect the instructions.

**Comment by BethanyG** [comment]
Hi @formidablae - 

Could you please cite and screengrab which of the instructions are not matched with the code?  On a scan of what we currently have in the repo, I am not seeing a mis-match.  That **doesn't** mean there isn't one -- just that I can't find it.  

Many thanks!

**Comment by formidablae** [comment]
Please see [this comment](https://github.com/exercism/python/pull/2812#issuecomment-983028564)!

**Comment by BethanyG** [comment]
Are you sure you have the most recent update of this exercise, and that you've named your parameters correctly?  Remember, parameters are _positional_ by default in python -- so their names are not as important as their _values_, and what you do with them.

When I run the current [Guido's Gorgeous Lasagna `exemplar.py`](https://github.com/exercism/python/blob/main/exercises/concept/guidos-gorgeous-lasagna/.meta/exemplar.py) against the current [Guido's Gorgeous Lasagna `lasagna_test.py`](https://github.com/exercism/python/blob/main/exercises/concept/guidos-gorgeous-lasagna/lasagna_test.py), everything passes.  

6 tests fail if I make the change you suggest to the test file.  The same 6 tests also fail for the "swapped" [solution example](https://exercism.org/tracks/python/exercises/guidos-gorgeous-lasagna/solutions/exercista) you linked to in your PR. 

I've had my co-maintainer @J08K  also take a look at this.  Unfortunately, neither one of us can reproduce your issue with the current exercise, and the current tests.

**Comment by formidablae** [comment]
My mistake. Parameter order is forced by the exercise and tested that way. Sorry for the confusion. You can close this as solved.
