### ISSUE TITLE
[Introduction] Wrong output presented for __doc__attribute of number_to_the_power_of

### ISSUE THREAD

**Issue by mlistewnik** [exercism/python#2833]
Hi, 
I was reading the Introduction article about Python ([link](https://exercism.org/tracks/python/concepts/basics)) and found a code snippet that I tested in my IDLE Shell (Python 3.8.10).
[Markdown permalink:](https://github.com/exercism/python/blob/main/concepts/basics/introduction.md?plain=1#L181-183)

```

def number_to_the_power_of(number_one, number_two):
    """Raise a number to an arbitrary power.
    
    :param number_one: int the base number.
    :param number_two: int the power to raise the base number to.
    :return: int - number raised to power of second number
    
    Takes number_one and raises it to the power of number_two, returning the result.
    """

    return number_one ** number_two
```
And then:
`print(number_to_the_power_of.__doc__)`

What I get is:
```
Raise a number to an arbitrary power.
    
    :param number_one: int the base number.
    :param number_two: int the power to raise the base number to.
    :return: int - number raised to power of second number
    
    Takes number_one and raises it to the power of number_two, returning the result.
```

But in lines 182-184 there is a different output ([link](https://github.com/exercism/python/blob/7171bdf19d850b09b5a97655be6c2aeaec39da40/concepts/basics/introduction.md?plain=1#L182-L184)):

```
Returns float or int.
       Takes number_one and raises it to the power of number_two, returning the result.
```

Is it correct?

**Comment by BethanyG** [comment]
Closing as fixed in #2837.  Thanks again, @mlistewnik! 💛
