### ISSUE TITLE
Misleading reference to supporting module in README.md of concept exercise "Cater Waiter"

### ISSUE THREAD

**Issue by fish-food89** [exercism/python#2845]
The README of the exercise instructs readers to use the file `categories.py`, but it is infact [`sets_categories_data.py`](https://github.com/exercism/python/blob/847f612226e1d5f3ff71516a1ba94e965ac410e7/exercises/concept/cater-waiter/sets_categories_data.py).

The misleading references can be found on these lines:
- https://github.com/exercism/python/blob/847f612226e1d5f3ff71516a1ba94e965ac410e7/exercises/concept/cater-waiter/.docs/instructions.md?plain=1#L27
- https://github.com/exercism/python/blob/847f612226e1d5f3ff71516a1ba94e965ac410e7/exercises/concept/cater-waiter/.docs/instructions.md?plain=1#L30
- https://github.com/exercism/python/blob/847f612226e1d5f3ff71516a1ba94e965ac410e7/exercises/concept/cater-waiter/.docs/instructions.md?plain=1#L47
- https://github.com/exercism/python/blob/847f612226e1d5f3ff71516a1ba94e965ac410e7/exercises/concept/cater-waiter/.docs/instructions.md?plain=1#L50
- https://github.com/exercism/python/blob/847f612226e1d5f3ff71516a1ba94e965ac410e7/exercises/concept/cater-waiter/.docs/instructions.md?plain=1#L70
- https://github.com/exercism/python/blob/847f612226e1d5f3ff71516a1ba94e965ac410e7/exercises/concept/cater-waiter/.docs/instructions.md?plain=1#L73
- https://github.com/exercism/python/blob/847f612226e1d5f3ff71516a1ba94e965ac410e7/exercises/concept/cater-waiter/.docs/instructions.md?plain=1#L137

**Comment by BethanyG** [comment]
Hi @fish-food89!  All I can say is .... 🤦🏽‍♀️ .  Would you care to submit a PR?? 💜  😄

**Comment by fish-food89** [comment]
Sure thing. I can create a PR to solve this.
