### ISSUE TITLE
[Inventory Management] Hints are missing

### ISSUE THREAD

**Issue by zepam** [exercism/python#2850]
Hints in the instructions return just the title of the task rather than the hints that are listed in the docs.

**Comment by zepam** [comment]
![image](https://user-images.githubusercontent.com/12726758/149081535-fdce358b-c3a9-4025-bded-2c8194662c33.png)
I'd fix it myself if I could figure out how to do it.

**Comment by BethanyG** [comment]
@zepam  -- Thank you for logging this!  We've had this issue before with a few other exercises.  I think its a Markdown parsing/syntax issue.  Let me take a look at other exercises that had this issue.   If there's a fix, I'll note it here and would be delighted if you wanted to then submit a PR.  😄

**Comment by BethanyG** [comment]
This is indeed a parsing issue.  More specifically - a title mis-match issue.  🤦🏽‍♀️   When the site parses the `hints.md` file, it matches `hint` content based on the **task** title in `instructions.md`.  If the two titles don't match, the `hint` content doesn't make it to the right place.  😢 

So in this case, we'll need to make sure that the **hint** titles are the same as the ones in the `instructions.md` file.  Things under the `General` heading in `hints.md` can stay the same.

[Inventory Management `hints.md`](https://github.com/exercism/python/blob/main/exercises/concept/inventory-management/.docs/hints.md)
[Inventory Management `instructions.md`](https://github.com/exercism/python/blob/main/exercises/concept/inventory-management/.docs/instructions.md)

**Comment by BethanyG** [comment]
Closed by #2854.  Many thanks, @zepam!

![image](https://user-images.githubusercontent.com/5923094/149300989-edfc67bb-49ba-4f49-b221-d0a6919589f5.png)

**Comment by kotp** [comment]
Very nice.  Came over from the PR, and this now looks very nice.

Definitely thank you @zepam !!
