### ISSUE TITLE
[Meltdown Mitigation] minor criticism -- always use units of measurement

### ISSUE THREAD

**Issue by chuck-alt-delete** [exercism/python#2857]
Thanks for your work on exercism!

The `temperature` parameter is simply a number, and there is logic pertaining to whether it is above or below 800. 800 what? Degrees Fahrenheit? Degrees Celsius? Kelvin? Parameter descriptions should always include proper units of measurement. It seems like a small point, but ambiguous units can [be very costly](https://www.latimes.com/archives/la-xpm-1999-oct-01-mn-17288-story.html).

**Comment by BethanyG** [comment]
Hi @chuck-alt-delete 👋🏽 

Thanks for filing this issue.  😄   Happy for you to PR what you think might be appropriate.  Keep in mind that this is a very **very** simplified exercise, and leaves out much of the calculations for [criticality](https://www.nuclear-power.com/nuclear-power/reactor-physics/nuclear-fission-chain-reaction/reactor-criticality/).  But we probably should specify units of temperature.

**Comment by BethanyG** [comment]
@chuck-alt-delete  - are you interested in PR-ing a unit of measure change?  Please let me know -- thanks!

**Comment by chuck-alt-delete** [comment]
I can’t commit to that (pun intended). I’m pretty swamped at work right this week. Maybe later, though!

**Comment by BethanyG** [comment]
Closing.  See #2918 & #2930.
