### ISSUE TITLE
[Conditionals] Correct typo in config

### ISSUE THREAD

**Issue by Timo4B** [exercism/python#2901]
"," is redundant and at the wrong place I think.
concepts/conditionals/.meta/config.json

**Comment by BethanyG** [comment]
As stated in the closed PR:  I disagree. I think the comma was in the correct _place_, but the space in front of it needed to go.

But this blurb also needs to be re-written slightly in light of the introduction of structural pattern matching in Python 3.10, so I think we'll leave it as-is until that re-write can be logged  as an issue and the work on that done.
