### ISSUE TITLE
Incorrect tests in book_store.py

### ISSUE THREAD

**Issue by tamireinhorn** [exercism/python#2910]
Despite the README from the exercise being the same as the C# track, for example, the tests all expect the return to be an int, and not a float. Therefore, even for the simplest test 'test_only_a_single_book', the test expectes 800, not 8! Either the tests should go have their results changed or the readme should be different on this track.

**Comment by kotp** [comment]
The base unit is 1 cent, and so 800 is an appropriate price for a book.
