### ISSUE TITLE
[Meltdown-Mitigation] Expected and actual were swapped in self.assertEqual

### ISSUE THREAD

**Issue by Metallifax** [exercism/python#2934]
I'm pretty new to contributing in general, but I'm excited to have the chance to work on this awesome platform with you all and I hope I can be of some use. I remember working on the Meltdown Mitigation problem a while back while using PyCharm and the expected and actual results were reversed in the testing tool output, so the value that is returned by the FUT would be the expected value and the actual would be expected, you get the picture. 

![expected-actual1](https://user-images.githubusercontent.com/61431322/154445224-c6615b54-585b-4910-9ca1-8c06fad73869.png)

Just a quick swap around of the expected and actual_result fixes it. 

![expected-actual2](https://user-images.githubusercontent.com/61431322/154445226-5aafd109-b346-4559-a6a9-baf2b1c5aca8.png)

I have a commit ready to go on my repo, I just didn't want to miss anything before creating a pull request. Let me know if there's anything I can do to get the ball rolling. 

Edit: I noticed after mulling over this a bit that all of the tests follow a similar pattern, so if this was intended, feel free to just close this unless you'd like someone to go through and change them one by one. Regards.

**Comment by kotp** [comment]
The [patch] looks good to me.

I would probably submit the PR for this concept exercise, and develop from there.  (It makes it easier to talk about the patch specifics as well if it is easily available to talk about.)

[patch]: https://github.com/Metallifax/python/commit/af0664b49c5404869ec2832030017f50db0889c8.patch

**Comment by kotp** [comment]
> you get the picture

Actually, I did get the picture, but that does not mean that I can read it easily.  It can be more accessible to copy and paste textual things, than to show a picture of that textual thing.  (A lot more accessible.)

**Comment by kotp** [comment]
Even though it may not be an accepted fix, (if it is not) at least it will be documented for the next person that sees it (and you have already done the Patch work anyway, so no lost time, consider it practice) it has value.

Thank you for the work done!

**Comment by BethanyG** [comment]
@Metallifax  -- please see comments in PR #2935.  Closing as won't fix.

**Comment by Metallifax** [comment]
@kotp As you said, any experience is good and I feel like I learned a lot about the process. It felt great to just work on code and go through the review process and see what happens, I also learned much more about the process in the repo as well. Cheers.
