### ISSUE TITLE
[Currency Exchange] - last exercises too complex

### ISSUE THREAD

**Issue by mohmad-null** [exercism/python#2946]
https://exercism.org/tracks/python/exercises/currency-exchange

The last two methods you have to create: `exchangeable_value` and `non_exchangeable_value` - are both far too complicated in their requirements.
I struggled to understand what was going on when I did them (I'm proficient at Python), and both of the friends I'm mentoring struggled as well, and we all three of us have at least a Masters in a STEM subject! I'm not bragging about our education there; I'm saying that if multiple people with advanced technical degrees struggle on a "learning" exercise, it's far too complicated for something that's meant to be teaching a basic concept.
When I look at it now a few months later, including my solution, I still have no idea what they're doing without spending a few minutes staring at them.

I would instead suggest it's worth demonstrating things like:
If you apply the following operators (* + -) to two ints, you get an int back, but apply `/` to two ints and you get a float back. That kind of thing.

**Comment by kotp** [comment]
>  apply / to two ints and you get a float back

I know you said "that kind of thing" but definitely not this thing.  Because it is not true.

```
>>> 4 / 2
2
>>> 4.0 / 2
2.0
```

**Comment by narenkeshav** [comment]
I concur. I found `exchangeable_value` to have a lack proper description in the final part.

**Comment by BethanyG** [comment]
@mohmad-null  -- since you also filed issue #2804, it was probably better to reopen that one instead of filing a new issue against the same exercise.

Consolidating related issues under #2951.  Closing this to reduce noise and focus on the redesign.

**Comment by mohmad-null** [comment]
> @mohmad-null -- since you also filed issue #2804, it was probably better to reopen that one instead of filing a new issue against the same exercise.
> 
> Consolidating related issues under #2951. Closing this to reduce noise and focus on the redesign.

Oh; I'd completely forgotten about that issue. I suppose that just re-enforces my point that about that particular exercise. :-)
