### ISSUE TITLE
[Practice Exercise: Hamming] Unnecessary test case

### ISSUE THREAD

**Issue by fish-food89** [exercism/python#2948]
The Hamming practice exercise has one test twice. Nothing harmful, but unnecessary.

The test cases [`test_disallow_right_empty_strand`](https://github.com/exercism/python/blob/6e11dfd03c6bb3167d706eb38c66820554e78106/exercises/practice/hamming/hamming_test.py#L47) and [`test_disallow_empty_second_strand`](https://github.com/exercism/python/blob/6e11dfd03c6bb3167d706eb38c66820554e78106/exercises/practice/hamming/hamming_test.py#L54) are identical in contents. Suggesting the removal of `test_disallow_right_empty_strand` as `test_disallow_empty_second_strand` is more in sync with its counter part case `test_disallow_empty_first_strand` in naming.

I can create a PR to resolve this issue if this gets a green light from a maintainer.

**Comment by kotp** [comment]
Double check that this does not need to be addressed in the source repository for practice exercises at https://github.com/exercism/problem-specifications

**Comment by fish-food89** [comment]
Acknowledged. I'll have a look into that.

**Comment by BethanyG** [comment]
@fish-food89 - Thanks for filing this.  Looks like a reimplemented test case from problem specifications was pulled by the template.  I'll set it to false and re-generate the tests.
