### ISSUE TITLE
[Ellen's Alien Game] should tests allow for health not to go below 0?

### ISSUE THREAD

**Issue by IsaacG** [exercism/python#2954]
My first solution for `hit()` did `self.health = max(0, self.health - 1)` ... and that failed the tests. Should the test fail if `hit()` doesn't reduce health below 0?

**Comment by IsaacG** [comment]
> Thoughts?

Health in games tends to be something that goes from a value above zero down to zero. Negative health values tend to not be valid in most games. In fact, `alien.hit()` when `alien.is_alive() == False` might even be expected to through an exception.

Testing for `in (0, -1)` would allow the students the freedom to implement it either way. Not calling `alien.hit()` on a dead alien would also make sense :)

> Would your solution be one that most students would try given this exercise?

I have no way of knowing :) Solutions which stop at zero would be rejected. Such solutions would not be submitted so it's hard to know if students are trying that.

**Comment by kotp** [comment]
On 22/02/26 09:00PM, Isaac Good wrote:
> Such solutions would not be submitted so it's hard to know if students
> are trying that.

Is this only true if they are submitted via the online editor?  Or does
Python allow the "normal" submit via the exercism cli?
