### ISSUE TITLE
[Little Sister's Vocabulary] exercise uses lists + other issues

### ISSUE THREAD

**Issue by mohmad-null** [exercism/python#2957]
https://exercism.org/tracks/python/exercises/little-sisters-vocab

```
def make_word_groups(vocab_words):
    """

    :param vocab_words: list of vocabulary words with a prefix.
    :return: str of prefix followed by vocabulary words with
             prefix applied, separated by ' :: '.

    This function takes a `vocab_words` list and returns a string
    with the prefix  and the words with prefix applied, separated
     by ' :: '.
    """
```

There are two problems here:

a) It requires the user to manipulate a list before you've introduced lists.

b) If I saw this in real-world code, it would flag my code-smell detector. We should be teaching people good code practices. The function definition should be:
`def make_word_groups(prefix, vocab_words)` - the prefix should be a separate parameter.
Although that would then complicate the solution (as loops haven't been taught yet), I guess get rid of the prefix entirely and just teach join.

**Comment by BethanyG** [comment]
Hi @mohmad-null 👋🏽 

> _a)  It requires the user to manipulate a list before you've introduced lists._

Please see the reasoning laid out here in closed issue #2588. As long as there are clear examples, it is not forbidden to add in an additional concept. I would also say that having `.join()` _unpack_ in iterable is not the same as having a student use `list.sort()` or `list.append()`. So we are not asking students to manipulate lists - only understand that `.join()` can process one and that `str.split()` returns one. 

>  _b)  If I saw this in real-world code, it would flag my code-smell detector. We should be teaching people good code practices._

I'm not sure how breaking down data in one form to return it in another is a "code smell".  Sometimes, separators are well-known and fixed.  This one is clearly stated in the task.  Dealing with how or why you would have a parameter for a variable separator or a fixed one (_or pulling one from a config file or any other permutation_) is out of scope for this exercise.

**Comment by mohmad-null** [comment]
I raise these issues because not only did I struggle with them (as a result of the instructions not being entirely clear and the code-smell), but also because a mentee struggled too.

> As long as there are clear examples, it is not forbidden to add in an additional concept.
It should be. The purpose of these exercises is to teach, and to do so effectively. That means not putting in other concepts that are not pertinent; that will simply add confusion to the exercise. Teach one thing and teach it well.


>  I'd also argue that weird input and output data is indeed a "real world" thing
Indubitably, but so is crime. That doesn't mean we should expose people to it if we can avoid it. And absolutely definitely not during a teaching exercise.

Yes there are countless real-world examples where you have to pull data out of itself and then munge it back together again (practically my day job). I'm not an academic so I can't expound on the theory, but the current "use the first value to edit all the other values but not the first value" feels onerous. The fact that it's not split out before the function definition feels code-smelly given this is a entirely contrived example rather than real data..

**Comment by BethanyG** [comment]
@mohmad-null   I think I am going to stop my participation in this discussion here, as I don't think we are going to come to an agreement.  I've asked several other maintainers to take a look, and weigh in on what they think of this exercise, its "code smells", and where it's placed in the exercise tree.

Meanwhile, I'd encourage you to submit a PR with changes you feel improve this exercise, or teach the concept in a better fashion from your perspective.
