### ISSUE TITLE
[Two Buckets] Potentially incorrect test case

### ISSUE THREAD

**Issue by ezabus** [exercism/python#2984]
Hi team!

I am not sure, but I think the following test case is not correct

https://github.com/exercism/python/blob/c0a63e5e0de0d2f50f77b558d99158c6ea51f2d5/exercises/practice/two-bucket/two_bucket_test.py#L19

There is a solution with less than 8 actions:
1. Initial step. Fill the second bucket: [0/3], [5,5]
2. Pour from second to first: [3/3], [2,5]
3. Empty the second: [3/3], [0/5]
4. Pour from first to second: [0/3], [3/5]
5. Fill the first: [3/3], [3/5]
6. Pour from first to second [1/3], [3/5]

Please let me know if i am missing something.

**Comment by IsaacG** [comment]
You're not wrong. But, from the instructions:

> That means, when starting with the larger bucket full, you are NOT allowed at any point to have the smaller bucket full and the larger bucket empty (aka, the opposite starting point); that would defeat the purpose of comparing both approaches!

Your step 3 violates this requirement.

**Comment by ezabus** [comment]
Oh, I see. Sorry for spending your time.
