### ISSUE TITLE
[Darts]: Hints File Does Not Display Nested Bullets or RefLinks

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#2998]
The `hints` file for Darts (available [here](https://github.com/exercism/python/blob/main/exercises/practice/darts/.docs/hints.md)) has both nested bullets and markdown reflinks.  These display fine on GH:

![2022-04-01_09-53-18](https://user-images.githubusercontent.com/5923094/161329358-9a17f54a-15fd-4407-9b7d-77f0a6b613de.png)

The same bullets and links are dropped when the file is displayed on the website:

![2022-04-01_09-51-37](https://user-images.githubusercontent.com/5923094/161329343-6265eca3-a250-4e10-9c48-fe396b19aae5.png)

This may or may not be easily fixed.  If the decision is to wait (or not) fix, then PR #2997 should be reviewed and merged.

**Comment by BethanyG** [comment]
@ErikSchierboom -- I went with this issue.  If it's not an easy fix, just ping me, and I can push the reformatted file.  Since this is our very first practice exercise hint file, I am not a a big hurry, since I don't think its going to really be quickly discoverable.

**Comment by ErikSchierboom** [comment]
@BethanyG I've just checked, and reference links in top-level list items work. The issue is likely with the nested list items.

**Comment by BethanyG** [comment]
Good to know!  I'll go back to the reflinks, and un-nest the bullets for now.  Thanks for checking.  😄

**Comment by ErikSchierboom** [comment]
Sure. I'll see if I can fix the nesting.

**Comment by BethanyG** [comment]
Noting https://github.com/exercism/website/pull/2616.  Once that's merged, this should resolve.  😄
