### ISSUE TITLE
[Guidos Gorgeous Lasagna] Correction to Instructions

### ISSUE THREAD

**Issue by jalriols** [exercism/python#3003]
The first step of the exercise consist on defining a constant. In the instructions there is an example where the the constant is called as follows:
```python
>>> lasagna.EXPECTED_BAKE_TIME
```

I believe that the constant was probably an atribute from the lasagna class in an earlier version of the problem, and now it just makes it difficult to understand what "lasagna" means in the exercise.

**Comment by BethanyG** [comment]
Hi @jalriols 👋🏽 

Thanks for submitting this issue.

While it may be confusing (_and we may need to make the example clearer by explicitly showing the import_), it is not wrong here to say `lasagna. EXPECTE_BAKE_TIME`.  It wasn't left over from a `lasagna` **_class_**, rather `lasagna` is the name of the exercise **_file/module_**.

 The convention in Python is to use  **`<module name>`.`<object name>`** if you are referring to a variable, constant, or class from an imported file/module - which you would be, if you were accessing the EXPECTED_BAKE_TIME constant from the `lasagna py` file in a  Python terminal (_which is what those `>>>` signify in the code example_)

You could also do `from lasagna import EXPECTED_BAKE_TIME` to avoid having to reference `lasagna`, but we chose not to go over that here.

I also left this note on the PR -- so if you'd like to add an import statement to the code example as clarification, I'd happily review and accept it -- but the current usage of `lasagna.EXPECTED_BAKE_TIME` is correct.

**Comment by jalriols** [comment]
Hi @BethanyG, thanks for your thorough explanation.

I think you expect me to modify the first example to look like this:
```python
>>> import lasagna
>>> lasagna.EXPECTED_BAKE_TIME
40
```

But then I think I should also add the _import_ for the rest of the functions to be consistent, like the example below:

```python
>>> from lasagna import bake_time_remaining
>>> bake_time_remaining(30)
10
```

Another option would be leaving only the first import, but calling all the functions with the complete name:

```python
>>> lasagna.bake_time_remaining(30)
10
```

What do you think?

**Comment by BethanyG** [comment]
Hi @jalriols, thanks for your thoughtful reply!  

Now that I am looking at it, I like the idea of adding the more specific import for the functions as well.  That gives two different examples of imports -- the whole file/module vs a specific function from it.

But as a learner, is that going to be confusing?  If not, then I say go with your top two examples above - and many thanks for filing the issue and doing the work!  😄
