### ISSUE TITLE
[Meetup] Descriptors for Week of Month  in Problem Statement Don't Match the Descriptors in the  Tests

### ISSUE THREAD

**Issue by ErnieWhite** [exercism/python#3005]
The descriptors for the week in the instructions.md do not match what is used in the unit test.  The best fix in my opinion would be to modify the instructions.md to match the unit test.  This would maintain the validity of existing submissions.

instructions.md:
    first, second, third, fourth, fifth

meetup_test.py
    1st, 2nd, 3rd, 4th, 5th

**Comment by ErnieWhite** [comment]
Hello @BethanyG 

I would like to take on the work.  I always enjoy learning something new.  On the surface this seems to be a fairly easy fix,  though that is rarely the case though.

**Comment by ErnieWhite** [comment]
Okay, the example file passes all 103 test.  That was the easy part, here is where I might need a little help. Do you want me to just create another pull request on it tagging this issue?

**Comment by BethanyG** [comment]
@ErnieWhite - _awesome!_

Did you edit the test generation template & regenerate the test files as well?  

If so -- **yes** -- please open a PR with the new template, the regenerated tests, and the updated example file, tagging this issue.  😄 

_Many thanks_
