### ISSUE TITLE
[Card Games] Test coverage for Task 6.

### ISSUE THREAD

**Issue by tsigma6** [exercism/python#3025]
The current test cases for Task 6 (for `def average_even_is_average_odd(hand)`) allows for `return card_average(hand) % 2 == 0` to pass all tests, however this is probably not the intention of this particular Task, and as written a counter example that should return `True` but returns `False` for this given solution would be `[1, 3, 5]`.

**Comment by BethanyG** [comment]
Hi @tsigma6 👋🏽 

Thanks for filing this issue!  Would you like to propose additional and/or different tests for task 6?  
We'd warmly welcome a PR/suggestions for it.  😄

**Comment by tsigma6** [comment]
I've added a pull request with a single additional test that should resolve it.
