### ISSUE TITLE
[Grep]: Unnecessary newline character at end of output

### ISSUE THREAD

**Issue by tobeannouncd** [exercism/python#3027]
After banging my head against the wall debugging my solution to [Grep](https://exercism.org/tracks/python/exercises/grep), I noticed that the tests assume that each line in the output ends with a newline character except when there are no matches. I have no clue why this the case, as there seems to be only one pattern that would generate output this way:

```
output_lines = [string_a, string_b, ...]
out = ""
for line in output_lines:
    out += line + "\n"
return out
```

Other exercises in the Python track don't seem to have this problem, and generally pass with the following pattern:

```
output_lines = [string_a, string_b, ...]
return "\n".join(output_lines)
```

Given that string methods are used quite frequently for formatting output in Exercism Python problems, I believe that the test suite should be updated to remove those trailing newline characters.

**Comment by BethanyG** [comment]
Closing this for now.  Will re-open if needed for discussing changes.
