### ISSUE TITLE
[Diffie Hellman]:  Test File Needs Reformatting so that the Test Runner Does Not Cut Off Test Code in the UI

### ISSUE THREAD

**Issue by joshgoebel** [exercism/python#3069]
Test 3
DiffieHellman > can calculate public key using private key

Under Code run all I see is:

```
p = 23
g = 5
private_key = 6
self.assertEqual(
    8,
```

**Comment by BethanyG** [comment]
Fixed in #3073 

![2022-06-03_05-50-17](https://user-images.githubusercontent.com/5923094/171857555-eaa464c7-a4ee-4f21-89e2-d31318a10636.png)

**Comment by joshgoebel** [comment]
Awesome. Thanks so much. 😎
