### ISSUE TITLE
[Sattelite] Insufficient tests

### ISSUE THREAD

**Issue by tamireinhorn** [exercism/python#3114]
This exercise presents an interesting challenge, specially after solving Binary Search Trees. However, for some reason, its trees do not use numerical values, and even the letter values do not seem to follow the usual alphabetical logic as far as I can see. Coupling that with the fact that of the 7 tests, only 2 are not exception verifications, I think the exercise could have more tests, derived from the trees in the Binary Search Trees exercise. I've even written them in my repo for solutions.

**Comment by BethanyG** [comment]
Hi @tamireinhorn,

That is correct -- you will want to update the `canonical-data.json` for the exercise.  😄 

You can find the specifications for the file under the [README -- Test Data](https://github.com/exercism/problem-specifications#test-data-canonical-datajson).  Any [valid UUID(v4)](https://en.wikipedia.org/wiki/Universally_unique_identifier) will work.  I often use this web-based [UUID Generator](https://www.uuidgenerator.net/) to generate the ids, but you can use any method, as long as they're valid UUID(v4). 

I ... _think_ that's all that is needed, but make sure to read through the linked README, as I may have forgotten something.

**Comment by tamireinhorn** [comment]
Here's the [PR](https://github.com/exercism/problem-specifications/pull/2058)

**Comment by BethanyG** [comment]
My apologies @tamireinhorn - I've been really swamped.  As soon as I get time to go back through the exercise, I will go ahead and add my review for your proposed changes.  Please bear with me.  😄

**Comment by tamireinhorn** [comment]
No worries, thanks for the update!

**Comment by BethanyG** [comment]
Closing this as there is an issue open in problem specifications.
