### ISSUE TITLE
[Improve Concept Docs]: TRACEBACKS - Add PDB section

### ISSUE THREAD

**Issue by bobahop** [exercism/python#3118]
If you have not yet contributed to concept documents, this issue will require some upfront reading to give you the needed background knowledge.  Additionally, we recommend reading the existing `about.md` docs [here](https://github.com/exercism/python/blob/main/concepts/functools/about.md), and an example of completed concept docs [here](https://github.com/exercism/python/tree/main/concepts/classes).

## ✅   Getting started

**`Please please read the docs before starting.`** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. 

**General Contributing Docs:**

- [Contributing to Exercism](https://exercism.org/docs/building) | [Exercism and GitHub](https://exercism.org/docs/building/github) | - [Contributor Pull Request Guide](https://exercism.org/docs/building/github/contributors-pull-request-guide)
- [What are those Weird Task Tags about?](https://exercism.org/docs/building/product/tasks)
- [Exercism Formatting and Style Guide](https://exercism.org/docs/building/markdown/style-guide)
- [Exercism Markdown Specification](https://exercism.org/docs/building/markdown/markdown)
- [Reputation](https://exercism.org/docs/using/product/reputation)  

**Documents on Language Tracks and Concepts:**

- [Building Language Tracks: An Overview](https://exercism.org/docs/building/tracks) 
- [What are Concepts?](https://exercism.org/docs/building/tracks/concepts)
- [Concept Specifications](https://exercism.org/docs/building/tracks/concepts) 

<br>

## 🙏🏽   Desired Improvements and Changes

Add section on [PDB](https://realpython.com/python-debugging-pdb/), either to #3059 before it's merged or to the [merged doc](https://github.com/exercism/python/tree/main/docs/TRACEBACKS.md) after the PR is approved and merged.
___________

# 🌟   Original Specifications

Below are the original specifications from the Concept issue.  Please use these as a guide in addition to the change list above.

Learn a little around error tracing tools such as [PDB](https://docs.python.org/3.9/library/pdb.html), and similar tools in common IDEs.

## 🎶  Implementation Notes

- Example code  should **only use syntax & concepts introduced within these docs or one of the prerequisite concept exercises or documents.** Where possible, please use REPL formatting, unless you are demonstrating pseudo code or a long code block.
  Please **do not use** syntax not previously covered in prerequisite topics or exercises.  Please also follow [PEP8](https://www.python.org/dev/peps/pep-0008/) guidelines.
- Our markdown and JSON files are checked against [prettier](https://prettier.io/) .  We recommend [setting prettier up locally](https://prettier.io/docs/en/install.html) and running it prior to submitting your PR  to avoid any CI errors.

<br>

##  🆘  Next Steps & Getting Help

1.  **`If you'd like to work on this issue, comment saying "I'd like to work on this"`** (_there is no real need to wait for a response, just go ahead, we'll assign you and put a `[claimed]` label on the issue_).
2. If you have any questions while implementing, please post the questions as comments in here, or contact one of the maintainers on our Slack channel.

**Comment by BethanyG** [comment]
@bobahop, please add the [appropriate tags](https://exercism.org/docs/building/product/tasks), so that this issue gets listed on the website.  It might also be helpful to add a **getting started** section, so that contributors have links to docs.   An example of that is [here](https://github.com/exercism/python/issues/3098) .  Thanks!

**Comment by meatball133** [comment]
The goal is to write a section in the tracebacks file on how to set up prettier and that you should not include syntax/concept in your solution which hasn't been covered in earlier concepts/exercises? Also that you should follow REPL?

**Comment by meatball133** [comment]
This is my first "big" pr for Exercism, I would appreciate all the feedback I can get.
