### ISSUE TITLE
[Improve Concept Docs]: Decorators

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#3120]
This issue describes desired additions and improvements to the `decorators` module **concept docs.**.
The completed portion of this concept can be found [here](https://github.com/exercism/python/blob/main/concepts/decorators/about.md).
The related **concept exercise** issue and specs can be found [here](https://github.com/exercism/python/issues/3119).

<br>

If you have not yet contributed to concept documents, this issue will require some upfront reading to give you the needed background knowledge.  Additionally, we recommend reading the existing `about.md` docs [here](https://github.com/exercism/python/blob/main/concepts/functools/about.md), and an example of completed concept docs [here](https://github.com/exercism/python/tree/main/concepts/classes).

## ✅   Getting started

**`Please please read the docs before starting.`** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. 

**General Contributing Docs:**

- [Contributing to Exercism](https://exercism.org/docs/building) | [Exercism and GitHub](https://exercism.org/docs/building/github) | - [Contributor Pull Request Guide](https://exercism.org/docs/building/github/contributors-pull-request-guide)
- [What are those Weird Task Tags about?](https://exercism.org/docs/building/product/tasks)
- [Exercism Formatting and Style Guide](https://exercism.org/docs/building/markdown/style-guide)
- [Exercism Markdown Specification](https://exercism.org/docs/building/markdown/markdown)
- [Reputation](https://exercism.org/docs/using/product/reputation)  

**Documents on Language Tracks and Concepts:**

- [Building Language Tracks: An Overview](https://exercism.org/docs/building/tracks) 
- [What are Concepts?](https://exercism.org/docs/building/tracks/concepts)
- [Concept Specifications](https://exercism.org/docs/building/tracks/concepts) 

<br>

## 🙏🏽   Desired Improvements and Changes

Create/complete the files for this concept:  

-  [x] `introduction.md`
-  [x] `links.json`
-  [x] `.meta/config.json` 

The `about.md` for this concept has already been completed.

<details open>
<summary><b>File Detail for this Issue</b> (<em>click to collapse</em>)</summary>
<table>
<td>
<br>

Please see the following for more details on these files:  [concepts](https://exercism.org/docs/building/tracks/concepts)

* ### `links.json`

  For more information, see [concept links file](https://github.com/exercism/docs/blob/main/building/tracks/concepts.md#file-linksjson)

  -  The same resources listed in this issue can be used as a starting point for the [ `concepts/links.json`](https://github.com/exercism/docs/blob/main/building/tracks/concepts.md#file-linksjson)  file, if it doesn't already exist.
  -  If there are particularly good/interesting information sources for this concept that extend or supplement the concept exercise material & the resources already listed -- please add them to the `links.json` document.

* ### Concept `about.md` 

  For more information, see [Concept `about.md`](https://github.com/exercism/docs/blob/main/anatomy/tracks/concepts.md#file-aboutmd)

  - This file provides information about this concept for a student who has completed the corresponding concept exercise.  It is intended as a reference for continued learning.   This portion has already been completed, and you can find the document [here](https://github.com/exercism/python/blob/main/concepts/decorators/about.md).

* ### Concept `introduction.md`

  For more information, see [Concept `introduction.md`](https://github.com/exercism/docs/blob/main/building/tracks/concepts.md#file-aboutmd)

  * This can also be a summary/paraphrase of the  `about.md` document listed above, and will provide a brief introduction of the concept for a student who has **not yet** completed the associated concept or practice exercises.   It should contain a good summation of the concept, but not go into lots of detail.

* ### Concept `.meta/config.json` Entries

  For more information, see [Concept `.meta/config.json`](https://github.com/exercism/docs/blob/main/building/tracks/concepts.md#file-metaconfigjson)

  * This file is likely already stubbed out.  Remember to add a concept **blurb** of less than 350 characters.  Please also add your GitHub username to the "authors" array, and any contributor GitHub usernames to the "contributors" array.

<br>
</td>
</table>
</details>

**Comment by velaco** [comment]
Hi @BethanyG 
I would like to be assigned to help out with this task if it hasn't been taken already 🙂

**Comment by BethanyG** [comment]
@velaco  - _Happy to have you do it!_  🎉 

FYI - if after going over the `about.md` doc you have improvements or changes you think are needed, please feel free to make them - none of it is set in stone.

Give a shout if you have any questions or issues.

**Comment by velaco** [comment]
Hi @BethanyG 
Any chance you can give me permission to push a local dev branch, or do I need to fork the repo and create a PR from there?

**Comment by BethanyG** [comment]
Closing this as resolved now that #3135 has been merged.  

@velaco  -- thank you very much for working on this!  🎉
