### ISSUE TITLE
[Ghost Gobble Arcade Game]: Stub Notes are Confusing

### ISSUE THREAD

**Issue by Crucibl** [exercism/python#3132]
Should be mentions of "If Else statements in the readme because the Boolean expressions are a red herring. You cannot solve anything by setting the value to true or false.

**Comment by BethanyG** [comment]
Hi @Crucibl 👋🏽 

Thanks for filing this issue.  You are, however mistaken.  It is quite possible to solve the `Ghost Gobble Arcade Game` without the use of conditionals.  Please see the [exemplar solution](https://github.com/exercism/python/blob/main/exercises/concept/ghost-gobble-arcade-game/.meta/exemplar.py) here in the repo for more details.  

We worked very hard to ensure that the `bools` exercise did not require `conditionals` in its solution, since it precedes the `conditionals` exercise.  We also wanted to make sure students really focused in on the Boolean logic. While it is _possible_ to use `if`, `elif` or `else` for the problem (_its entirely your choice_), it is by no means _required_ for a correct solution.

**Comment by Crucibl** [comment]
Yes so this says to return a Boolean

 """Verify that Pac-Man can eat a ghost if he is empowered by a power pellet.
    :param power_pellet_active: bool - does the player have an active power pellet?
    :param touching_ghost: bool - is the player touching a ghost?
    :return: bool - can the ghost be eaten?
    """

**Comment by Crucibl** [comment]
And you dont return a boolean, you simply return the parameters

**Comment by BethanyG** [comment]
@Crucibl - I believe you are misunderstanding the code.  Please take a look at this Real Python article [Python Booleans](https://realpython.com/python-boolean/#python-booleans-as-keywords) for more information.  It is not the **_parameters_** that are important in the `return` statement, it is the use of `or`, `and`, `not`.

The evaluation of those Boolean Operators results in `True` and `False`.

**Comment by Crucibl** [comment]
I completely misunderstand because of the way it is written

**Comment by Crucibl** [comment]
Would be better to write the parameters (has_eaten_all_dots, power_pellet_active, touching_ghost) are boolean values that need to be evaluated

**Comment by Crucibl** [comment]
"""Evaluate that Pac-Man can eat a ghost if he is empowered by a power pellet by returning the parameters
touching_ghost and  power_pellet_active: bool - does the player have an active power pellet?- is the player touching a ghost?
"""

**Comment by Crucibl** [comment]
"""Evaluate that Pac-Man can eat a ghost if he is empowered by a power pellet by returning the parameters
touching_ghost and power_pellet_active: which are already set to a bool in the test file - does the player have an active power pellet?- is the player touching a ghost?
"""

**Comment by Crucibl** [comment]
Did they complete the exercise by looking at prior solutions before answering? How can you read this and not be confused

**Comment by Crucibl** [comment]
Stub notes or readme. Anything to clarify what is being asked

**Comment by Crucibl** [comment]
The docstrings and Readme lead me to believe that I must set something to true or false. So when I read. Verify that Pac-Man can eat a ghost if he is empowered by a power pellet. :param power_pellet_active: bool - does the player have an active power pellet? :param touching_ghost: bool - is the player touching a ghost? :return: bool - can the ghost be eaten? I first think set parameter power_pellet_active to a boolean, like power_pellet_active = True and touching_ghost: = True so is the player touching a ghost? is = to true

**Comment by Crucibl** [comment]
"We also risk confusing people more by adding more words."
Im not trying to add more words. Im trying to optimize the wording for intellectually challenged people like myself who dont realize the variables are already defined in the test files

**Comment by Crucibl** [comment]
Then maybe 12,000 people can solve the puzzle not 6300

**Comment by Crucibl** [comment]
1008202
members have earned this badge for joining Exercism. but only 294540
members have earned this badge. for submitting an exercise. So out of 100 users only 36 or 37 actually submit an exercise. Why do more than 60 people out of every 100 not submit an exercise?

**Comment by Crucibl** [comment]
More than half the people join and quit

**Comment by Crucibl** [comment]
Surely we can improve

**Comment by Crucibl** [comment]
There are 194,498 students in the Python track and only 6300 have been able to solve the 3rd exercise

**Comment by BethanyG** [comment]
@Crucibl  - my reasons are mentioned in my [comment above](https://github.com/exercism/python/issues/3132#issuecomment-1175416070), and I don't think going back and forth as if this is a chat window is helpful.  We'll think about your feedback and consider changing the wording, **but it's not going to happen right now.**  We need to gather feedback from other users/mentors and maintainers on if the exercise is as confusing to them as it is to you.

**Comment by bobahop** [comment]
Adding my feedback as a student, mentor, and maintainer... (sorry for the late response, I haven't checked issues for a while)

>The docstrings and Readme lead me to believe that I must set something to true or false. 

That is more vague than the actual instructions. The instructions specify

>The function should return True only if Pac-Man has a power pellet active and is touching a ghost.

What is being set is the function's return value. It's not simply a matter of returning the parameters. It's a matter of how they are joined in the returned expression.

`    return power_pellet_active or touching_ghost`

is returning the parameters, but not in a way to solve the task. I think the instructions make clear the arguments to the two parameters are used to set the return value from the function. The instructions begin with

>Define the eat_ghost() function that takes two parameters (if Pac-Man has a power pellet active and if Pac-Man is touching a ghost) and returns a Boolean value if Pac-Man is able to eat the ghost.

In the 20+ times I've mentored this exercise I don't recollect any student saying they've been confused by the instructions for that task. They sometimes do more than they need to solve it by setting the expression to a variable and then returning the variable, or by using if/else when they can just return the parameters joined with the correct logical operator, but they get the general gist.

Clearness of the instructions is taken just as seriously as not modifying the instructions unnecessarily. It's a pain for everyone when their completed solution becomes outdated just from a change to the instructions. If there were multiple people complaining about these instructions being unclear, then a re-evaluation of them would certainly be in order. But, sorry, that is less likely to happen with a one-off complaint, not matter how fervent it may be.

**Comment by BethanyG** [comment]
Closing this for now, as we've had no additional complaints.  Will re-open if the issue comes up again from additional students or mentors.
