### ISSUE TITLE
[Triangle]: Bug that allows faulty solutions to be accepted

### ISSUE THREAD

**Issue by krion7** [exercism/python#3134]
Hello Exercism team, thank you for your continuous work and contributions on the website!

FYI, I am a beginner to Python (only 16.8% completion on the Python track) and brand new to GitHub, so please excuse me if I make any mistakes on this issue.

I would like to inform you about a bug I encountered on the Triangle exercise in Python, more specifically at the scalene part. Say, we've got a code like this:
```
def scalene(sides):
    a, b, c = sides
    return valid_triangle(sides) and a != b != c
```
That code is accepted as a valid solution when verified with current tests. However, this code **shouldn't** be a valid solution as demonstrated here.
```
>>> scalene([2, 3, 2])
True
```
Of course, a triangle with lengths of 2, 3, and 2 is **not scalene** since a scalene triangle has all sides of different lengths, but is recognized as such by that code.

I notice that there is no such test there that is identical to `scalene([2, 3, 2])` in the current list of tests on the Triangle exercise. To solve this problem, I suggest adding a test like that to reduce the chance of faulty solutions being accepted.

And, I suspect this might be a problem in other language tracks too, so that might be worth checking.

Thanks!

**Comment by BethanyG** [comment]
Hi @krion7 👋🏽 

Thanks for filing this issue!

> _And, I suspect this might be a problem in other language tracks too, so that might be worth checking._

And that is indeed what I am going to suggest to you.  😄   The `Triangle` practice exercise (_and its associated tests_) for this track is actually pulled from a cross-track [problems specifications](https://github.com/exercism/problem-specifications) repo.  The Python track auto-generates the details based on the canonical data there.  So I would recommend filing this issue in problem specifications for the maintainers to discuss.


Re-opening or commenting on [this](https://github.com/exercism/problem-specifications/issues/1567) might also be good, as it also pertains to scalene triangle tests -- but you can also open a new issue for discussing adding new test cases.

**Comment by BethanyG** [comment]
Closing the issue here in the Python repo, as the issue has bee raised cross-track in problem specifications.
