### ISSUE TITLE
[Transpose] - unittesting code error

### ISSUE THREAD

**Issue by joemichalak** [exercism/python#3136]
I am working on the python Transpose exercise and it appears that there is an issue with the unittest setup. 

For the code block:
`lines = ["Single line."] 
expected = ["S", "i", "n", "g", "l", "e", " ", "l", "i", "n", "e", "."] 
self.assertEqual(transpose("\n".join(lines)), "\n".join(expected))`

My code is returning the value assigned to expected. But I believe that 'self.assertEqual transpose("\n".join(lines))' should actually be `"\n".join(transpose(lines))` and/or the `self.assertEqual` condition should just be `self.assertEqual(transpose(lines), expected)`. In this particular case, `transpose("\n".join(lines))` is trivial because lines is a list with one item. Furthermore, the values assigned to `lines` are all lists, and it seems unusual to pass a string in the test case. 

Furthermore, when I looked at the solution in the .meta folder, it appears as if historically the exercise may have passed a string, given that the list generator function in line 2, `rows = [row.replace(' ', '_') for row in lines.splitlines()]` uses `.splitlines()` which is valid for a string, but not for a list.

**Comment by BethanyG** [comment]
Hi @joemichalak 👋🏽 

Thanks for submitting this issue.  There are two things that might be very confusing about the way these unit tests are written:

1.  The tests are indeed passing a `str` to the function under test..but it's not entirely obvious that they are doing so.  The test data for this exercise is pulled from a common repo, [problem-specifications](https://github.com/exercism/problem-specifications/tree/main/exercises/transpose), and the canonical data there is using an array, so our tests are putting that data back together into a string via `.join()`.  
2. The test file is generated via  a [JinJa2 template](https://github.com/exercism/python/blob/main/exercises/practice/transpose/.meta/template.j2).  The template is used for all cases, so the single list entry is a bit of an odd duck out, in that it uses `.join()` when it doesn't strictly _have to_ -- but doing so makes the JinJa2 template simpler and easier to maintain.

Having walked through this exercise, I think that the tests are correct as-is, with the caveat that the one single entry case is going through an unnecessary `.join()` -- but that it's ok, given the way the template is made.

**Comment by joemichalak** [comment]
Hi @BethanyG , 

I see what's happening now, and you're completely correct. Thank you very much for the very insightful answer!
