### ISSUE TITLE
[List Ops]: Potential mismatch between instructions and tests

### ISSUE THREAD

**Issue by OndrejMarsalek** [exercism/python#3141]
The instructions for `append` say "given two lists, add all items in the second list to the end of the first list". Although I understand someone could read it the other way, to me, a strict reading of this is that the first list should be modified. The tests do not guard against constructing a third list that contains items from both inputs, and people will commonly solve this with `return list1 + list2`. I think that either the instructions or tests should be updated, but I am not submitting a PR, as it is not clear to me what the original intention was.

**Comment by BethanyG** [comment]
Closing to track under #3156.  Please give a shout if you'd like to work on the issue.
