### ISSUE TITLE
[List Ops]:  def concat(lists) possible test error

### ISSUE THREAD

**Issue by dfreeman500** [exercism/python#3142]
Hello, 
I'm a relative newbie so hopefully I'm not adding more work. 

In the Python List Ops project 'list_ops.py',

def concat(lists): is supposed to "(given a series of lists, combine all items in all lists into one **flattened** list)".

On line 36 in the test file the expected result does not appear to be a flattened list:
`    def test_concat_list_of_nested_lists(self):
        self.assertEqual(
            concat([[[1], [2]], [[3]], [[]], [[4, 5, 6]]]),
            [[1], [2], [3], [], [4, 5, 6]],
        )`

I would expect that the test should actually be: 

`    def test_concat_list_of_nested_lists(self):
        self.assertEqual(
            concat([[[1], [2]], [[3]], [[]], [[4, 5, 6]]]),
            [1, 2, 3, 4, 5, 6],
        )`

So, [1, 2, 3, 4, 5, 6] instead of [[1], [2], [3], [], [4, 5, 6]]

Thanks for all you do!

**Comment by IsaacG** [comment]
The prose might benefit from some rewording but this is an intro to lists exercise. There's an [explicit and specific exercise for list flattening](https://github.com/exercism/python/tree/main/exercises/practice/flatten-array) which is distinct from this exercise.

**Comment by BethanyG** [comment]
Hi @dfreeman500 👋🏽 

Thanks for filing this issue. 

We pull the test cases for practice exercises from a common repo, [problem specifications](https://github.com/exercism/problem-specifications) and use a test-case generator here on the Python track to turn the canonical data for a given exercise into python unittest/pytest test cases.  

[Here](https://github.com/exercism/problem-specifications/blob/main/exercises/list-ops/canonical-data.json) is the canonical data for `List-Ops`.  As you can see, the expected result treats the innermost lists as _elements_, and does not unpack them, but does remove the enclosing (second-level) lists.  So it does appear the spirit here is "flatten to one" as opposed to "recursively unpack".

With all that being said, I agree that the word "flattened" could be easily mis-interpreted in the instructions, and could benefit from some more detail or explanation.  

I'd suggest that you PR a change/start a discussion about the exercise in [problem specifications](https://github.com/exercism/problem-specifications), and perhaps ask about the logic of the expected result for that case.  I know in Python that a general default is one level of unpacking, but this is actually two levels, but not a full unpack.  We may want to examine how/why that test case is there, and if it needs to be altered and/or the instructions altered.

**Comment by BethanyG** [comment]
Closing this for now, since the issue lies in problem specifications.  Can re-open if an instruction append on the track is needed.
