### ISSUE TITLE
[Card Games]: Missing period in `/.docs/introduction.md`

### ISSUE THREAD

**Issue by unfirthman** [exercism/python#3147]
The final sentence of the first paragraph appears to be missing a period. This is a super small thing, but I am super new to github and would like the practice!

> Like any [sequence](https://docs.python.org/3/library/stdtypes.html#sequence-types-list-tuple-range), items can be accessed via 0-based index number from the left and -1-base index from the right. Lists can be copied in whole or in part via [slice notation](https://docs.python.org/3/reference/expressions.html#slicings) or <list>.copy()

Happy to take this on if that's alright.

**Comment by BethanyG** [comment]
Hi @unfirthman 👋🏽 

We love that you want to practice (_and no PR is too small_ 😄 ).  There are a few ways you can go about this:

1.  Right here in the Git Hub webpage/interface.  If you navigate to the file in the UI, you can click on the edit button (highlighted below), and can edit the markdown directly.  Git Hub will make a special "patch branch" (see second image) that you can then title, comment and commit from.

<img src="https://user-images.githubusercontent.com/5923094/180512929-0492634b-4e4d-4305-996a-2698ba5cfa6e.png" width=400>
<br>
<img src="https://user-images.githubusercontent.com/5923094/180513779-d05dfa26-c5e3-4773-b85b-212adf903250.png" width=400>

2.  Dig in a bit more and [make a project fork](https://docs.github.com/en/get-started/quickstart/fork-a-repo) that you can use to do future edits.  Use either the GitHub web interface or the [GitHub desktop client](https://desktop.github.com/) to make the change and PR.
3. Make a fork and Install [git](https://docs.github.com/en/get-started/using-git/about-git) locally.  Clone your fork down to your machine, make a branch, commit your changes and push back to the fork.  Then, open a PR.  😄   You learn more about the this sort of workflow [here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

For any of those three strategies, make sure to ping for a review, so a maintainer can approve and merge the changes when they're ready.

I'd also challenge you to maybe go through the associated docs for this exercise (see the [lists concept docs](https://github.com/exercism/python/tree/main/concepts/lists) and the [exercise folders](https://github.com/exercism/python/tree/main/exercises/concept/card-games) and see if there are any other changes that should be made to their spelling, grammar, punctuation, or code.  You could then add those to your PR.  You don't _**have to**_, but it might be fun -- and we'd surely appreciate the help.  😉 🌈 

But just learning the workflow can be a lot, so no hard feelings _**at all**_ if you fix the typo and move on.  Also feel free to ping if you get stuck or need help with something.  _Good luck!_

**Comment by unfirthman** [comment]
Sounds great. Thanks @BethanyG ! I will go through these other documents and add them to my PR if I find any spelling or grammar improvements.

**Comment by BethanyG** [comment]
Closing now that #3152 has been merged.  Thank you for your contribution, @unfirthman!
