### ISSUE TITLE
[Currency Exchange] Inconsistent change value type (`float`/`int`)

### ISSUE THREAD

**Issue by pranasziaukas** [exercism/python#3157]
Exchanged value is of type `float`:

https://github.com/exercism/python/blob/48e47c1f6af8050e135747461085d713a3231164/exercises/concept/currency-exchange/exchange.py#L6

Remaining value is of type `float` as well:

https://github.com/exercism/python/blob/48e47c1f6af8050e135747461085d713a3231164/exercises/concept/currency-exchange/exchange.py#L17

Value exchangeable in bills of a certain denomination is of type `int`, but that is justifiable because denominations are integers:

https://github.com/exercism/python/blob/48e47c1f6af8050e135747461085d713a3231164/exercises/concept/currency-exchange/exchange.py#L52

However, non-exchangeable value is of type `int` as well, which I believe is inconsistent:

https://github.com/exercism/python/blob/48e47c1f6af8050e135747461085d713a3231164/exercises/concept/currency-exchange/exchange.py#L65
 
Given the established structure, I see no reason why the non-exchangeable value should be integer. I mean, it clearly is not integer, but has to be rounded artificially to pass the tests.

---

Overall, I was surprised how convoluted this seemingly simple exercise was.

For one, there are few opportunities to reuse code in `exchangeable_value` (task 5) and `non_exchangeable_value` (task 6).
The essence of both of these functions is to calculate the exchangeable amount given the spread, which could've been implemented in `exchange_money` (task 1).
Then `exchangeable_value` could potentially reuse `get_value_of_bills` (task 3), whereas `non_exchangeable_value` could potentially reuse `get_change` (task 2) -- except for the fact that it expects an integer, therefore this issue.

As a side note, if we're really looking to encourage the usage of the modulo operator `%`, we could introduce a task to convert amounts using different denominations (and e.g. calculate the remainder that cannot be converted).

Happy to discuss & potentially submit a PR.

**Comment by BethanyG** [comment]
Hi @pranasziaukas 👋🏽 

Welcome back.  😄 

I'm very happy to discus you reworking this exercise - I like the changes you propose above, and I think more practice with the modulo operator would also be good.

As you can see from the discussions in #2951 , and the additional issues linked within -- we've had some issues with `currency exchange` and the general `numbers` concept.  We've been contemplating replacing the exercise with one or more different numbers-focused challenges instead.

So if you'd like to take on a bigger challenge, there is definitely opportunity to both rethink `currency exchange` as well as expand the `numbers` "concept cluster" by creating additional exercises for `complex-numbers`,  the `int` variants `bin`, `oct`, and `hex`, and using modules such as `decimal` and `fractions`. 

`decimal` in particular could be a nice work-in for a `currency exchange` follow-on, given that exchange value for currency is often 3-4 decimal places, but _purchase value_ for goods and services is often 2-3 decimal places.  

Just let me know how you'd like to proceed - I am open to revamp, replacement, and/or extension.

**Comment by BethanyG** [comment]
Also just putting this here for reference, so we have a link to how the Python docs talk about numeric types: https://docs.python.org/3/library/stdtypes.html#numeric-types-int-float-complex

**Comment by BethanyG** [comment]
@pranasziaukas  - just checking in - are you still interested in making a PR for this?  If not, I can add your comments to the tracking issue we have for reworking this exercise.  Just let me know.  Thanks!

**Comment by pranasziaukas** [comment]
Sorry, I still intend to circle back to this @BethanyG. I opened this issue just before my vacation thinking I might have some spare time while traveling, but I was wrong :)

**Comment by BethanyG** [comment]
@pranasziaukas  - I hope you were wrong because you were busy having fun on vacation!  😄   And no worries - ping when you are ready.   Meanwhile, I'll  assign this to you .

**Comment by pranasziaukas** [comment]
Hello and thanks for your thoughtful (as always) response @BethanyG.

> Just let me know how you'd like to proceed - I am open to revamp, replacement, and/or extension.

Since I'm still an infrequent visitor, not really comfortable to do a deep strategic dive.
I will iterate the current exercise to hopefully make things more consistent and friendly to further changes.

PR incoming!
