### ISSUE TITLE
Bad indentation error for tab size of 2

### ISSUE THREAD

**Issue by eminphi** [exercism/python#3171]
Python Analyzer produces an essential error when tab size of `2` is used instead of `4`. I work exercises locally via CLI.

`exercism version 3.0.13`

<img width="480" alt="Screen Shot 2022-09-11 at 12 02 24 PM" src="https://user-images.githubusercontent.com/42714627/189537428-e9df6dab-a894-4115-a209-cd92b2880c7d.png">

**Comment by bobahop** [comment]
Thank you for your interest in improving the Python track on Exercism.

The analyzer follows the [Python Style Guide for Indentation](https://peps.python.org/pep-0008/#indentation) which says 

>Use 4 spaces per indentation level.

So the analyzer is enforcing the style guidelines as written by the creator of the Python language and others.

Please let us know if this response is satisfactory so we can close this issue. Thanks!

**Comment by eminphi** [comment]
Thanks for the Guide reference. I always, inaccurately, assumed that the indentation is just a personal preference. Something new I've learned today!
