### ISSUE TITLE
[Cater Waiter] Possible mistake in "categorize_dish" method docstring

### ISSUE THREAD

**Issue by rodrigosantiag** [exercism/python#3186]
I think that there's an error in param dish_ingredients param type description in `categorize_dish' docstring.

On "task" introduction is written: 
```
Implement the categorize_dish(<dish_name>, <dish_ingredients>) function that takes a dish name and a **set** of that dish's' ingredients
```

But on method's docstring the `dish_ingredients` param type definition is as list

```
:param dish_ingredients: list - ingredients for the dish.
```

Looking to method's unit tests, we can see that, in fact, the second method argument is `set'

**Comment by BethanyG** [comment]
Hi @rodrigosantiag 👋🏽 

Thanks for filing this issue!  There is indeed a mistake - would you like to submit a PR to fix it?  😉   If not, I'll see if I can get to it this weekend.  😄

**Comment by rodrigosantiag** [comment]
Hi @BethanyG .

I opened the PR [#3187](https://github.com/exercism/python/pull/3187)

Regards

**Comment by BethanyG** [comment]
Hi @rodrigosantiag  - Thank you for the PR!  It is approved and merged.  😄   Closing this now as fixed. 🌟
