### ISSUE TITLE
[Tisbury Treasure Hunt] Task Example Correction

### ISSUE THREAD

**Issue by zylideum** [exercism/python#3196]
# Tisbury Treasure Hunt Task 4

Task 4 has the following example, pulled directly from the site:

```py
>>> create_record(('Brass Spyglass', '4B'), ('Abandoned Lighthouse', ('4', 'B'), 'Blue'))
('Brass Spyglass', '4B', 'Abandoned Lighthouse', ('4', 'B'), 'Blue')

>>> create_record(('Brass Spyglass', '4B'), (('1', 'C'), 'Seaside Cottages', 'blue'))
"not a match"
```

As you can see in the second call of create_record, the `rui_record` tuple is formatted incorrectly, listing the coordinate tuple before the location. 

The example posits the format of `rui_record` as such: `(location, coordinate, quadrant)`.

## Verification via Unit Tests

Upon looking at [tuples_test.py](https://github.com/exercism/python/blob/main/exercises/concept/tisbury-treasure-hunt/tuples_test.py), we can see that the test for the `rui_record` that contains `Seaside Cottages` is in the correct format, verifying the example in the instructions is incorrect.

```py
 (('Amethyst  Octopus', '1F'), ('Seaside Cottages', ('1', 'C'), 'Blue')),
```

## Importance

The second call of `create_record` contradicts the first call in the example, potentially confusing people about whether they should handle a `rui_record` tuple in which the coordinate pair is at index 0.

## Solution

I'll be submitting a PR that fixes the typo in the example to swap the `coordinate` with the `location` in the second call of `create_record`

### Question

Are there changes that need to be made to any other repositories aside from the `instructions.md` file in the exercise repository to push the change to the site? I noticed the `website-copy` repository but none of the exercises included the instructions. Just wanted to verify.

**Comment by zylideum** [comment]
Closed with PR #3197

**Comment by BethanyG** [comment]
Hi @zylideum 👋🏽 

Thank you for filing this issue.  Apologies for the delay in getting back to you.  I think the one change to `instructions.md` should do it.  If not, we can do a follow up. 😄

**Comment by zylideum** [comment]
Looks like it made it to the site, thanks!
