### ISSUE TITLE
Python Forth Exercise Test 29 is wrong

### ISSUE THREAD

**Issue by joMarsch** [exercism/python#3199]
Test 29 of the Forth exercise seems wrong. If I understand the test the right way the output should be [1,2,2] instead of [1,2,1].

**Comment by BethanyG** [comment]
Hi @joMarsch 👋🏽 

Thanks for filing this issue.  The Python track pulls test data (inputs and expected results) from a central repo, [problem specifications](https://github.com/exercism/problem-specifications), where the [canonical data](https://github.com/exercism/problem-specifications/blob/main/exercises/forth/canonical-data.json#L342) shows that `[1,2,1]` is indeed the expected result for the case.

I would recommend that you either open an issue in that repo to discuss things, or open a discussion on our [discussion forum](https://forum.exercism.org/t/exercise-but-no-actual-lessons/867) to talk through the exercise and the test results, and where you think they should be changed or improved.

Once we get an understanding of what should be changed in problem specifications, all repos that pull from there can be updated with the information.

**Comment by qianzhong516** [comment]
For anyone who might have encountered the same confusion - I searched for the forth documentation and realised what the `OVER` command actually does is:
> OVER    ( n1 n2 — n1 n2 n1 )    Copies second item to top

Hence the test is actually correct.

Link: https://www.forth.com/starting-forth/2-stack-manipulation-operators-arithmetic/
