### ISSUE TITLE
Missing backslashes in sgf parsing test test_escaped_t_and_n_in_property_value_are_just_letters_not_whitespace

### ISSUE THREAD

**Issue by blakelewis** [exercism/python#3282]
The test currently expects you to convert "\t" and "\n" to "t" and "n".  The intent is presumably to check that the two-character sequences "\" + "t" and "\" + "n" get converted to "t" and "n", as the problem statement specifies.  However, the test string actually contains a tab and a newline because of incorrect escaping.

**Comment by blakelewis** [comment]
OK, that's certainly disappointing.  It is too bad that obviously broken changes get checked in.

**Comment by BethanyG** [comment]
Hi @blakelewis 👋🏽 

It seems odd that [this solution](https://exercism.org/tracks/python/exercises/sgf-parsing/solutions/IsaacG) by one of our top python mentors and contributors passes all the latest tests for this exercise when there is an obviously broken change.

Additionally, if you would like to discuss your issue, you are welcome to in our [forum](https://forum.exercism.org/new-topic?title=Missing%20backslashes%20in%20sgf%20parsing%20test%20test_escaped_t_and_n_in_property_value_are_just_letters_not_whitespace&body=The%20test%20currently%20expects%20you%20to%20convert%20%22%5Ct%22%20and%20%22%5Cn%22%20to%20%22t%22%20and%20%22n%22.%20%20The%20intent%20is%20presumably%20to%20check%20that%20the%20two-character%20sequences%20%22%5C%22%20+%20%22t%22%20and%20%22%5C%22%20+%20%22n%22%20get%20converted%20to%20%22t%22%20and%20%22n%22,%20as%20the%20problem%20statement%20specifies.%20%20However,%20the%20test%20string%20actually%20contains%20a%20tab%20and%20a%20newline%20because%20of%20incorrect%20escaping.&category=python), at which point if it is indeed a bug, we can reopen this issue and assign someone to work on it.

**Comment by blakelewis** [comment]
The solution that you cite contains a workaround for the test bug at line
48.

It is of course not correct behavior for the parser to convert tab
characters to "t" and newlines to "n".  It is a very obvious bug.
Backslashes are tricky to get right and at some point, a pair of them got
dropped.
