### ISSUE TITLE
Hello_World test breaking with import error

### ISSUE THREAD

**Issue by bo1658a** [exercism/python#3345]
I did the Hello_world test and encountered an error on submission as seen below. Kindly assist.

We received the following error when we ran your code:
  ImportError while importing test module '.mnt.exercism-iteration.hello_world_test.py'.
Hint: make sure your test modules.packages have valid Python names.
Traceback:
.usr.local.lib.python3.10.importlib.__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
.mnt.exercism-iteration.hello_world_test.py:3: in <module>
    from hello_world import (
E   ImportError: cannot import name 'hello' from 'hello_world' (.mnt.exercism-iteration.hello_world.py)

**Comment by BethanyG** [comment]
Hi @bo1658a 👋🏽 

Thank you for taking the time to raise this issue. As stated in the auto-response, we would prefer if you first raised issues in our [exercism forum](forum.exercism.org), and not here in the Python repo.  That gives us a chance to discuss the issue and determine if it is a bug or something that can be resolved by other means.

The forum has many friendly people who would love to discuss and help students with issues they encounter.  Another alternative is to use our [CLI](https://exercism.org/docs/using/solving-exercises/working-locally) to upload your partial solution and [request mentoring](https://exercism.org/docs/using/feedback/mentor).  A mentor can walk through your solution and point out where things might have gone wrong.

My reply in [this forum post](http://forum.exercism.org/t/error-executing-code-in-python/1775/2) might also be helpful for your particular situation.
