### ISSUE TITLE
[Simple Linked List]:  Re-Do SVG Images to Have Transparent Background.

### ISSUE THREAD

**Issue by BethanyG** [exercism/python#3477]
The current images in the instruction append have a white background which looks bad with dark mode.  These should be replaced to have a transparent background, so that they work with both light and dark mode.

We should also consider re-working the instruction append so that it reads better and clearer, given the edited instructions.

**Comment by nayan2167** [comment]
Hi @BethanyG I would like to work on this, can you explain it a bit more?

**Comment by BethanyG** [comment]
Hi @nayan2167,

Thanks for the offer, but this is actually a note to myself to work on this exercise, as community contributions to this repo are currently closed.  Please see [this post](https://exercism.org/blog/freeing-our-maintainers) for more details.

**Comment by BethanyG** [comment]
Fixed in part by [this](https://github.com/exercism/python/pull/3475)
