### ISSUE TITLE
[Triangle] Proposed Solution

### ISSUE THREAD

**Issue by krstopro** [exercism/python#3497]
Recently I saw the proposed solution to the Triangle exercise and there are few things I am not sure about.
First, the implementation of `is_valid`.
```
def is_valid(sides):
    if not sides[0]:
        return False
    return all(side * 2 < sum(sides) for side in sides)
```
The condition `not sides[0]` will work only if `sides` is sorted; e.g. it won't work for `[1, 0, 0]`. Also, none of the tests covers cases like this.
Here, `sum(sides)` is used in the generator. Is `sum` being evaluated in every iteration (making it quadratic complexity; here it is not important as `sides` has length 3, but I would prefer avoiding stuff like this in proposed solutions) or Python optimises this "under the hood"?
I believe it would be better idea to store `sum(sides)` in a variable and then use it in the generator.

Another thing I was not sure about is the proposed implementation of `equilateral`.
```
def equilateral(sides):
    return is_valid(sides) and len(set(sides)) == 1
```
Does it really make sense to check if triangle is valid here? Isn't it sufficient to check if all the sides have the same length greater than zero?

**Comment by IsaacG** [comment]
If you'd like to discuss a solution, I'd suggest one of the following:

* Request a code review/mentoring session
* Post on the forums
* Post on the Discord server.
