### ISSUE TITLE
Clarify that the root is a natural number in square-root documentation

### ISSUE THREAD

**Issue by ksnortum** [exercism/python#3594]
The instructions in `exercises/practice/square-root/.docs/instructions.append.md` says that they are "only testing natural numbers," but more clearly, the *solutions* are only natural numbers.  Two is a natural number and its root is real (and irrational).

**Comment by BethanyG** [comment]
Links to docs:

[Pull Request Guide](https://exercism.org/docs/building/github/contributors-pull-request-guide)
[Markdown Guide](https://exercism.org/docs/building/markdown)
[Practice Exercise Spec](https://exercism.org/docs/building/tracks/practice-exercises)
