### ISSUE TITLE
[Little Sister’s Essay] A typo in the exercise introduction 

### ISSUE THREAD

**Issue by anym0us** [exercism/python#3673]
Hello! 👋 I'm really enjoying Exercism, thank you!

Would like to suggest a fix for a small typo in the first example of ["Little Sister's Essay" exercise](https://exercism.org/tracks/python/exercises/little-sisters-essay).

Here's a PR: https://github.com/exercism/python/pull/3672

---

**Currently:**
```man_in_hat_ru = 'mужчина в шляпе'``` (`m` is a latin/roman letter).

**A suggested change:**
```man_in_hat_ru = 'мужчина в шляпе'``` (`м` is expected to be a cyrillic letter).

**Comment by BethanyG** [comment]
For record-keeping, I am going to reopen this, so that when the PR is merged, we can say this has been fixed.  😄 

Thanks for finding/fixing this.

**Comment by anym0us** [comment]
I'm happy to make Exercism even better! Thanks a lot for everything you did for the project. 🙇
