### ISSUE TITLE
[Card Games] `approx_average_is_average` docstring summary needs improvement

### ISSUE THREAD

**Issue by anym0us** [exercism/python#3674]
Docstring summary of `approx_average_is_average` function could be more clear.

### A story behind
1. Initially I've started an implementation of `approx_average_is_average` function based on docstring.
2. Wrote the function, run tests and found the implementation doesn't work.
3. Then read instructions and found inconsistencies between docstring and instructions.

### Proposed change
| Currently | Suggested |
| --- | --- |
| `"""Return if an average is using (first + last index values ) OR ('middle' card) == calculated average.` | `"""Return if the (average of first and last card values) OR ('middle' card) == calculated average.`

### Screenshot

<img width="1212" alt="Screen Shot 2024-04-14 at 8 01 37 PM" src="https://github.com/exercism/python/assets/5333431/465fa9f6-561e-4df1-a3e6-349584d7d37c">

**Comment by BethanyG** [comment]
I like that suggestion, and would welcome a PR!  Thanks for logging this.  😄

**Comment by BethanyG** [comment]
Fixed in 33675
