### ISSUE TITLE
[Inventory Management] `list_inventory` docstring summary needs improvement

### ISSUE THREAD

**Issue by anym0us** [exercism/python#3683]
Docstring summary of `list_inventory` function is inconsistent.

### A story behind
1. Initially I've started an implementation of `list_inventory` function based on docstring.
2. Wrote the function, run tests and found the implementation doesn't work.
3. Then read instructions and found inconsistencies between docstring and instructions.

### Proposed change
| Currently | Suggested |
| --- | --- |
| `"""Create a list containing all (item_name, item_count) pairs in inventory.` | `"""Create a list containing only available (item_name, item_count > 0) pairs in inventory.`

### Screenshot

<img width="1411" alt="Screen Shot 2024-04-20 at 4 03 48 PM" src="https://github.com/exercism/python/assets/5333431/d26f2c6f-711b-431a-99ae-354ec3b6bf9e">

**Comment by BethanyG** [comment]
Thanks for this!  😄 

Feel free to PR this change - and any other typos or errors you find in the docs.  **As a note:**  the longer and more detailed concept documents display after the exercise is completed, and can be found under the `concepts/` directory.  The one for this exercise is [dicts](https://github.com/exercism/python/blob/main/concepts/dicts/about.md).

**Comment by anym0us** [comment]
@BethanyG Hi! 👋 Hope you're doing good.

👆 Please find above a link to PR.
