### ISSUE TITLE
[Mecha Munch Management]: Typos in hints for task #5 (`send_to_store`)

### ISSUE THREAD

**Issue by anym0us** [exercism/python#3685]
There are the following typos in hints for task no. 5 (`Send User Shopping Cart to Store for Fulfillment`):
1. Keyword argument should be `reverse`, not `reversed` (reference: [official documentation](https://docs.python.org/3/library/functions.html#sorted));
2. Boolean value should be `True`, not `true`.

### Proposed change
| Currently | Suggested |
| --- | --- |
| `reversed=true` | `reverse=True` |

### Screenshots
<img width="1113" alt="Screen Shot 2024-04-22 at 8 44 21 PM" src="https://github.com/exercism/python/assets/5333431/b7f9a057-c495-478a-987e-0cf8a8750859">

----
#### Official documentation:
<img width="613" alt="Screen Shot 2024-04-22 at 8 50 57 PM" src="https://github.com/exercism/python/assets/5333431/4e432086-483a-497b-b468-ccba4ef52d4b">

**Comment by BethanyG** [comment]
Fixed/closed by #3686.
