### ISSUE TITLE
Suggestions for making clock exercise more idiomatic

### ISSUE THREAD

**Issue by treyhunner** [exercism/python#373]
I teach Python and I sometimes send folks I'm mentoring to Exercism for more practice. 👍

I have some suggestions to make the clock exercise feel slightly more Pythonic. As I noted below, I'm very happy to open pull requests for each of these suggestions.
#### Comparability

Equality of `Clock` objects is tested, but other comparisons (e.g. `<` and `>`) are not checked.

It might be a good exercise to add a few tests implementing those. Most objects that rely on custom equality also implement the other forms of comparability in Python. I'd think it'd go something like this: 00:00 < 00:01 < 23:59.
#### add method

The `add` method looks very odd to me. It makes this object feel more JavaScript-like than Python-like.

``` python
>>> Clock(6, 15).add(-160) == Clock(3, 35)
True
```

I'd think either of these options might make more sense:

Option 1: Implementing `+` and `-` with integers (either only left-hand or right-hand also):

``` python
>>> Clock(6, 15) - 160 == Clock(3, 35)
True
```

Option 2: Implementing `+` and `-` with other `Clock` objects (this doubles up these objects as both times and time differences, but that may be fine in this case):

``` python
>>> Clock(6, 15) - Clock(0, 160) == Clock(3, 35)
True
```
#### repr

I'm not sure if this one is necessary, but this seems like the perfect object to test for a nice repr output on:

``` python
>>> Clock(6, 15)
Clock(6, 15)
```

---

I'd be happy to write a pull request for any/all of these suggestions. I wanted to open an issue for discussion first.

Thoughts on the above suggestions for the clock exercise? 😸

**Comment by patricksjackson** [comment]
The reason the exercise looks like it does is to match the common tests laid out in [x-common](http://github.com/exercism/x-common), either that or it was directly ported from something like JavaScript. That helps for consistency across tracks and saves the maintainers time designing the test suites.

I'm not one of the maintainers here, but I think filling out the operators as you described is a good idea for Python specifically :+1: 

(On your **repr** suggestion though, doesn't it already have that?)

**Comment by treyhunner** [comment]
@patricksjackson it tests for `str` but not `repr`. Given that `str` gives something like '05:05', I think it should have both (since `repr` tends to provide a description of how to construct a duplicate object).

**Comment by treyhunner** [comment]
For the 6 comparisons, you only need to implement 2 if you use [functools.total_ordering][total_ordering] (which is available in Python 2 and Python 3):

```python
from functools import total_ordering

@total_ordering
class Clock:
    def __init__(self, hours, minutes):
        self.hours, self.minutes = divmod(hours*60+minutes, 60)

    def __eq__(self, other):
        return (self.hours, self.minutes) == (other.hours, other.minutes)

    def __lt__(self, other):
        return (self.hours, self.minutes) < (other.hours, other.minutes)

    # ...
```

I agree that this is advanced for the third exercise. I think classes in general are a bit advanced for the third exercise. Unless folks are switching from an OOP language like Java, classes can be a very tricky concept initially.

The core of this exercise seems to be "normalize hours/minutes". That functionality could be achieved using just a function and I'd normally encourage my students to write functions for this type of exercise (bias: [Stop Writing Classes][] is one of my favorite talks). I assume that would be too drastic a change to make.

Would it make sense to move this exercise further down the list? Exercise 3 seems very early to introduce classes, `__str__`, `__eq__`, etc.

[total_ordering]: https://docs.python.org/2/library/functools.html#functools.total_ordering
[stop writing classes]: https://www.youtube.com/watch?v=o9pEzgHorH0

**Comment by behrtam** [comment]
Maybe the another option is to move it down a bit anyway and add decorated tests `@unittest.skip("advanced")` for all the additional stuff. So people that already know more about python classes, can do them if they want to.

**Comment by treyhunner** [comment]
@behrtam: I like both of those ideas! 👍

**Comment by behrtam** [comment]
Okay, do you have the time and interest to work on the new example implementation and the additional skipped tests?

**Comment by treyhunner** [comment]
@behrtam: yes, but slowly. I'm putting this on my list of stuff to look into in a couple weeks.

If someone else gets to this first please feel free to do this without me. 😄

**Comment by cmlang42** [comment]
Hello @behrtam and @TruthfulTechnology. I was wanting to get started with contributing to exercism and the python/c++ tracks. Would this be an issue that I might be able to pick up?

**Comment by treyhunner** [comment]
@cmlang42 I don't plan to take action to write code regarding this issue soon. This fell through the cracks of my to do list, so please feel free to pick it up if you're motivated to do so.

**Comment by behrtam** [comment]
@cmlang42 if you need any help just ask. If you get stuck just create a pull request with what you have even if it's not finished and we continue from there.

**Comment by cmlang42** [comment]
I created a PR (#447) for the part of moving the clock exercise later in the fetch order.  Here is a page with my notes for review of my understanding of the layout of the project:  (since I am a newbie on this project)
http://www.cmlang.com/blog/exercism-issue-fix-walkthrough/     

@treyhunner @behrtam 

This should, at least address the issue of the complexity of the example being to close to the beginning of the fetch order.
