### ISSUE TITLE
Run skipped tests

### ISSUE THREAD

**Issue by behrtam** [exercism/python#391]
The **allergies** exercise has an additional [test case](https://github.com/exercism/xpython/blob/master/exercises/allergies/allergies_test.py#L35-L37) which is skipped. If the tests get executed with the `.test/check-exercises.py` script during the travis build, even skipped tests should be run.

**Comment by rootulp** [comment]
The **linked-list** exercise also has two additional [test cases](https://github.com/exercism/xpython/blob/master/exercises/linked-list/linked_list_test.py#L47) which are skipped.

**Comment by cmccandless** [comment]
`allergies` exercise no longer contains skipped exercises.
