### ISSUE TITLE
Should we forgo any missing exercises

### ISSUE THREAD

**Issue by behrtam** [exercism/python#417]
Right now there are 36 exercises that are not yet part of the python track. Besides [implementing](https://github.com/exercism/x-common/blob/master/CONTRIBUTING.md#implementing-a-completely-new-exercise) or finishing those, there is also the option ([config.json#L465](https://github.com/exercism/xpython/blob/master/config.json#L46)) to decide not to implement certain problems if they don't make sense for this track.
- markdown
- bank-account
- pov
- tournament
- dot-dsl
- connect
- two-bucket
- sgf-parsing
- zipper
- ledger
- nucleotide-codons
- *simple-linked-list* #385 
- forth
- *binary-search-tree* #388 
- scale-generator
- tree-building
- error-handling
- transpose
- react
- parallel-letter-frequency
- hangman
- variable-length-quantity
- alphametics
- custom-set
- diffie-hellman
- change
- protein-translation
- counter
- lens-person
- go-counting
- word-search
- bowling
- dominoes
- food-chain
- paasio

**Comment by skabbass1** [comment]
@behrtam 
Are you still looking for contributions on this issue ( implementing the 36 exercises not part of the python track). Also  just curious to know why you think certain problems don't make sense for the python track (I haven't looked through all the exercises so just asking for my information :) )

**Comment by kabiir** [comment]
@behrtam I can contribute binary-search-tree exercise should I open a new issue for it or reference the closed one #388 in my PR

**Comment by m-a-ge** [comment]
@kabiir, that is awesome.
I'm planning to open issues for these exercises as part of Hacktoberfest. Will it work for you?

**Comment by kabiir** [comment]
@m-a-ge  Yes of course! I'm excited to start coding.

**Comment by cmccandless** [comment]
I've implemented `dominoes`  at #726.

**Comment by m-a-ge** [comment]
Updated list of not yet implemented exercises excluding deprecated ones and those which were implemented since Feb 22 (24 in total):

- markdown
- bank-account
- pov
- dot-dsl
- connect
- two-bucket
- sgf-parsing
- zipper
- ledger
- simple-linked-list #385
- forth
- binary-search-tree #388
- tree-building
- error-handling
- react
- parallel-letter-frequency
- hangman
- custom-set
- diffie-hellman
- go-counting
- dominoes
- food-chain
- paasio
- spiral-matrix

**Comment by m-a-ge** [comment]
@kabiir I've created issues as promised 😉

**Comment by aes421** [comment]
Is Bowling deprecated?  It's on the unimplemented list, but I don't see an issue for it.  If it's up for grabs I can do it when I finish my current PR.

**Comment by m-a-ge** [comment]
@aes421 hm, looks like I've missed that exercise somehow.
Feel free to open a new PR any time (there is no need to wait until your other PR are merged). Only make sure you'll use different branch based on `upstream/master` when you start working.
Link to Problem Specification for the exercise - https://github.com/exercism/problem-specifications/tree/master/exercises/bowling

**Comment by cmccandless** [comment]
Updated list of unimplemented exercises:

- bank-account (#757, #1260)
- sgf-parsing
- ledger
- hangman (#1160)
- passio
- rational numbers

**Comment by cmccandless** [comment]
@pythonmite `affine-cipher` [has already been implemented](https://github.com/exercism/python/tree/master/exercises/affine-cipher).

If you are still interested in contributing here, please check our [list of open issues](https://github.com/exercism/python/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc).

**Comment by andrefpoliveira** [comment]
Hey! I would like to implement a new exercise. But I don't know Passio. Can you explain? Thank you!

**Comment by cmccandless** [comment]
Hi @andrefpoliveira !

Actually we just merged #2195, which implements `passio`. And there is an open PR for hangman which was placed on hold by the maintainers. However...

We have a great deal of work still needed for our new Concept exercises. By the launch of v3, they will be relocated to this repository, but for now, they are being developed for all language tracks here: https://github.com/exercism/v3. We would greatly appreciate contribution there! If you wish to keep to the Python track, simply look at the open issues here: https://github.com/exercism/v3/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc++python.

**Comment by cmccandless** [comment]
Regarding this issue: all unimplemented issues from problem-specifications have either been implemented or put on hold, so this issue will be closed.
