### ISSUE TITLE
Add example test to README

### ISSUE THREAD

**Issue by TApicella** [exercism/python#480]
Currently, README files have a description of the exercise and goals, but refrain from mentioning implementation details However, the test suite does require a specific format for inputs and outputs, particularly for handling invalid results (some check for a raised exception, others will accept an empty string).

Including one of the tests in the README would give a programmer all of the information they need to proceed in one place.

**Comment by behrtam** [comment]
The READMEs for the exercises are maintained language independent: https://github.com/exercism/x-common/tree/master/exercises

As you mention exceptions ... so we would at least need to include a basic test and an exception test in the readme. If we would have multiple functions or a class with multiple methods, we would need to copy 2-5 tests into the readme and update them in both places if we change something. 

To me this doesn't look like a good idea. I also think one should have a look into the test suite while working on an exercise.
