### ISSUE TITLE
Change test suite naming convention to use test_ as a prefix

### ISSUE THREAD

**Issue by TApicella** [exercism/python#481]
Currently, the naming convention is foo.py and foo_test.py.  Changing to test_foo.py would be more tab-complete friendly when using the command line.

**Comment by behrtam** [comment]
We might have to check if this plays well with [configlet](https://github.com/exercism/configlet) and we would need to update [check-exercises.py](https://github.com/exercism/xpython/blob/master/test/check-exercises.py) but I think that should be possible.
