### ISSUE TITLE
kindergarten-garden: bugs in unit test

### ISSUE THREAD

**Issue by chuckwondo** [exercism/python#487]
The `test_disordered_test` method has 2 bugs in it. The following calls specify the wrong student names:

```python
garden.plants("Patricia")
garden.plants("Xander")
```
The correct names, are `"Samantha"` and `"Roger"`, respectively.

**Comment by behrtam** [comment]
As discussed in #423 they are not wrong but the tests should definitely be updated according to the new canonical test data.

**Comment by chuckwondo** [comment]
I'm not sure I quite follow what #423 is trying to solve, but I believe the test case is actually wrong.

Regardless of the fact that the names are different from the "default" names, the names that I claim are erroneous do not line up with the list of names and the list of plant codes in `test_disordered_test`, which is why I'm claiming them to be erroneous. Changing them to the names I specified allows the test to pass when the rest of the tests also pass.

However, perhaps I'm missing the point of `test_disordered_test`. I certainly don't know why the test is named as it is. How does "disordered" make sense in the context of this problem?
