### ISSUE TITLE
Gitter Room... migrate to exercism/python

### ISSUE THREAD

**Issue by kotp** [exercism/python#512]
The room (and badge in Readme) would do well to be moved to https://gitter.im/exercism/python as currently references to issues here are becoming broken, and the link to the chat room is also broken from the Readme file.

**Comment by m-a-ge** [comment]
I am not that familiar with Gitter and not sure how one can create a chat room and redirect others to a new one. Should investigate

**Comment by kotp** [comment]
How I did it for the Ruby (and others) room was create the new room, and announce in the old room.  I also added them in manually to the new room.  I then took about a week or so (over a weekend for sure, maybe two) to give time to know about the room.  And eventually deleted the old room.

**Comment by kotp** [comment]
Once the room is created on Gitter, the links in the Readme will automatically work, as they point to python, rather than xpython.

**Comment by behrtam** [comment]
@kotp thanks for the detailed steps https://gitter.im/exercism/python
