### ISSUE TITLE
Increase 80-character limit for linting to 120(?) chars

### ISSUE THREAD

**Issue by matthewmorgan** [exercism/python#520]
The 80-character limit made sense when most people were using low-resolution displays without a lot of screen real estate, but its usefulness has passed.

It seems good to have a limit, but does it need to stay at a mere 80 characters?

**Comment by behrtam** [comment]
#299 #434 ... I once was against this strict limit, but it's a de facto standard in the Python world.
I would not say "its usefulness has passed", if you solve exercises in split view with the code and the tests side by side it still helps. Also we have to have a limit at some point, so why not use the suggested limit from the official Python style guid `PEP8`.

**Comment by matthewmorgan** [comment]
@behrtam I guess this is a 'tabs vs spaces' kind of a thing.  As a contributor (potential contributor?) to the track, it's painful to have my builds fail because one of my lines is 81 characters long.  I do think that maybe a 16-year old style guide should be taken with a grain of salt, but I understand that's a choice that the track maintainers have made.

The contributing guide mentions PEP8 being the standard for the repo, so that was clearly an oversight on my part.
