### ISSUE TITLE
Complex Numbers: Incorrect test case

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#527]
Case `test_multiply_numbers_with_real_and_imaginary_part` appears to test under the assumption that the correct implementation of (a + bi) * (c + di) = (ac + bdi) (or, using the data from the test: (1 + 2i) * (-5 + 10i) is expected to equal (-5 + 20i)). 

The correct formula for this operation is [(a + bi) * (c  + di) = (ac - bd) + (ad + bc)i](http://mathworld.wolfram.com/ComplexMultiplication.html). Again, to use the text inputs, (1 + 2i) * (-5 + 10i) should equal (-5 - 20) + (10 - 10)i = -25 + 0i.

**Comment by m-a-ge** [comment]
@lilislilit could you please take a look at it when you have some time?

**Comment by cmccandless** [comment]
Due to my lack of knowledge of how GitHub web works, I accidentally created a new issue, #528, and attached a pull request.

**Comment by lilislilit** [comment]
@cmccandless thanks a bunch for the fix, I was away from civilization for quite some time

**Comment by m-a-ge** [comment]
@cmccandless I've merged #528
@lilislilit I'm glad you're back :simple_smile:
