### ISSUE TITLE
alphametics: not all intended tests are run

### ISSUE THREAD

**Issue by shaleh** [exercism/python#530]
When using Python's `unittest` framework, a test method must have the word 'test' in it.

 * solution_must_have_unique_value_for_each_letter
 * leading_zero_solution_is_invalid
 * puzzle_with_six_letters

Are all not run. You can see this with `python ./alphametics_test.py -v`.

**Comment by m-a-ge** [comment]
Thanks for creating this one, @shaleh!

**Comment by shaleh** [comment]
I can submit a PR.

**Comment by m-a-ge** [comment]
@shaleh, it would be really appreciated

**Comment by m-a-ge** [comment]
@shaleh, thanks for your help and sorry for the delay!

**Comment by shaleh** [comment]
No worries @m-a-ge
