### ISSUE TITLE
alphametics: please order the unit tests

### ISSUE THREAD

**Issue by shaleh** [exercism/python#531]
Python runs the tests based on their alphabetic sorting not their physical order in the file.

It would be nice to have the small cases first and then the larger. The invalid checks are fine at the beginning or the end.

**Comment by behrtam** [comment]
Important point, never thought about that.

**Comment by sjwarner-bp** [comment]
```loader = unittest.TestLoader()
loader.sortTestMethodsUsing(None)```

I think that the above would prevent sorting alphabetically, but presumably this would need to be inserted into every exercise test suite?

**Comment by shaleh** [comment]
Sounds like the easiest and most attractive solution. The other is to embed the order in the method names: `test001FirstTest` `test002AnotherTest` and so one.
