### ISSUE TITLE
grep: why is a unit test messing with files??

### ISSUE THREAD

**Issue by shaleh** [exercism/python#534]
This is what mocking and monkey patching are for.

**Comment by behrtam** [comment]
Sure, but how would you do it without 3rd party stuff and still support Python2.X. `unittest.mock.mock_open` would be perfect for this, but it is only available since Python3.3 I think. 

https://docs.python.org/3/library/unittest.mock.html#mock-open

**Comment by shaleh** [comment]
Pass in a "file" object. Then you can use fake files.

On October 1, 2017 1:55:23 AM PDT, Tammo Behrends <notifications@github.com> wrote:
>Sure, but how would you do it without 3rd party stuff and still support
>Python2.X. `unittest.mock.mock_open` would be perfect for this, but it
>is only available since Python3.3 I think. 
>
>https://docs.python.org/3/library/unittest.mock.html#mock-open
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/exercism/python/issues/534#issuecomment-333362829

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by cmccandless** [comment]
@shaleh If you would like to improve on the current implementation, feel free to submit a pull request.
