### ISSUE TITLE
binary-search: ValueError is the wrong exception to use

### ISSUE THREAD

**Issue by shaleh** [exercism/python#535]
From the Python docs:

    ValueError Raised when a built-in operation or function receives an argument
    that has the right type but an inappropriate value
    
Why not have the test mimic the result of `find` and return -1?

I like how the Go version of this exercise has the developer return the position the requested item would have in the container if the item is not found. So the user of the routine could add a new element to the container and keep it sorted. This makes it a bit more challenging. As written, the tests work if I just do a simple walk from beginning to end.

**Comment by tallpants** [comment]
@shaleh `ValueError` is what's raised by the `index()` method, which is why I think it's fine here as well.

See: https://docs.python.org/3.6/tutorial/datastructures.html?highlight=index

**Comment by shaleh** [comment]
Fair enough. `index` gives the impression that the item is expected to exist the user just does not know where. Search does not give that same impression. But I can see why it was chosen here.
