### ISSUE TITLE
accumulate: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#537]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by smt923** [comment]
Looks like accumlate already has parameters in it's placeholder? If it should be something else I'd like to work on this but it looks okay already to me:

```python
def accumulate(array, function):
pass
```
https://github.com/exercism/python/blob/master/exercises/accumulate/accumulate.py#L1

**Comment by m-a-ge** [comment]
@smt923 thanks for checking. 
I believe we can change existing names to something more meaningful
What do you think?

**Comment by smt923** [comment]
I was gonna say, I feel like if anything they should match the README, and that seems to have done it ^

**Comment by m-a-ge** [comment]
@smt923 thanks for clarification
