### ISSUE TITLE
all-your-base: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#538]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by smt923** [comment]
I'd like to work on this - if there's no placeholder already should I add it (all_your_base.py)? With the added parameters too of course

**Comment by m-a-ge** [comment]
@smt923 oh, that should be fixed, thanks!
