### ISSUE TITLE
beer-song: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#543]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by jnaulty** [comment]
@m-a-ge 
beer-song: :robot:  already [parameterized](https://github.com/exercism/python/blob/master/exercises/beer-song/beer_song.py#L1) :robot: 
:man_singer:

**Comment by m-a-ge** [comment]
@jnaulty sorry, bro, my bad.
And thanks for checking
