### ISSUE TITLE
binary-search: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#544]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by subkrish** [comment]
@m-a-ge This issue can be closed. The file already has parameters.

**Comment by m-a-ge** [comment]
@subkrish looks like it, thanks for checking

It would be great to change `array` to `list_of_numbers` or something similar. `array` does not sound Pythonish to me, maybe it's just me

**Comment by subkrish** [comment]
@m-a-ge Sure. I'm on it, I'll make the change.
