### ISSUE TITLE
binary: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#545]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by mostlybadfly** [comment]
I believe this placeholder already has parameters.  I just wanted to make sure I understand before taking a look. Is one needed here?

**Comment by m-a-ge** [comment]
@mostlybadfly this a good thing you asked before working on a PR. The exercise has a parameter (`string`), but it is too general, I think we come with something more meaningful
