### ISSUE TITLE
bracket-push: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#548]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by JanKaifer** [comment]
There already is parameter named "string" which is good enough i think. bracket_string_to_verify is too long in my opinion.

**Comment by m-a-ge** [comment]
Honestly I don't like 'string` option since it does not give any real meaning. I guess it's better to have something more suitable

**Comment by JanKaifer** [comment]
In PR #583 we (with @atg-abhishek) came up with `input_string` and `bracket_string`. Don't know which describes parameter better.
