### ISSUE TITLE
collatz-conjecture: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#552]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by smt923** [comment]
Working on this one as well (a lot of these are done already, should I make another issue marking ones which have examples + parameters?)

**Comment by m-a-ge** [comment]
@smt923 no. I think I'll have to go over all exercises after all open issues will be closed to check everything once again
