### ISSUE TITLE
perfect-numbers: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#607]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by saurabhchalke** [comment]
I would like to take take this up.

**Comment by saurabhchalke** [comment]
Fixed the issue in #675

**Comment by saurabhchalke** [comment]
Issue fixed in #688
