### ISSUE TITLE
phone-number: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#608]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by saurabhchalke** [comment]
I would like to contribute to this one.

**Comment by saurabhchalke** [comment]
I have fixed the issue in #675

**Comment by saurabhchalke** [comment]
Issue fixed in #687

**Comment by m-a-ge** [comment]
there are two PRs for the same issue: #591 and #687
@Sukhj1nder created his PR first, so it would be fair to merge it.

@saurabhchalke, don't be discouraged, there will be enough issues in this repo thought the month

**Comment by Sukhj1nder** [comment]
@m-a-ge Is there any issue with the commit, or is it all good to merge?

**Comment by m-a-ge** [comment]
I want to hear @saurabhchalke`s opinion and we will figure something out

**Comment by Sukhj1nder** [comment]
cool, sounds good. :)

**Comment by saurabhchalke** [comment]
Alright, no problem. I'll look for some other issue in the repo. @m-a-ge
