### ISSUE TITLE
point-emulations: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#610]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by cmccandless** [comment]
This exercise is deprecated; should we bother fixing it?

**Comment by m-a-ge** [comment]
@cmccandless deprecated, could give more details? I'm a bit lost

**Comment by cmccandless** [comment]
From the [README](/exercism/python/blob/master/exercises/point-mutations/README.md) for point-mutations:

>Note: This problem is deprecated, replaced by the one called hamming.
