### ISSUE TITLE
robot-name: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#621]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by subkrish** [comment]
@m-a-ge Do parameters need to be added this file also? Looks like it is already there.

**Comment by m-a-ge** [comment]
Yeah, looks like parameters are not required for this one due nature of the exercise, output is generated upon class creation.

I'm closing the issue. Thanks for checking, @subkrish
