### ISSUE TITLE
series: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#638]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by a-arpit94** [comment]
#656

**Comment by m-a-ge** [comment]
#656 was closed and not merged, a separate PR for this particular exercise is needed

**Comment by rohitrango** [comment]
Is this issue still open?

**Comment by m-a-ge** [comment]
@rohitrango yeah, I think so, since there are no open PRs linked to the issue

**Comment by rohitrango** [comment]
I'm getting myself familiar with the platform, after which I can start working on it. Can I?

**Comment by rohitrango** [comment]
So I did a little bit of homework and found that there should ideally be one PR for each exercise. This issue doesn't point to any specific exercise. Should I search and fix some other issue? Please correct me if I'm wrong.

**Comment by m-a-ge** [comment]
@rohitrango the name of the exercise is stated in the header of the issue:
 `series: add parameters to exercise placeholder`

Yes, there should be one PR per one issue, it's easier that way to review them
