### ISSUE TITLE
sum-of-multiples: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#644]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by ackerleytng** [comment]
Hi! This is my first pull request ever! I'm trying to understand how pull requests work... 

I've completed all the necessary edits and pushed to my `sum-of-multiples-add-parameters` branch at `ackerleytng/python`.

Do I have to make another pull request after this push, or is this good enough?

**Comment by m-a-ge** [comment]
@ackerleytng no, it looks Ok. I merged it btw 😄

**Comment by ackerleytng** [comment]
Thanks!
