### ISSUE TITLE
triangle: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#647]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by rozuur** [comment]
I would like to work on this.

**Comment by m-a-ge** [comment]
@rozuur ok, feel free to create an empty [work in progress] PR

**Comment by rozuur** [comment]
@m-a-ge done

**Comment by m-a-ge** [comment]
@rozuur I left a minor comment in your PR, please take a look

**Comment by rozuur** [comment]
@m-a-ge I have used side_a, side_b and side_c notation instead of x,y, and z.
