### ISSUE TITLE
word-search: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#653]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by gabriellhrn** [comment]
It looks like [it's done for `word-search`](https://github.com/exercism/python/blob/master/exercises/word-search/word_search.py#L26).

**Comment by m-a-ge** [comment]
@gabriellhrn thanks, looks like I opened it by mistake
