### ISSUE TITLE
zebra-puzzle: add parameters to exercise placeholder

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#655]
We would like you to help us add expected parameters in placeholder templates as described in #509 to make it easier for learners to start working on the exercise in question.

Feel free to ask any questions, we'll be glad to help!

**Comment by mikeyny** [comment]
Hy , @m-a-ge  can i work on this ?

**Comment by mikeyny** [comment]
I've been looking at the test case though , it seems the function doesn't take any parameters

**Comment by m-a-ge** [comment]
Ops, my bad. @mikeyny, thanks for checking
