### ISSUE TITLE
Assign open issues to user once claimed

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#720]
Especially with the high number of open issues for Hacktoberfest, it would be very helpful to make an effort to actually assign issues to a user once they have begun working on a fix. This way, it is easy to filter on unassigned to see what issues are not yet being worked on.

Recommend "discussion" label for this issue.

**Comment by m-a-ge** [comment]
Ok, I'll bear that in mind, thanks

**Comment by m-a-ge** [comment]
@cmccandless, 

Looks like it isn't possible, from [docs](https://help.github.com/articles/assigning-issues-and-pull-requests-to-other-github-users/)

> You can only create assignments for yourself, collaborators on personal projects, or members of your organization with read permissions on the repository.

I suggest claiming the issue with empty [WIP] PR (with this tag in its title stating that work is in progress)

**Comment by cmccandless** [comment]
Good to know, thanks for looking into it.
