### ISSUE TITLE
simple-linked-list: implement exercise

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#738]
There are exercises that are not yet implemented in Python track (the full list of them - https://github.com/exercism/python/issues/417#issuecomment-334841778).
You can help us change this situation by implementing this one. Ref #417

The guide ["Implement an exercise from specification"](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md) will help you succeed.

If you still have questions, I encourage you to ask them before starting working on the issue.

I also suggest claiming the issue by creating an empty PR as stated [here](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work)

Please note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge.
This simple thing helps us a lot, and makes our life a bit easier

**Comment by m-a-ge** [comment]
You can find #385 useful

**Comment by akshitgrover** [comment]
@m-a-ge I will work on this, but since this PR won't count if i enable automatic merge, so please merge this PR manually, Cool?

**Comment by m-a-ge** [comment]
@akshitgrover I didn't quite understand what you mean, could you clarify?

**Comment by akshitgrover** [comment]
Read hactoberfest rules.

**Comment by m-a-ge** [comment]
@akshitgrover 
> Rules
> To get a shirt, you must make four pull requests between October 1–31 in any timezone. Pull requests can be to any public repo on GitHub, not just the ones we’ve highlighted. The pull request must contain commits you made yourself. Pull requests reported by maintainers as spam or that are automated will be marked as invalid and won’t count towards the shirt.
> 
>from https://hacktoberfest.digitalocean.com/

And?
