### ISSUE TITLE
binary-search-tree: implement exercise

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#740]
There are exercises that are not yet implemented in Python track (the full list of them - https://github.com/exercism/python/issues/417#issuecomment-334841778).
You can help us change this situation by implementing this one. Ref #417

The guide ["Implement an exercise from specification"](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md) will help you succeed.

If you still have questions, I encourage you to ask them before starting working on the issue.

I also suggest claiming the issue by creating an empty PR as stated [here](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work)

Please note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge.
This simple thing helps us a lot, and makes our life a bit easier

**Comment by m-a-ge** [comment]
#388 can be useful

**Comment by rodrigocam** [comment]
I'm working on it!

**Comment by m-a-ge** [comment]
@rodrigocam, I suggest creating an empty [WIP] PR - https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work to claim it

**Comment by m-a-ge** [comment]
@rodrigocam ah, I see, you've done that, but forgot to add a reference to this issue in order to add visibility. I strongly recommend always doing it, it saves a lot of time.

Please also note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge. 
It makes our work much easier. I hope this hint will help you to make your future PRs a bit better

**Comment by rodrigocam** [comment]
Alright, thanks! Which methods do you want in the binary search tree? I create an insert method and preorder, inorder and postorder traversals.

**Comment by rodrigocam** [comment]
I made a pull request with the implementation, please take a look!

**Comment by m-a-ge** [comment]
@rodrigocam thanks! You've created two PRs #773 and #768. Could you please close one to avoid confusion.

> Which methods do you want in the binary search tree? 
It's up to you

**Comment by rodrigocam** [comment]
Ok, sorry. I closed one of them, please take a look (:
