### ISSUE TITLE
hangman: implement exercise

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#745]
There are exercises that are not yet implemented in Python track (the full list of them - https://github.com/exercism/python/issues/417#issuecomment-334841778).
You can help us change this situation by implementing this one. Ref #417

The guide ["Implement an exercise from specification"](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md) will help you succeed.

If you still have questions, I encourage you to ask them before starting working on the issue.

I also suggest claiming the issue by creating an empty PR as stated [here](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work)

Please note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge.
This simple thing helps us a lot, and makes our life a bit easier

**Comment by vaibhavsingh97** [comment]
can i take up this issue?

**Comment by m-a-ge** [comment]
@vaibhavsingh97 of course

I suggest creating an empty [WIP] PR - https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work to claim it

**Comment by khoa102** [comment]
Hi, I wonder if I can take up this issues as my first contribution for open source?

**Comment by cmccandless** [comment]
@khoa102 Absolutely! Issues can be claimed by creating a PR for them. Please remember to put `Fixes #745` in the PR description to link the PR to this issue.

**Comment by khoa102** [comment]
Great! @cmccandless

**Comment by khoa102** [comment]
Hi, can anyone take a look at the PR for this issue that I submit a few day ago? I would also want to know what should I put for the config of this exercise, like the difficulty, unlock or topic?

**Comment by anshima1** [comment]
Hey is this issue solved? If not, I'll like to work on it.

**Comment by cmccandless** [comment]
@anshima1 No, this issue is not yet resolved.

If you wish to work on this, I highly suggest reviewing the discussion in #1160.

**Comment by junming403** [comment]
Hi is this issue still relevant? I would like to work on it.

**Comment by cmccandless** [comment]
@junming403 It is still relevant, yes. 

Also, as stated above:

> If you wish to work on this, I highly suggest reviewing the discussion in #1160.

**Comment by junming403** [comment]
Hi thank you for the prompt response! I have looked at the thread of discussion. Notice it did not use  FRP, I am considering make this exercise based on FRP library(http://reactivex.io/intro.html). What should do if the exercise rely on the library? Any guidance?

**Comment by cmccandless** [comment]
RE: the track [README](https://github.com/exercism/python/blob/master/README.md#conventions)

> We use unittest (Python Standard Library) and no 3rd-party-framework.

It would be preferable that we stick to that.
