### ISSUE TITLE
food-chain: implement exercise

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#750]
There are exercises that are not yet implemented in Python track (the full list of them - https://github.com/exercism/python/issues/417#issuecomment-334841778).
You can help us change this situation by implementing this one. Ref #417

The guide ["Implement an exercise from specification"](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md) will help you succeed.

If you still have questions, I encourage you to ask them before starting working on the issue.

I also suggest claiming the issue by creating an empty PR as stated [here](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work)

Please note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge.
This simple thing helps us a lot, and makes our life a bit easier

**Comment by LU4XLII** [comment]
Can i?

**Comment by m-a-ge** [comment]
@LU4XLII sure, have fun
I suggest creating an empty [WIP]  PR - https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work to claim it

**Comment by Rajdeep400** [comment]
can i ?

**Comment by m-a-ge** [comment]
@Rajdeep400 I'd say yes since @LU4XLII the closed claiming PR

@LU4XLII, do you still working on this?

**Comment by LU4XLII** [comment]
@m-a-ge I have made a second pull request with the complete exercise.

**Comment by m-a-ge** [comment]
@LU4XLII could you reference this issue in your PR description to indicate that you're working on it?

It's generally not a good idea to closing existing PR and creating a new one because it's harder for maintainers to track progress etc. If you are not sure how to update already opened PR, feel free to ask

**Comment by LU4XLII** [comment]
@m-a-ge I have updated the original pull request and closed the second, is this ok now?

**Comment by m-a-ge** [comment]
@LU4XLII give me some time to review it :godmode:
