### ISSUE TITLE
Hacktoberfest topic missing from repository topics

### ISSUE THREAD

**Issue by cmccandless** [exercism/python#786]
To fully participate in Hacktoberfest, the `hacktoberfest` topic should be added to the repository. See [openfaas/faas](https://github.com/openfaas/faas) for example.

**Comment by m-a-ge** [comment]
Thanks for the tip, but I can't change repo description and list of topics

**Comment by cmccandless** [comment]
Actually, this is my fault, I missed something. Looking at the [rules for maintainers](https://hacktoberfest.digitalocean.com), simply tagging issues with `hacktoberfest` should be enough.
