### ISSUE TITLE
perfect-numbers: add topics

### ISSUE THREAD

**Issue by m-a-ge** [exercism/python#848]
As stated in #808 we need to add topics for exercises. They should be relevant to the exercise even though you might be able to solve it without encountering that topic. Here is the list of commonly used topics in every track - https://github.com/exercism/problem-specifications/blob/master/TOPICS.txt, please use topics from this list or add one if you think it's missing but required.
Hint: you can take a look at an example implementation here (SPOILERS) or in a different language.

There are some exercises which have topics in `config.json`, so you can look at them as an example.

If you still have questions, I encourage you to ask them before starting working on the issue.

I also suggest claiming the issue by creating an empty PR as discribded [here](https://github.com/exercism/docs/blob/master/you-can-help/implement-an-exercise-from-specification.md#avoiding-duplicate-work)

Please note that there are some special ['closing issue' keywords](https://help.github.com/articles/closing-issues-using-keywords/) that you can put in description of your PR and Github will take care of closing the corresponding issue automatically after merge.
This simple thing helps us a lot, and makes our life a bit easier, so please reference the issue in your PR accordingly.

**Comment by VibhuKesar** [comment]
Hello, I am in a little dilemma. I committed topics for Luhn and made a PR, now I added topics for current https://github.com/exercism/python/issues/848 issue too and made commit. Should I make one more PR ? It will be very generous of you, if you could aid me regarding the same.
Thanks

**Comment by m-a-ge** [comment]
@VibhuKesar the problem is that you used your `master` branch for creating both PRs.
Anything you push to that branch (`master` in your case) will appear in both PRs automatically. For that reason it's always a good reason to always use different branches for creating PRs, it's a main idea in git, always use them.
Plus, `master` branch has a special meaning and isn't recommended to work directly in it (there some exceptions of course).
Does it makes sense? 

Feel free to ask questions

**Comment by VibhuKesar** [comment]
Thanks, I understood. So, I should create both PRs again and push it to a different branch rather than master?

**Comment by VibhuKesar** [comment]
https://github.com/exercism/python/pull/949 I make another, I hope I did correct this time. Thanks

**Comment by m-a-ge** [comment]
@VibhuKesar no, not really.
There are two commits for different exercises in your PR - https://github.com/exercism/python/pull/949/commits

You should create two separate Pull Requests from two different branches which in turn should contain respective commit

**Comment by m-a-ge** [comment]
@VibhuKesar could you create the PR for this one?

**Comment by VibhuKesar** [comment]
Yeah sure thing. I will make one asap.

**Comment by VibhuKesar** [comment]
@m-a-ge  https://github.com/exercism/python/pull/961 
I have made the PR for perfect numbers. I hope this is fine. Thanks
